// Generated by oapi-codegen-cli (1.0.0)

/**
 * Thrown by every AdminOrderApiClient method when the HTTP response is not 2xx.
 * Carries the status code and the response body parsed per the response's declared
 * content-type (JSON parsed object, text body for `text/*`, raw `Blob` for binary,
 * or `undefined` when the response had no body).
 */
export class ApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly statusText: string,
    public readonly body: unknown,
  ) {
    super(`HTTP ${status}: ${statusText}`);
    this.name = 'ApiError';
  }
}
import type { AdminOrderFindAllResponse } from '../model/admin-order-find-all-response';
import type { AdminOrderResponse } from '../model/admin-order-response';

export interface Pageable {
  page?: number;
  size?: number;
  sort?: string;
}

/**
 * Credentials for AdminOrderApi. One field per declared security scheme;
 * supply the value for the scheme(s) the operation you call requires.
 *   - `api-key` schemes carry the raw key (set as the configured header / query / cookie).
 *   - `http-bearer` / `oauth2` / `openid-connect` carry the token (sent as `Authorization: Bearer …`).
 *   - `http-basic` carries the already-base64-encoded `username:password` (sent as `Authorization: Basic …`).
 */
export interface AdminOrderApiCredentials {
  /** Scheme `BearerAuth` (`http-bearer`). */
  bearerAuth?: string;
}

/**
 * AdminOrder API
 */
export interface AdminOrderApi {

  /**
   * List orders across all customers. Omit user_uid for the unscoped list.
   * Errors:
   * 400 (BadRequestError) — The server could not understand the request due to invalid syntax.
   * 401 (UnauthorizedError) — Access is unauthorized.
   * 403 (ForbiddenError) — Access is forbidden.
   */
  adminOrdersListOrders(
    userUid: string | undefined,
    status: string | undefined,
    pageable: Pageable,
  ): Promise<AdminOrderFindAllResponse>;

  /**
   * Find an order by uid, with its lines and shipping destination
   * Errors:
   * 401 (UnauthorizedError) — Access is unauthorized.
   * 403 (ForbiddenError) — Access is forbidden.
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  adminOrdersReadOrder(
    uid: string,
  ): Promise<AdminOrderResponse>;

  /**
   * Cancel an order. The order service runs the compensation, so the returned order reflects its state at that moment.
   * Errors:
   * 400 (BadRequestError) — The server could not understand the request due to invalid syntax.
   * 401 (UnauthorizedError) — Access is unauthorized.
   * 403 (ForbiddenError) — Access is forbidden.
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  adminOrdersCancelOrder(
    uid: string,
  ): Promise<AdminOrderResponse>;
}

export class AdminOrderApiClient implements AdminOrderApi {
  private readonly baseUrl: string;
  private readonly credentials: AdminOrderApiCredentials;

  constructor(baseUrl: string, credentials: AdminOrderApiCredentials = {}) {
    this.baseUrl = baseUrl;
    this.credentials = credentials;
  }

  async adminOrdersListOrders(
    userUid: string | undefined,
    status: string | undefined,
    pageable: Pageable,
  ): Promise<AdminOrderFindAllResponse> {
    const params = new URLSearchParams();
    if (userUid !== undefined) params.append('user_uid', Array.isArray(userUid) ? (userUid as readonly unknown[]).join(',') : String(userUid));
    if (status !== undefined) params.append('status', Array.isArray(status) ? (status as readonly unknown[]).join(',') : String(status));
    if (pageable.page !== undefined) params.append('page', String(pageable.page));
    if (pageable.size !== undefined) params.append('size', String(pageable.size));
    if (pageable.sort !== undefined) params.append('sort', pageable.sort);
    const query = params.toString();
    const url = `${this.baseUrl}/api/v1/admin/orders${query ? `?${query}` : ''}`;
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as AdminOrderFindAllResponse;
  }

  async adminOrdersReadOrder(
    uid: string,
  ): Promise<AdminOrderResponse> {
    const url = `${this.baseUrl}/api/v1/admin/orders/${uid}`;
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as AdminOrderResponse;
  }

  async adminOrdersCancelOrder(
    uid: string,
  ): Promise<AdminOrderResponse> {
    const url = `${this.baseUrl}/api/v1/admin/orders/${uid}/cancel`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as AdminOrderResponse;
  }
}
