// Generated by oapi-codegen-cli (1.0.0)

/**
 * Thrown by every AdminRiskApiClient method when the HTTP response is not 2xx.
 * Carries the status code and the response body parsed per the response's declared
 * content-type (JSON parsed object, text body for `text/*`, raw `Blob` for binary,
 * or `undefined` when the response had no body).
 */
export class ApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly statusText: string,
    public readonly body: unknown,
  ) {
    super(`HTTP ${status}: ${statusText}`);
    this.name = 'ApiError';
  }
}
import type { AdminRiskEntryListResponse } from '../model/admin-risk-entry-list-response';
import type { AdminRiskEntryResponse } from '../model/admin-risk-entry-response';
import type { AdminRiskFlagRequest } from '../model/admin-risk-flag-request';

/**
 * Credentials for AdminRiskApi. One field per declared security scheme;
 * supply the value for the scheme(s) the operation you call requires.
 *   - `api-key` schemes carry the raw key (set as the configured header / query / cookie).
 *   - `http-bearer` / `oauth2` / `openid-connect` carry the token (sent as `Authorization: Bearer …`).
 *   - `http-basic` carries the already-base64-encoded `username:password` (sent as `Authorization: Basic …`).
 */
export interface AdminRiskApiCredentials {
  /** Scheme `BearerAuth` (`http-bearer`). */
  bearerAuth?: string;
}

/**
 * AdminRisk API
 */
export interface AdminRiskApi {

  /**
   * List all currently flagged principals
   * Errors:
   * 401 (UnauthorizedError) — Access is unauthorized.
   * 403 (ForbiddenError) — Access is forbidden.
   */
  adminRiskListRisk(
  ): Promise<AdminRiskEntryListResponse>;

  /**
   * Flag a principal (restrict = deny writes, block = deny all). An administrator may not flag themselves.
   * Errors:
   * 400 (BadRequestError) — The server could not understand the request due to invalid syntax.
   * 401 (UnauthorizedError) — Access is unauthorized.
   * 403 (ForbiddenError) — Access is forbidden.
   */
  adminRiskFlagRisk(
    uid: string,
    body: AdminRiskFlagRequest,
  ): Promise<AdminRiskEntryResponse>;

  /**
   * Remove a principal's risk flag
   * Errors:
   * 401 (UnauthorizedError) — Access is unauthorized.
   * 403 (ForbiddenError) — Access is forbidden.
   */
  adminRiskUnflagRisk(
    uid: string,
  ): Promise<void>;
}

export class AdminRiskApiClient implements AdminRiskApi {
  private readonly baseUrl: string;
  private readonly credentials: AdminRiskApiCredentials;

  constructor(baseUrl: string, credentials: AdminRiskApiCredentials = {}) {
    this.baseUrl = baseUrl;
    this.credentials = credentials;
  }

  async adminRiskListRisk(
  ): Promise<AdminRiskEntryListResponse> {
    const url = `${this.baseUrl}/api/v1/admin/risk`;
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as AdminRiskEntryListResponse;
  }

  async adminRiskFlagRisk(
    uid: string,
    body: AdminRiskFlagRequest,
  ): Promise<AdminRiskEntryResponse> {
    const url = `${this.baseUrl}/api/v1/admin/risk/${uid}`;
    const response = await fetch(url, {
      method: 'PUT',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
      body: JSON.stringify(body),
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as AdminRiskEntryResponse;
  }

  async adminRiskUnflagRisk(
    uid: string,
  ): Promise<void> {
    const url = `${this.baseUrl}/api/v1/admin/risk/${uid}`;
    const response = await fetch(url, {
      method: 'DELETE',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
  }
}
