// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { AuditItemRequest } from './audit-item-request';
import { AuditItemRequestSchema } from './audit-item-request';

export interface AuditCreateRequest {
  items: Array<AuditItemRequest>;
  notes?: string;
  warehouse_uid: string;
}

export const AuditCreateRequestSchema = z.object({
  items: z.array(AuditItemRequestSchema),
  notes: z.string().optional(),
  warehouse_uid: z.string(),
});
