// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface AuditItemResponse {
  actual_quantity: number;
  difference: number;
  edition_uid: string;
  system_quantity: number;
}

export const AuditItemResponseSchema = z.object({
  actual_quantity: z.number().int(),
  difference: z.number().int(),
  edition_uid: z.string(),
  system_quantity: z.number().int(),
});
