// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface BadRequestError {
  detail?: string;
  errors?: Array<string>;
  status: number;
  title: string;
  type?: string;
}

export const BadRequestErrorSchema = z.object({
  detail: z.string().optional(),
  errors: z.array(z.string()).optional(),
  status: z.number().int(),
  title: z.string(),
  type: z.string().optional(),
});
