// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { BalanceFindResponse } from './balance-find-response';
import { BalanceFindResponseSchema } from './balance-find-response';

export interface BalanceFindAllResponse {
  items: Array<BalanceFindResponse>;
  total: string;
}

export const BalanceFindAllResponseSchema = z.object({
  items: z.array(BalanceFindResponseSchema),
  total: z.string().regex(/^-?\d+$/),
});
