// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface BalanceFindResponse {
  adjust_quantity: number;
  current_quantity: number;
  edition_uid: string;
  inbound_quantity: number;
  outbound_quantity: number;
  warehouse_name: string;
  warehouse_uid: string;
}

export const BalanceFindResponseSchema = z.object({
  adjust_quantity: z.number().int(),
  current_quantity: z.number().int(),
  edition_uid: z.string(),
  inbound_quantity: z.number().int(),
  outbound_quantity: z.number().int(),
  warehouse_name: z.string(),
  warehouse_uid: z.string(),
});
