// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { ClosingFindResponse } from './closing-find-response';
import { ClosingFindResponseSchema } from './closing-find-response';

export interface ClosingFindAllResponse {
  items: Array<ClosingFindResponse>;
  total: string;
}

export const ClosingFindAllResponseSchema = z.object({
  items: z.array(ClosingFindResponseSchema),
  total: z.string().regex(/^-?\d+$/),
});
