// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface ClosingItemResponse {
  adjust_quantity: number;
  closing_quantity: number;
  edition_uid: string;
  inbound_quantity: number;
  opening_quantity: number;
  outbound_quantity: number;
}

export const ClosingItemResponseSchema = z.object({
  adjust_quantity: z.number().int(),
  closing_quantity: z.number().int(),
  edition_uid: z.string(),
  inbound_quantity: z.number().int(),
  opening_quantity: z.number().int(),
  outbound_quantity: z.number().int(),
});
