// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import { StockChangeType, StockChangeTypeSchema } from '../constant/stock-change-type';

export interface StockHistoryFindResponse {
  change_qty: number;
  change_type: StockChangeType;
  created_at: Date;
  reason?: string;
  uid: string;
}

export const StockHistoryFindResponseSchema = z.object({
  change_qty: z.number().int(),
  change_type: StockChangeTypeSchema,
  created_at: z.date(),
  reason: z.string().optional(),
  uid: z.string(),
});
