// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { StockWarehouseItem } from './stock-warehouse-item';
import { StockWarehouseItemSchema } from './stock-warehouse-item';

export interface StockFindResponse {
  edition_uid: string;
  total_quantity: number;
  uid: string;
  warehouses: Array<StockWarehouseItem>;
}

export const StockFindResponseSchema = z.object({
  edition_uid: z.string(),
  total_quantity: z.number().int(),
  uid: z.string(),
  warehouses: z.array(StockWarehouseItemSchema),
});
