// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

/**
 * Release stock from a warehouse (outbound)
 */

export interface StockReleaseRequest {
  edition_uid: string;
  quantity: number;
  reason?: string;
  warehouse_uid: string;
}

export const StockReleaseRequestSchema = z.object({
  edition_uid: z.string(),
  quantity: z.number().int(),
  reason: z.string().optional(),
  warehouse_uid: z.string(),
});
