// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import { TransferStatus, TransferStatusSchema } from '../constant/transfer-status';

export interface TransferFindResponse {
  completed_at?: Date;
  created_at: Date;
  edition_uid: string;
  quantity: number;
  reason?: string;
  source_warehouse_uid: string;
  status: TransferStatus;
  target_warehouse_uid: string;
  uid: string;
  updated_at?: Date;
}

export const TransferFindResponseSchema = z.object({
  completed_at: z.date().optional(),
  created_at: z.date(),
  edition_uid: z.string(),
  quantity: z.number().int(),
  reason: z.string().optional(),
  source_warehouse_uid: z.string(),
  status: TransferStatusSchema,
  target_warehouse_uid: z.string(),
  uid: z.string(),
  updated_at: z.date().optional(),
});
