// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface WarehouseCreateRequest {
  address?: string;
  capacity: number;
  name: string;
}

export const WarehouseCreateRequestSchema = z.object({
  address: z.string().optional(),
  capacity: z.number().int(),
  name: z.string(),
});
