// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { WarehouseFindResponse } from './warehouse-find-response';
import { WarehouseFindResponseSchema } from './warehouse-find-response';

export interface WarehouseFindAllResponse {
  items: Array<WarehouseFindResponse>;
  total: string;
}

export const WarehouseFindAllResponseSchema = z.object({
  items: z.array(WarehouseFindResponseSchema),
  total: z.string().regex(/^-?\d+$/),
});
