// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface WarehouseUpdateRequest {
  address?: string;
  capacity?: number;
  name?: string;
}

export const WarehouseUpdateRequestSchema = z.object({
  address: z.string().optional(),
  capacity: z.number().int().optional(),
  name: z.string().optional(),
});
