/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as UnauthorizedRouteImport } from "./routes/unauthorized"
import { Route as AuthedRouteImport } from "./routes/_authed"
import { Route as AuthedIndexRouteImport } from "./routes/_authed/index"
import { Route as AuthedUsersIndexRouteImport } from "./routes/_authed/users/index"
import { Route as AuthedSettlementsIndexRouteImport } from "./routes/_authed/settlements/index"
import { Route as AuthedRiskIndexRouteImport } from "./routes/_authed/risk/index"
import { Route as AuthedRefundsIndexRouteImport } from "./routes/_authed/refunds/index"
import { Route as AuthedPaymentsIndexRouteImport } from "./routes/_authed/payments/index"
import { Route as AuthedOrdersIndexRouteImport } from "./routes/_authed/orders/index"
import { Route as AuthedCatalogIndexRouteImport } from "./routes/_authed/catalog/index"
import { Route as AuthedUsersUidRouteImport } from "./routes/_authed/users/$uid"
import { Route as AuthedSettlementsUidRouteImport } from "./routes/_authed/settlements/$uid"
import { Route as AuthedRefundsUidRouteImport } from "./routes/_authed/refunds/$uid"
import { Route as AuthedPaymentsUidRouteImport } from "./routes/_authed/payments/$uid"
import { Route as AuthedOrdersUidRouteImport } from "./routes/_authed/orders/$uid"
import { Route as AuthedCatalogNewRouteImport } from "./routes/_authed/catalog/new"
import { Route as AuthedCatalogUidRouteImport } from "./routes/_authed/catalog/$uid"
import { Route as AuthedInventoryWarehousesIndexRouteImport } from "./routes/_authed/inventory/warehouses/index"
import { Route as AuthedInventoryStocksIndexRouteImport } from "./routes/_authed/inventory/stocks/index"
import { Route as AuthedInventoryWarehousesUidRouteImport } from "./routes/_authed/inventory/warehouses/$uid"

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: "/unauthorized",
  path: "/unauthorized",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersIndexRoute = AuthedUsersIndexRouteImport.update({
  id: "/users/",
  path: "/users/",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettlementsIndexRoute = AuthedSettlementsIndexRouteImport.update({
  id: "/settlements/",
  path: "/settlements/",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRiskIndexRoute = AuthedRiskIndexRouteImport.update({
  id: "/risk/",
  path: "/risk/",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRefundsIndexRoute = AuthedRefundsIndexRouteImport.update({
  id: "/refunds/",
  path: "/refunds/",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPaymentsIndexRoute = AuthedPaymentsIndexRouteImport.update({
  id: "/payments/",
  path: "/payments/",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrdersIndexRoute = AuthedOrdersIndexRouteImport.update({
  id: "/orders/",
  path: "/orders/",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCatalogIndexRoute = AuthedCatalogIndexRouteImport.update({
  id: "/catalog/",
  path: "/catalog/",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersUidRoute = AuthedUsersUidRouteImport.update({
  id: "/users/$uid",
  path: "/users/$uid",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettlementsUidRoute = AuthedSettlementsUidRouteImport.update({
  id: "/settlements/$uid",
  path: "/settlements/$uid",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRefundsUidRoute = AuthedRefundsUidRouteImport.update({
  id: "/refunds/$uid",
  path: "/refunds/$uid",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPaymentsUidRoute = AuthedPaymentsUidRouteImport.update({
  id: "/payments/$uid",
  path: "/payments/$uid",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrdersUidRoute = AuthedOrdersUidRouteImport.update({
  id: "/orders/$uid",
  path: "/orders/$uid",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCatalogNewRoute = AuthedCatalogNewRouteImport.update({
  id: "/catalog/new",
  path: "/catalog/new",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCatalogUidRoute = AuthedCatalogUidRouteImport.update({
  id: "/catalog/$uid",
  path: "/catalog/$uid",
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInventoryWarehousesIndexRoute =
  AuthedInventoryWarehousesIndexRouteImport.update({
    id: "/inventory/warehouses/",
    path: "/inventory/warehouses/",
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedInventoryStocksIndexRoute =
  AuthedInventoryStocksIndexRouteImport.update({
    id: "/inventory/stocks/",
    path: "/inventory/stocks/",
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedInventoryWarehousesUidRoute =
  AuthedInventoryWarehousesUidRouteImport.update({
    id: "/inventory/warehouses/$uid",
    path: "/inventory/warehouses/$uid",
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof AuthedIndexRoute
  "/unauthorized": typeof UnauthorizedRoute
  "/catalog/$uid": typeof AuthedCatalogUidRoute
  "/catalog/new": typeof AuthedCatalogNewRoute
  "/orders/$uid": typeof AuthedOrdersUidRoute
  "/payments/$uid": typeof AuthedPaymentsUidRoute
  "/refunds/$uid": typeof AuthedRefundsUidRoute
  "/settlements/$uid": typeof AuthedSettlementsUidRoute
  "/users/$uid": typeof AuthedUsersUidRoute
  "/catalog/": typeof AuthedCatalogIndexRoute
  "/orders/": typeof AuthedOrdersIndexRoute
  "/payments/": typeof AuthedPaymentsIndexRoute
  "/refunds/": typeof AuthedRefundsIndexRoute
  "/risk/": typeof AuthedRiskIndexRoute
  "/settlements/": typeof AuthedSettlementsIndexRoute
  "/users/": typeof AuthedUsersIndexRoute
  "/inventory/warehouses/$uid": typeof AuthedInventoryWarehousesUidRoute
  "/inventory/stocks/": typeof AuthedInventoryStocksIndexRoute
  "/inventory/warehouses/": typeof AuthedInventoryWarehousesIndexRoute
}
export interface FileRoutesByTo {
  "/unauthorized": typeof UnauthorizedRoute
  "/": typeof AuthedIndexRoute
  "/catalog/$uid": typeof AuthedCatalogUidRoute
  "/catalog/new": typeof AuthedCatalogNewRoute
  "/orders/$uid": typeof AuthedOrdersUidRoute
  "/payments/$uid": typeof AuthedPaymentsUidRoute
  "/refunds/$uid": typeof AuthedRefundsUidRoute
  "/settlements/$uid": typeof AuthedSettlementsUidRoute
  "/users/$uid": typeof AuthedUsersUidRoute
  "/catalog": typeof AuthedCatalogIndexRoute
  "/orders": typeof AuthedOrdersIndexRoute
  "/payments": typeof AuthedPaymentsIndexRoute
  "/refunds": typeof AuthedRefundsIndexRoute
  "/risk": typeof AuthedRiskIndexRoute
  "/settlements": typeof AuthedSettlementsIndexRoute
  "/users": typeof AuthedUsersIndexRoute
  "/inventory/warehouses/$uid": typeof AuthedInventoryWarehousesUidRoute
  "/inventory/stocks": typeof AuthedInventoryStocksIndexRoute
  "/inventory/warehouses": typeof AuthedInventoryWarehousesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_authed": typeof AuthedRouteWithChildren
  "/unauthorized": typeof UnauthorizedRoute
  "/_authed/": typeof AuthedIndexRoute
  "/_authed/catalog/$uid": typeof AuthedCatalogUidRoute
  "/_authed/catalog/new": typeof AuthedCatalogNewRoute
  "/_authed/orders/$uid": typeof AuthedOrdersUidRoute
  "/_authed/payments/$uid": typeof AuthedPaymentsUidRoute
  "/_authed/refunds/$uid": typeof AuthedRefundsUidRoute
  "/_authed/settlements/$uid": typeof AuthedSettlementsUidRoute
  "/_authed/users/$uid": typeof AuthedUsersUidRoute
  "/_authed/catalog/": typeof AuthedCatalogIndexRoute
  "/_authed/orders/": typeof AuthedOrdersIndexRoute
  "/_authed/payments/": typeof AuthedPaymentsIndexRoute
  "/_authed/refunds/": typeof AuthedRefundsIndexRoute
  "/_authed/risk/": typeof AuthedRiskIndexRoute
  "/_authed/settlements/": typeof AuthedSettlementsIndexRoute
  "/_authed/users/": typeof AuthedUsersIndexRoute
  "/_authed/inventory/warehouses/$uid": typeof AuthedInventoryWarehousesUidRoute
  "/_authed/inventory/stocks/": typeof AuthedInventoryStocksIndexRoute
  "/_authed/inventory/warehouses/": typeof AuthedInventoryWarehousesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/unauthorized"
    | "/catalog/$uid"
    | "/catalog/new"
    | "/orders/$uid"
    | "/payments/$uid"
    | "/refunds/$uid"
    | "/settlements/$uid"
    | "/users/$uid"
    | "/catalog/"
    | "/orders/"
    | "/payments/"
    | "/refunds/"
    | "/risk/"
    | "/settlements/"
    | "/users/"
    | "/inventory/warehouses/$uid"
    | "/inventory/stocks/"
    | "/inventory/warehouses/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/unauthorized"
    | "/"
    | "/catalog/$uid"
    | "/catalog/new"
    | "/orders/$uid"
    | "/payments/$uid"
    | "/refunds/$uid"
    | "/settlements/$uid"
    | "/users/$uid"
    | "/catalog"
    | "/orders"
    | "/payments"
    | "/refunds"
    | "/risk"
    | "/settlements"
    | "/users"
    | "/inventory/warehouses/$uid"
    | "/inventory/stocks"
    | "/inventory/warehouses"
  id:
    | "__root__"
    | "/_authed"
    | "/unauthorized"
    | "/_authed/"
    | "/_authed/catalog/$uid"
    | "/_authed/catalog/new"
    | "/_authed/orders/$uid"
    | "/_authed/payments/$uid"
    | "/_authed/refunds/$uid"
    | "/_authed/settlements/$uid"
    | "/_authed/users/$uid"
    | "/_authed/catalog/"
    | "/_authed/orders/"
    | "/_authed/payments/"
    | "/_authed/refunds/"
    | "/_authed/risk/"
    | "/_authed/settlements/"
    | "/_authed/users/"
    | "/_authed/inventory/warehouses/$uid"
    | "/_authed/inventory/stocks/"
    | "/_authed/inventory/warehouses/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/unauthorized": {
      id: "/unauthorized"
      path: "/unauthorized"
      fullPath: "/unauthorized"
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authed": {
      id: "/_authed"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authed/": {
      id: "/_authed/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/users/": {
      id: "/_authed/users/"
      path: "/users"
      fullPath: "/users/"
      preLoaderRoute: typeof AuthedUsersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/settlements/": {
      id: "/_authed/settlements/"
      path: "/settlements"
      fullPath: "/settlements/"
      preLoaderRoute: typeof AuthedSettlementsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/risk/": {
      id: "/_authed/risk/"
      path: "/risk"
      fullPath: "/risk/"
      preLoaderRoute: typeof AuthedRiskIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/refunds/": {
      id: "/_authed/refunds/"
      path: "/refunds"
      fullPath: "/refunds/"
      preLoaderRoute: typeof AuthedRefundsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/payments/": {
      id: "/_authed/payments/"
      path: "/payments"
      fullPath: "/payments/"
      preLoaderRoute: typeof AuthedPaymentsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/orders/": {
      id: "/_authed/orders/"
      path: "/orders"
      fullPath: "/orders/"
      preLoaderRoute: typeof AuthedOrdersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/catalog/": {
      id: "/_authed/catalog/"
      path: "/catalog"
      fullPath: "/catalog/"
      preLoaderRoute: typeof AuthedCatalogIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/users/$uid": {
      id: "/_authed/users/$uid"
      path: "/users/$uid"
      fullPath: "/users/$uid"
      preLoaderRoute: typeof AuthedUsersUidRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/settlements/$uid": {
      id: "/_authed/settlements/$uid"
      path: "/settlements/$uid"
      fullPath: "/settlements/$uid"
      preLoaderRoute: typeof AuthedSettlementsUidRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/refunds/$uid": {
      id: "/_authed/refunds/$uid"
      path: "/refunds/$uid"
      fullPath: "/refunds/$uid"
      preLoaderRoute: typeof AuthedRefundsUidRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/payments/$uid": {
      id: "/_authed/payments/$uid"
      path: "/payments/$uid"
      fullPath: "/payments/$uid"
      preLoaderRoute: typeof AuthedPaymentsUidRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/orders/$uid": {
      id: "/_authed/orders/$uid"
      path: "/orders/$uid"
      fullPath: "/orders/$uid"
      preLoaderRoute: typeof AuthedOrdersUidRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/catalog/new": {
      id: "/_authed/catalog/new"
      path: "/catalog/new"
      fullPath: "/catalog/new"
      preLoaderRoute: typeof AuthedCatalogNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/catalog/$uid": {
      id: "/_authed/catalog/$uid"
      path: "/catalog/$uid"
      fullPath: "/catalog/$uid"
      preLoaderRoute: typeof AuthedCatalogUidRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/inventory/warehouses/": {
      id: "/_authed/inventory/warehouses/"
      path: "/inventory/warehouses"
      fullPath: "/inventory/warehouses/"
      preLoaderRoute: typeof AuthedInventoryWarehousesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/inventory/stocks/": {
      id: "/_authed/inventory/stocks/"
      path: "/inventory/stocks"
      fullPath: "/inventory/stocks/"
      preLoaderRoute: typeof AuthedInventoryStocksIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    "/_authed/inventory/warehouses/$uid": {
      id: "/_authed/inventory/warehouses/$uid"
      path: "/inventory/warehouses/$uid"
      fullPath: "/inventory/warehouses/$uid"
      preLoaderRoute: typeof AuthedInventoryWarehousesUidRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedCatalogUidRoute: typeof AuthedCatalogUidRoute
  AuthedCatalogNewRoute: typeof AuthedCatalogNewRoute
  AuthedOrdersUidRoute: typeof AuthedOrdersUidRoute
  AuthedPaymentsUidRoute: typeof AuthedPaymentsUidRoute
  AuthedRefundsUidRoute: typeof AuthedRefundsUidRoute
  AuthedSettlementsUidRoute: typeof AuthedSettlementsUidRoute
  AuthedUsersUidRoute: typeof AuthedUsersUidRoute
  AuthedCatalogIndexRoute: typeof AuthedCatalogIndexRoute
  AuthedOrdersIndexRoute: typeof AuthedOrdersIndexRoute
  AuthedPaymentsIndexRoute: typeof AuthedPaymentsIndexRoute
  AuthedRefundsIndexRoute: typeof AuthedRefundsIndexRoute
  AuthedRiskIndexRoute: typeof AuthedRiskIndexRoute
  AuthedSettlementsIndexRoute: typeof AuthedSettlementsIndexRoute
  AuthedUsersIndexRoute: typeof AuthedUsersIndexRoute
  AuthedInventoryWarehousesUidRoute: typeof AuthedInventoryWarehousesUidRoute
  AuthedInventoryStocksIndexRoute: typeof AuthedInventoryStocksIndexRoute
  AuthedInventoryWarehousesIndexRoute: typeof AuthedInventoryWarehousesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedCatalogUidRoute: AuthedCatalogUidRoute,
  AuthedCatalogNewRoute: AuthedCatalogNewRoute,
  AuthedOrdersUidRoute: AuthedOrdersUidRoute,
  AuthedPaymentsUidRoute: AuthedPaymentsUidRoute,
  AuthedRefundsUidRoute: AuthedRefundsUidRoute,
  AuthedSettlementsUidRoute: AuthedSettlementsUidRoute,
  AuthedUsersUidRoute: AuthedUsersUidRoute,
  AuthedCatalogIndexRoute: AuthedCatalogIndexRoute,
  AuthedOrdersIndexRoute: AuthedOrdersIndexRoute,
  AuthedPaymentsIndexRoute: AuthedPaymentsIndexRoute,
  AuthedRefundsIndexRoute: AuthedRefundsIndexRoute,
  AuthedRiskIndexRoute: AuthedRiskIndexRoute,
  AuthedSettlementsIndexRoute: AuthedSettlementsIndexRoute,
  AuthedUsersIndexRoute: AuthedUsersIndexRoute,
  AuthedInventoryWarehousesUidRoute: AuthedInventoryWarehousesUidRoute,
  AuthedInventoryStocksIndexRoute: AuthedInventoryStocksIndexRoute,
  AuthedInventoryWarehousesIndexRoute: AuthedInventoryWarehousesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
