// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: modules/stock/v1/stock.proto

package stockpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockFindAllProtoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        *int64                 `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3,oneof" json:"book_id,omitempty"`
	WarehouseId   *int64                 `protobuf:"varint,2,opt,name=warehouse_id,json=warehouseId,proto3,oneof" json:"warehouse_id,omitempty"`
	Filter        *QueryFilter           `protobuf:"bytes,3,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockFindAllProtoReq) Reset() {
	*x = StockFindAllProtoReq{}
	mi := &file_modules_stock_v1_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockFindAllProtoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockFindAllProtoReq) ProtoMessage() {}

func (x *StockFindAllProtoReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_stock_v1_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockFindAllProtoReq.ProtoReflect.Descriptor instead.
func (*StockFindAllProtoReq) Descriptor() ([]byte, []int) {
	return file_modules_stock_v1_stock_proto_rawDescGZIP(), []int{0}
}

func (x *StockFindAllProtoReq) GetBookId() int64 {
	if x != nil && x.BookId != nil {
		return *x.BookId
	}
	return 0
}

func (x *StockFindAllProtoReq) GetWarehouseId() int64 {
	if x != nil && x.WarehouseId != nil {
		return *x.WarehouseId
	}
	return 0
}

func (x *StockFindAllProtoReq) GetFilter() *QueryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type QueryFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sort          string                 `protobuf:"bytes,1,opt,name=sort,proto3" json:"sort,omitempty"`
	Order         string                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFilter) Reset() {
	*x = QueryFilter{}
	mi := &file_modules_stock_v1_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFilter) ProtoMessage() {}

func (x *QueryFilter) ProtoReflect() protoreflect.Message {
	mi := &file_modules_stock_v1_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFilter.ProtoReflect.Descriptor instead.
func (*QueryFilter) Descriptor() ([]byte, []int) {
	return file_modules_stock_v1_stock_proto_rawDescGZIP(), []int{1}
}

func (x *QueryFilter) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *QueryFilter) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *QueryFilter) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryFilter) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type StockFindAllProtoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Items         []*StockFindProtoResp  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockFindAllProtoResp) Reset() {
	*x = StockFindAllProtoResp{}
	mi := &file_modules_stock_v1_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockFindAllProtoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockFindAllProtoResp) ProtoMessage() {}

func (x *StockFindAllProtoResp) ProtoReflect() protoreflect.Message {
	mi := &file_modules_stock_v1_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockFindAllProtoResp.ProtoReflect.Descriptor instead.
func (*StockFindAllProtoResp) Descriptor() ([]byte, []int) {
	return file_modules_stock_v1_stock_proto_rawDescGZIP(), []int{2}
}

func (x *StockFindAllProtoResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *StockFindAllProtoResp) GetItems() []*StockFindProtoResp {
	if x != nil {
		return x.Items
	}
	return nil
}

type StockFindProtoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockFindProtoReq) Reset() {
	*x = StockFindProtoReq{}
	mi := &file_modules_stock_v1_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockFindProtoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockFindProtoReq) ProtoMessage() {}

func (x *StockFindProtoReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_stock_v1_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockFindProtoReq.ProtoReflect.Descriptor instead.
func (*StockFindProtoReq) Descriptor() ([]byte, []int) {
	return file_modules_stock_v1_stock_proto_rawDescGZIP(), []int{3}
}

func (x *StockFindProtoReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StockFindProtoResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId           int64                  `protobuf:"varint,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	WarehouseId      int64                  `protobuf:"varint,3,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Quantity         int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ReservedQuantity int64                  `protobuf:"varint,5,opt,name=reserved_quantity,json=reservedQuantity,proto3" json:"reserved_quantity,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StockFindProtoResp) Reset() {
	*x = StockFindProtoResp{}
	mi := &file_modules_stock_v1_stock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockFindProtoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockFindProtoResp) ProtoMessage() {}

func (x *StockFindProtoResp) ProtoReflect() protoreflect.Message {
	mi := &file_modules_stock_v1_stock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockFindProtoResp.ProtoReflect.Descriptor instead.
func (*StockFindProtoResp) Descriptor() ([]byte, []int) {
	return file_modules_stock_v1_stock_proto_rawDescGZIP(), []int{4}
}

func (x *StockFindProtoResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StockFindProtoResp) GetBookId() int64 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *StockFindProtoResp) GetWarehouseId() int64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *StockFindProtoResp) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StockFindProtoResp) GetReservedQuantity() int64 {
	if x != nil {
		return x.ReservedQuantity
	}
	return 0
}

var File_modules_stock_v1_stock_proto protoreflect.FileDescriptor

const file_modules_stock_v1_stock_proto_rawDesc = "" +
	"\n" +
	"\x1cmodules/stock/v1/stock.proto\x12\bstock.v1\"\xb8\x01\n" +
	"\x14StockFindAllProtoReq\x12\x1c\n" +
	"\abook_id\x18\x01 \x01(\x03H\x00R\x06bookId\x88\x01\x01\x12&\n" +
	"\fwarehouse_id\x18\x02 \x01(\x03H\x01R\vwarehouseId\x88\x01\x01\x122\n" +
	"\x06filter\x18\x03 \x01(\v2\x15.stock.v1.QueryFilterH\x02R\x06filter\x88\x01\x01B\n" +
	"\n" +
	"\b_book_idB\x0f\n" +
	"\r_warehouse_idB\t\n" +
	"\a_filter\"e\n" +
	"\vQueryFilter\x12\x12\n" +
	"\x04sort\x18\x01 \x01(\tR\x04sort\x12\x14\n" +
	"\x05order\x18\x02 \x01(\tR\x05order\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"a\n" +
	"\x15StockFindAllProtoResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x122\n" +
	"\x05items\x18\x02 \x03(\v2\x1c.stock.v1.StockFindProtoRespR\x05items\"#\n" +
	"\x11StockFindProtoReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xa9\x01\n" +
	"\x12StockFindProtoResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\x03R\x06bookId\x12!\n" +
	"\fwarehouse_id\x18\x03 \x01(\x03R\vwarehouseId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12+\n" +
	"\x11reserved_quantity\x18\x05 \x01(\x03R\x10reservedQuantity2\xac\x01\n" +
	"\fStockService\x12R\n" +
	"\rFindAllStocks\x12\x1e.stock.v1.StockFindAllProtoReq\x1a\x1f.stock.v1.StockFindAllProtoResp\"\x00\x12H\n" +
	"\tFindStock\x12\x1b.stock.v1.StockFindProtoReq\x1a\x1c.stock.v1.StockFindProtoResp\"\x00Bg\n" +
	"\fcom.stock.v1B\n" +
	"StockProtoP\x01Z\n" +
	"pb/stockpb\xa2\x02\x03SXX\xaa\x02\bStock.V1\xca\x02\bStock\\V1\xe2\x02\x14Stock\\V1\\GPBMetadata\xea\x02\tStock::V1b\x06proto3"

var (
	file_modules_stock_v1_stock_proto_rawDescOnce sync.Once
	file_modules_stock_v1_stock_proto_rawDescData []byte
)

func file_modules_stock_v1_stock_proto_rawDescGZIP() []byte {
	file_modules_stock_v1_stock_proto_rawDescOnce.Do(func() {
		file_modules_stock_v1_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_stock_v1_stock_proto_rawDesc), len(file_modules_stock_v1_stock_proto_rawDesc)))
	})
	return file_modules_stock_v1_stock_proto_rawDescData
}

var file_modules_stock_v1_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_modules_stock_v1_stock_proto_goTypes = []any{
	(*StockFindAllProtoReq)(nil),  // 0: stock.v1.StockFindAllProtoReq
	(*QueryFilter)(nil),           // 1: stock.v1.QueryFilter
	(*StockFindAllProtoResp)(nil), // 2: stock.v1.StockFindAllProtoResp
	(*StockFindProtoReq)(nil),     // 3: stock.v1.StockFindProtoReq
	(*StockFindProtoResp)(nil),    // 4: stock.v1.StockFindProtoResp
}
var file_modules_stock_v1_stock_proto_depIdxs = []int32{
	1, // 0: stock.v1.StockFindAllProtoReq.filter:type_name -> stock.v1.QueryFilter
	4, // 1: stock.v1.StockFindAllProtoResp.items:type_name -> stock.v1.StockFindProtoResp
	0, // 2: stock.v1.StockService.FindAllStocks:input_type -> stock.v1.StockFindAllProtoReq
	3, // 3: stock.v1.StockService.FindStock:input_type -> stock.v1.StockFindProtoReq
	2, // 4: stock.v1.StockService.FindAllStocks:output_type -> stock.v1.StockFindAllProtoResp
	4, // 5: stock.v1.StockService.FindStock:output_type -> stock.v1.StockFindProtoResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_modules_stock_v1_stock_proto_init() }
func file_modules_stock_v1_stock_proto_init() {
	if File_modules_stock_v1_stock_proto != nil {
		return
	}
	file_modules_stock_v1_stock_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_stock_v1_stock_proto_rawDesc), len(file_modules_stock_v1_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_stock_v1_stock_proto_goTypes,
		DependencyIndexes: file_modules_stock_v1_stock_proto_depIdxs,
		MessageInfos:      file_modules_stock_v1_stock_proto_msgTypes,
	}.Build()
	File_modules_stock_v1_stock_proto = out.File
	file_modules_stock_v1_stock_proto_goTypes = nil
	file_modules_stock_v1_stock_proto_depIdxs = nil
}
