// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface CartUpdateItemRequest {
  quantity: number;
}

export const CartUpdateItemRequestSchema = z.object({
  quantity: z.number().int(),
});
