// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { CartItemFindResponse } from './cart-item-find-response';
import { CartItemFindResponseSchema } from './cart-item-find-response';

export interface CartFindResponse {
  items: Array<CartItemFindResponse>;
  total_amount: number;
  total_items: number;
  uid: string;
  user_uid: string;
}

export const CartFindResponseSchema = z.object({
  items: z.array(CartItemFindResponseSchema),
  total_amount: z.number(),
  total_items: z.number().int(),
  uid: z.string(),
  user_uid: z.string(),
});
