// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { OrderShippingCreateRequest } from './order-shipping-create-request';
import { OrderShippingCreateRequestSchema } from './order-shipping-create-request';

export interface CartCheckoutRequest {
  currency: string;
  idempotency_key: string;
  shipping?: OrderShippingCreateRequest;
}

export const CartCheckoutRequestSchema = z.object({
  currency: z.string(),
  idempotency_key: z.string(),
  shipping: OrderShippingCreateRequestSchema.optional(),
});
