// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface OrderItemUpdateRequest {
  currency?: string;
  options?: string;
  price?: number;
  product_id?: string;
  product_name?: string;
  quantity?: number;
  sku?: string;
  tax_rate?: number;
}

export const OrderItemUpdateRequestSchema = z.object({
  currency: z.string().optional(),
  options: z.string().optional(),
  price: z.number().optional(),
  product_id: z.string().regex(/^-?\d+$/).optional(),
  product_name: z.string().optional(),
  quantity: z.number().int().optional(),
  sku: z.string().optional(),
  tax_rate: z.number().optional(),
});
