// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import { OrderAdjustmentType, OrderAdjustmentTypeSchema } from '../constant/order-adjustment-type';

export interface OrderAdjustmentFindResponse {
  amount: number;
  created_at: Date;
  label?: string;
  meta?: Record<string, unknown>;
  type: OrderAdjustmentType;
  uid: string;
  updated_at?: Date;
}

export const OrderAdjustmentFindResponseSchema = z.object({
  amount: z.number(),
  created_at: z.date(),
  label: z.string().optional(),
  meta: z.record(z.string(), z.unknown()).optional(),
  type: OrderAdjustmentTypeSchema,
  uid: z.string(),
  updated_at: z.date().optional(),
});
