// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { OrderAdjustmentFindResponse } from './order-adjustment-find-response';
import { OrderAdjustmentFindResponseSchema } from './order-adjustment-find-response';

export interface OrderAdjustmentFindAllResponse {
  items: Array<OrderAdjustmentFindResponse>;
  total: string;
}

export const OrderAdjustmentFindAllResponseSchema = z.object({
  items: z.array(OrderAdjustmentFindResponseSchema),
  total: z.string().regex(/^-?\d+$/),
});
