// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { OrderItemFindResponse } from './order-item-find-response';
import { OrderItemFindResponseSchema } from './order-item-find-response';

export interface OrderItemFindAllResponse {
  items: Array<OrderItemFindResponse>;
  total: string;
}

export const OrderItemFindAllResponseSchema = z.object({
  items: z.array(OrderItemFindResponseSchema),
  total: z.string().regex(/^-?\d+$/),
});
