// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface OrderShippingUpdateRequest {
  address_line1?: string;
  address_line2?: string;
  city?: string;
  country?: string;
  postal_code?: string;
  recipient_name?: string;
  recipient_phone?: string;
  shipping_method?: string;
  state?: string;
}

export const OrderShippingUpdateRequestSchema = z.object({
  address_line1: z.string().optional(),
  address_line2: z.string().optional(),
  city: z.string().optional(),
  country: z.string().optional(),
  postal_code: z.string().optional(),
  recipient_name: z.string().optional(),
  recipient_phone: z.string().optional(),
  shipping_method: z.string().optional(),
  state: z.string().optional(),
});
