// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { OrderItemCreateRequest } from './order-item-create-request';
import { OrderItemCreateRequestSchema } from './order-item-create-request';
import type { OrderShippingCreateRequest } from './order-shipping-create-request';
import { OrderShippingCreateRequestSchema } from './order-shipping-create-request';

export interface PlaceOrderRequest {
  currency: string;
  discount_amount?: number;
  idempotency_key: string;
  items: Array<OrderItemCreateRequest>;
  items_amount: number;
  shipping?: OrderShippingCreateRequest;
  shipping_amount?: number;
  tax_amount?: number;
  total_amount: number;
  user_uid: string;
}

export const PlaceOrderRequestSchema = z.object({
  currency: z.string(),
  discount_amount: z.number().optional(),
  idempotency_key: z.string(),
  items: z.array(OrderItemCreateRequestSchema),
  items_amount: z.number(),
  shipping: OrderShippingCreateRequestSchema.optional(),
  shipping_amount: z.number().optional(),
  tax_amount: z.number().optional(),
  total_amount: z.number(),
  user_uid: z.string(),
});
