// Code generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0); DO NOT EDIT.
//
// Inventory service API
//
// Inventory service API of Bookstore microservices
//
// API version: 0.1.0
// Contact: admin@example.com

package openapi

import (
	"github.com/gin-gonic/gin"
)

type WarehouseAPI interface {


    // ApiV1WarehousesGet Get /api/v1/warehouses
    // Find all warehouses 
     ApiV1WarehousesGet(c *gin.Context)

    // ApiV1WarehousesIdDelete Delete /api/v1/warehouses/:id
    // Delete warehouse 
     ApiV1WarehousesIdDelete(c *gin.Context)

    // ApiV1WarehousesIdGet Get /api/v1/warehouses/:id
    // Find warehouse 
     ApiV1WarehousesIdGet(c *gin.Context)

    // ApiV1WarehousesIdPut Put /api/v1/warehouses/:id
    // Update warehouse 
     ApiV1WarehousesIdPut(c *gin.Context)

    // ApiV1WarehousesPost Post /api/v1/warehouses
    // Add new warehouse 
     ApiV1WarehousesPost(c *gin.Context)

}