[general]
gen_lang = "kotlin"
gen_type = "client"
input_spec = "../order/api/openapi/schema/openapi.1.0.0.json"
output_dir = "src/main/generated"

[packages]
api_package = "com.codejsha.bookstore.generated.application.port.restclient.order.api"
model_package = "com.codejsha.bookstore.generated.application.port.restclient.order.model"
constant_package = "com.codejsha.bookstore.generated.application.port.restclient.order.model"

[options]
validation_enabled = true
kotlin_pagination_enabled = false
kotlin_security_enabled = false
