mode: standalone
auth:
  useCredentialsFiles: true
  useSecret: false

podAnnotations:
  traffic.sidecar.istio.io/excludeOutboundPorts: "8200"
  sidecar.istio.io/proxyCPU: "10m"
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/agent-inject-status: "update"
  vault.hashicorp.com/agent-init-first: "true"
  vault.hashicorp.com/preserve-secret-case: "true"
  vault.hashicorp.com/service: "http://vault.vault.svc.cluster.local:8200"
  vault.hashicorp.com/role: "minio-role"
  vault.hashicorp.com/agent-inject-secret-admin-username: "kv/data/minio/admin"
  vault.hashicorp.com/secret-volume-path-admin-username: "/opt/bitnami/minio/secrets"
  vault.hashicorp.com/agent-inject-file-admin-username: "root-user"
  vault.hashicorp.com/agent-inject-template-admin-username: |
    {{`{{- with secret "kv/data/minio/admin" -}}`}}
    {{`{{ .Data.data.username }}`}}
    {{`{{- end -}}`}}
  vault.hashicorp.com/agent-inject-secret-admin-password: "kv/data/minio/admin"
  vault.hashicorp.com/secret-volume-path-admin-password: "/opt/bitnami/minio/secrets"
  vault.hashicorp.com/agent-inject-file-admin-password: "root-password"
  vault.hashicorp.com/agent-inject-template-admin-password: |
    {{`{{- with secret "kv/data/minio/admin" -}}`}}
    {{`{{ .Data.data.password }}`}}
    {{`{{- end -}}`}}

serviceAccount:
  create: true
  name: "minio-sa"
  automountServiceAccountToken: true
automountServiceAccountToken: true

resources:
  requests:
    cpu: 10m
    memory: 1024Mi
    ephemeral-storage: 50Mi
  limits:
    cpu: 750m
    memory: 1536Mi
    ephemeral-storage: 2Gi

networkPolicy:
  enabled: false

persistence:
  enabled: true
  size: 1000Gi
