// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { OrderFindResponse } from './order-find-response';
import { OrderFindResponseSchema } from './order-find-response';

export interface OrderFindAllResponse {
  items: Array<OrderFindResponse>;
  total: string;
}

export const OrderFindAllResponseSchema = z.object({
  items: z.array(OrderFindResponseSchema),
  total: z.string().regex(/^-?\d+$/),
});
