// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { OrderItem } from './order-item';
import { OrderItemSchema } from './order-item';
import { OrderStatus, OrderStatusSchema } from '../constant/order-status';

export interface OrderFindResponse {
  order_items?: Array<OrderItem>;
  status?: OrderStatus;
  total_price?: number;
  uid: string;
  user_uid?: string;
}

export const OrderFindResponseSchema = z.object({
  order_items: z.array(OrderItemSchema).optional(),
  status: OrderStatusSchema.optional(),
  total_price: z.number().optional(),
  uid: z.string(),
  user_uid: z.string().optional(),
});
