// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { PaymentFindResponse } from './payment-find-response';
import { PaymentFindResponseSchema } from './payment-find-response';

export interface PaymentFindAllResponse {
  items: Array<PaymentFindResponse>;
  total: string;
}

export const PaymentFindAllResponseSchema = z.object({
  items: z.array(PaymentFindResponseSchema),
  total: z.string().regex(/^-?\d+$/),
});
