// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface PaymentFindResponse {
  amount?: number;
  category_type?: string;
  currency?: string;
  order_uid?: string;
  payment_date?: Date;
  reason?: string;
  status?: string;
  uid: string;
  user_uid?: string;
}

export const PaymentFindResponseSchema = z.object({
  amount: z.number().optional(),
  category_type: z.string().optional(),
  currency: z.string().optional(),
  order_uid: z.string().optional(),
  payment_date: z.date().optional(),
  reason: z.string().optional(),
  status: z.string().optional(),
  uid: z.string(),
  user_uid: z.string().optional(),
});
