// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import { PointChangeType, PointChangeTypeSchema } from '../constant/point-change-type';

export interface PointHistoryFindResponse {
  amount: number;
  change_type: PointChangeType;
  created_at: Date;
  reason?: string;
  uid: string;
}

export const PointHistoryFindResponseSchema = z.object({
  amount: z.number().int(),
  change_type: PointChangeTypeSchema,
  created_at: z.date(),
  reason: z.string().optional(),
  uid: z.string(),
});
