// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { PointHistoryFindResponse } from './point-history-find-response';
import { PointHistoryFindResponseSchema } from './point-history-find-response';

export interface PointHistoryFindAllResponse {
  items: Array<PointHistoryFindResponse>;
  total: string;
}

export const PointHistoryFindAllResponseSchema = z.object({
  items: z.array(PointHistoryFindResponseSchema),
  total: z.string().regex(/^-?\d+$/),
});
