// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

/**
 * Spend points for a customer
 */

export interface PointSpendRequest {
  amount: number;
  reason?: string;
}

export const PointSpendRequestSchema = z.object({
  amount: z.number().int(),
  reason: z.string().optional(),
});
