// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface PointBalanceResponse {
  balance: number;
  user_uid: string;
}

export const PointBalanceResponseSchema = z.object({
  balance: z.number().int(),
  user_uid: z.string(),
});
