// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface ReviewCreateRequest {
  book_uid: string;
  content?: string;
  rating: number;
  title?: string;
}

export const ReviewCreateRequestSchema = z.object({
  book_uid: z.string(),
  content: z.string().optional(),
  rating: z.number().int(),
  title: z.string().optional(),
});
