// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

/**
 * Remove books from wishlist
 */

export interface WishlistRemoveRequest {
  book_uids: Array<string>;
}

export const WishlistRemoveRequestSchema = z.object({
  book_uids: z.array(z.string()),
});
