// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

/**
 * Add books to wishlist
 */

export interface WishlistAddRequest {
  book_uids: Array<string>;
}

export const WishlistAddRequestSchema = z.object({
  book_uids: z.array(z.string()),
});
