variable "namespace" {
  description = "Namespace name"
  type        = string
}

variable "mysql_services" {
  description = "MySQL services"
  type        = list(string)
}

variable "mysql_service_accounts" {
  description = "MySQL service accounts"
  type        = list(string)
}

variable "mysql_root_password" {
  description = "MySQL root password (generated by random_password in parent module)"
  type        = string
  sensitive   = true
}

variable "mysql_credentials" {
  description = "Per-service credentials list: [{service, username, password}]. Generated by random_password in parent module."
  type = list(object({
    service  = string
    username = string
    password = string
  }))
  sensitive = true
}
