image:
  pullPolicy: Always

env:
  - name: APP_CONFIG_PROFILE
    value: dev
  - name: APP_CONFIG_SERVER
    value: "configserver:http://config-server.cloud-config.svc.cluster.local:8888"

mesh:
  waypoint: "bookstore-waypoint"

gatewayApi:
  enabled: true
  host: "notification-api.example.com"
