generatorName: go
globalProperties:
  apis: ""
additionalProperties:
  packageName: idp
  generateInterfaces: true
inputSpec: api/idp/oidc-openapi-bundle.json
outputDir: internal/application/port/idp
ignoreFileOverride: ../../api/idp/config-params.openapi-generator-ignore
templateDir: ../../api/idp/templates
files:
  params.mustache:
    templateType: API
    destinationFilename: _params.go
  request.mustache:
    templateType: API
    destinationFilename: _requests.go
