// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: modules/publisher/v1/publisher.proto

package publisherpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublisherFindAllProtoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Filter        *QueryFilter           `protobuf:"bytes,2,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublisherFindAllProtoReq) Reset() {
	*x = PublisherFindAllProtoReq{}
	mi := &file_modules_publisher_v1_publisher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublisherFindAllProtoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherFindAllProtoReq) ProtoMessage() {}

func (x *PublisherFindAllProtoReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_publisher_v1_publisher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherFindAllProtoReq.ProtoReflect.Descriptor instead.
func (*PublisherFindAllProtoReq) Descriptor() ([]byte, []int) {
	return file_modules_publisher_v1_publisher_proto_rawDescGZIP(), []int{0}
}

func (x *PublisherFindAllProtoReq) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PublisherFindAllProtoReq) GetFilter() *QueryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type QueryFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sort          string                 `protobuf:"bytes,1,opt,name=sort,proto3" json:"sort,omitempty"`
	Order         string                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFilter) Reset() {
	*x = QueryFilter{}
	mi := &file_modules_publisher_v1_publisher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFilter) ProtoMessage() {}

func (x *QueryFilter) ProtoReflect() protoreflect.Message {
	mi := &file_modules_publisher_v1_publisher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFilter.ProtoReflect.Descriptor instead.
func (*QueryFilter) Descriptor() ([]byte, []int) {
	return file_modules_publisher_v1_publisher_proto_rawDescGZIP(), []int{1}
}

func (x *QueryFilter) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *QueryFilter) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *QueryFilter) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryFilter) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type PublisherFindAllProtoResp struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Total         int64                     `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Items         []*PublisherFindProtoResp `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublisherFindAllProtoResp) Reset() {
	*x = PublisherFindAllProtoResp{}
	mi := &file_modules_publisher_v1_publisher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublisherFindAllProtoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherFindAllProtoResp) ProtoMessage() {}

func (x *PublisherFindAllProtoResp) ProtoReflect() protoreflect.Message {
	mi := &file_modules_publisher_v1_publisher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherFindAllProtoResp.ProtoReflect.Descriptor instead.
func (*PublisherFindAllProtoResp) Descriptor() ([]byte, []int) {
	return file_modules_publisher_v1_publisher_proto_rawDescGZIP(), []int{2}
}

func (x *PublisherFindAllProtoResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PublisherFindAllProtoResp) GetItems() []*PublisherFindProtoResp {
	if x != nil {
		return x.Items
	}
	return nil
}

type PublisherFindProtoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublisherFindProtoReq) Reset() {
	*x = PublisherFindProtoReq{}
	mi := &file_modules_publisher_v1_publisher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublisherFindProtoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherFindProtoReq) ProtoMessage() {}

func (x *PublisherFindProtoReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_publisher_v1_publisher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherFindProtoReq.ProtoReflect.Descriptor instead.
func (*PublisherFindProtoReq) Descriptor() ([]byte, []int) {
	return file_modules_publisher_v1_publisher_proto_rawDescGZIP(), []int{3}
}

func (x *PublisherFindProtoReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PublisherFindProtoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       *string                `protobuf:"bytes,3,opt,name=address,proto3,oneof" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublisherFindProtoResp) Reset() {
	*x = PublisherFindProtoResp{}
	mi := &file_modules_publisher_v1_publisher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublisherFindProtoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherFindProtoResp) ProtoMessage() {}

func (x *PublisherFindProtoResp) ProtoReflect() protoreflect.Message {
	mi := &file_modules_publisher_v1_publisher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherFindProtoResp.ProtoReflect.Descriptor instead.
func (*PublisherFindProtoResp) Descriptor() ([]byte, []int) {
	return file_modules_publisher_v1_publisher_proto_rawDescGZIP(), []int{4}
}

func (x *PublisherFindProtoResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublisherFindProtoResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PublisherFindProtoResp) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

var File_modules_publisher_v1_publisher_proto protoreflect.FileDescriptor

const file_modules_publisher_v1_publisher_proto_rawDesc = "" +
	"\n" +
	"$modules/publisher/v1/publisher.proto\x12\fpublisher.v1\"\x7f\n" +
	"\x18PublisherFindAllProtoReq\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x126\n" +
	"\x06filter\x18\x02 \x01(\v2\x19.publisher.v1.QueryFilterH\x01R\x06filter\x88\x01\x01B\a\n" +
	"\x05_nameB\t\n" +
	"\a_filter\"e\n" +
	"\vQueryFilter\x12\x12\n" +
	"\x04sort\x18\x01 \x01(\tR\x04sort\x12\x14\n" +
	"\x05order\x18\x02 \x01(\tR\x05order\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"m\n" +
	"\x19PublisherFindAllProtoResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12:\n" +
	"\x05items\x18\x02 \x03(\v2$.publisher.v1.PublisherFindProtoRespR\x05items\"'\n" +
	"\x15PublisherFindProtoReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"g\n" +
	"\x16PublisherFindProtoResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\aaddress\x18\x03 \x01(\tH\x00R\aaddress\x88\x01\x01B\n" +
	"\n" +
	"\b_address2\xd8\x01\n" +
	"\x10PublisherService\x12f\n" +
	"\x11FindAllPublishers\x12&.publisher.v1.PublisherFindAllProtoReq\x1a'.publisher.v1.PublisherFindAllProtoResp\"\x00\x12\\\n" +
	"\rFindPublisher\x12#.publisher.v1.PublisherFindProtoReq\x1a$.publisher.v1.PublisherFindProtoResp\"\x00B\xb1\x01\n" +
	">com.codejsha.bookstore.service.application.port.pb.publisherpbB\x0ePublisherProtoP\x01Z\x0epb/publisherpb\xa2\x02\x03PXX\xaa\x02\fPublisher.V1\xca\x02\fPublisher\\V1\xe2\x02\x18Publisher\\V1\\GPBMetadata\xea\x02\rPublisher::V1b\x06proto3"

var (
	file_modules_publisher_v1_publisher_proto_rawDescOnce sync.Once
	file_modules_publisher_v1_publisher_proto_rawDescData []byte
)

func file_modules_publisher_v1_publisher_proto_rawDescGZIP() []byte {
	file_modules_publisher_v1_publisher_proto_rawDescOnce.Do(func() {
		file_modules_publisher_v1_publisher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_publisher_v1_publisher_proto_rawDesc), len(file_modules_publisher_v1_publisher_proto_rawDesc)))
	})
	return file_modules_publisher_v1_publisher_proto_rawDescData
}

var file_modules_publisher_v1_publisher_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_modules_publisher_v1_publisher_proto_goTypes = []any{
	(*PublisherFindAllProtoReq)(nil),  // 0: publisher.v1.PublisherFindAllProtoReq
	(*QueryFilter)(nil),               // 1: publisher.v1.QueryFilter
	(*PublisherFindAllProtoResp)(nil), // 2: publisher.v1.PublisherFindAllProtoResp
	(*PublisherFindProtoReq)(nil),     // 3: publisher.v1.PublisherFindProtoReq
	(*PublisherFindProtoResp)(nil),    // 4: publisher.v1.PublisherFindProtoResp
}
var file_modules_publisher_v1_publisher_proto_depIdxs = []int32{
	1, // 0: publisher.v1.PublisherFindAllProtoReq.filter:type_name -> publisher.v1.QueryFilter
	4, // 1: publisher.v1.PublisherFindAllProtoResp.items:type_name -> publisher.v1.PublisherFindProtoResp
	0, // 2: publisher.v1.PublisherService.FindAllPublishers:input_type -> publisher.v1.PublisherFindAllProtoReq
	3, // 3: publisher.v1.PublisherService.FindPublisher:input_type -> publisher.v1.PublisherFindProtoReq
	2, // 4: publisher.v1.PublisherService.FindAllPublishers:output_type -> publisher.v1.PublisherFindAllProtoResp
	4, // 5: publisher.v1.PublisherService.FindPublisher:output_type -> publisher.v1.PublisherFindProtoResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_modules_publisher_v1_publisher_proto_init() }
func file_modules_publisher_v1_publisher_proto_init() {
	if File_modules_publisher_v1_publisher_proto != nil {
		return
	}
	file_modules_publisher_v1_publisher_proto_msgTypes[0].OneofWrappers = []any{}
	file_modules_publisher_v1_publisher_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_publisher_v1_publisher_proto_rawDesc), len(file_modules_publisher_v1_publisher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_publisher_v1_publisher_proto_goTypes,
		DependencyIndexes: file_modules_publisher_v1_publisher_proto_depIdxs,
		MessageInfos:      file_modules_publisher_v1_publisher_proto_msgTypes,
	}.Build()
	File_modules_publisher_v1_publisher_proto = out.File
	file_modules_publisher_v1_publisher_proto_goTypes = nil
	file_modules_publisher_v1_publisher_proto_depIdxs = nil
}
