// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import { AuthRole, AuthRoleSchema } from '../constant/auth-role';
import { UserStatus, UserStatusSchema } from '../constant/user-status';

export interface UserFindResponse {
  created_at: Date;
  email: string;
  first_name: string;
  last_login_at?: Date;
  last_name: string;
  phone?: string;
  roles: Array<AuthRole>;
  status: UserStatus;
  uid: string;
  updated_at?: Date;
}

export const UserFindResponseSchema = z.object({
  created_at: z.date(),
  email: z.string().email(),
  first_name: z.string(),
  last_login_at: z.date().optional(),
  last_name: z.string(),
  phone: z.string().optional(),
  roles: z.array(AuthRoleSchema),
  status: UserStatusSchema,
  uid: z.string(),
  updated_at: z.date().optional(),
});
