// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { UserFindResponse } from './user-find-response';
import { UserFindResponseSchema } from './user-find-response';

export interface UserFindAllResponse {
  items: Array<UserFindResponse>;
  total: string;
}

export const UserFindAllResponseSchema = z.object({
  items: z.array(UserFindResponseSchema),
  total: z.string().regex(/^-?\d+$/),
});
