apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: uv-triggertemplate
  namespace: "${namespace}"
spec:
  params:
    - name: service-name
    - name: git-repo-url
    - name: git-repo-name
    - name: git-ref
    - name: git-revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: pipelinerun-uv-ci-
        labels:
          bookstore.dev/service: $(tt.params.service-name)
      spec:
        pipelineRef:
          resolver: git
          params:
            - name: repo
              value: tektoncd-custom-catalog
            - name: revision
              value: main
            - name: pathInRepo
              value: task/uv-ci-pipeline/0.1/uv-ci-pipeline.yaml
        taskRunTemplate:
          podTemplate:
            imagePullSecrets:
              - name: harbor-pull
        taskRunSpecs:
          - pipelineTaskName: clone-source-repo
            serviceAccountName: git-source-sa
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                storageClassName: local-path
                resources:
                  requests:
                    storage: 5Gi
          - name: dockerconfig
            secret:
              secretName: dockerconfig-secret
          - name: git-source-ssh-auth
            secret:
              secretName: $(tt.params.service-name)-repo-ssh-auth
        params:
          - name: service-name
            value: $(tt.params.service-name)
          - name: git-source-revision
            value: $(tt.params.git-revision)
