// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

/**
 * A single ordered line, priced as it was when the order was placed
 */

export interface AdminOrderLineItem {
  currency: string;
  options?: string;
  price: number;
  product_id: string;
  product_name?: string;
  quantity: number;
  sku?: string;
  subtotal: number;
  tax_rate: number;
  uid: string;
}

export const AdminOrderLineItemSchema = z.object({
  currency: z.string(),
  options: z.string().optional(),
  price: z.number(),
  product_id: z.string().regex(/^-?\d+$/),
  product_name: z.string().optional(),
  quantity: z.number().int(),
  sku: z.string().optional(),
  subtotal: z.number(),
  tax_rate: z.number(),
  uid: z.string(),
});
