// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

/**
 * The authenticated administrator, as projected by the mesh from the JWT
 */

export interface AdminIdentityResponse {
  email?: string;
  name?: string;
  /** Realm roles carried by the token */
  roles: Array<string>;
  uid: string;
}

export const AdminIdentityResponseSchema = z.object({
  email: z.string().email().optional(),
  name: z.string().optional(),
  roles: z.array(z.string()),
  uid: z.string(),
});
