// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

/**
 * The shipping destination recorded on the order
 */

export interface AdminOrderShipping {
  address_line1: string;
  address_line2?: string;
  city: string;
  country: string;
  postal_code: string;
  recipient_name: string;
  recipient_phone: string;
  shipping_method: string;
  state: string;
}

export const AdminOrderShippingSchema = z.object({
  address_line1: z.string(),
  address_line2: z.string().optional(),
  city: z.string(),
  country: z.string(),
  postal_code: z.string(),
  recipient_name: z.string(),
  recipient_phone: z.string(),
  shipping_method: z.string(),
  state: z.string(),
});
