// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { AdminWorkResponse } from './admin-work-response';
import { AdminWorkResponseSchema } from './admin-work-response';

export interface AdminWorkFindAllResponse {
  items: Array<AdminWorkResponse>;
  total: string;
}

export const AdminWorkFindAllResponseSchema = z.object({
  items: z.array(AdminWorkResponseSchema),
  total: z.string().regex(/^-?\d+$/),
});
