// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { AdminOrderLineItem } from './admin-order-line-item';
import { AdminOrderLineItemSchema } from './admin-order-line-item';
import type { AdminOrderShipping } from './admin-order-shipping';
import { AdminOrderShippingSchema } from './admin-order-shipping';

/**
 * A single order with its lines and shipping destination
 */

export interface AdminOrderResponse {
  created_at: Date;
  currency: string;
  discount_amount: number;
  items?: Array<AdminOrderLineItem>;
  items_amount: number;
  order_number: string;
  shipping?: AdminOrderShipping;
  shipping_amount: number;
  status: string;
  tax_amount: number;
  total_amount: number;
  uid: string;
  updated_at?: Date;
  user_uid: string;
}

export const AdminOrderResponseSchema = z.object({
  created_at: z.date(),
  currency: z.string(),
  discount_amount: z.number(),
  items: z.array(AdminOrderLineItemSchema).optional(),
  items_amount: z.number(),
  order_number: z.string(),
  shipping: AdminOrderShippingSchema.optional(),
  shipping_amount: z.number(),
  status: z.string(),
  tax_amount: z.number(),
  total_amount: z.number(),
  uid: z.string(),
  updated_at: z.date().optional(),
  user_uid: z.string(),
});
