// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { AdminRefundResponse } from './admin-refund-response';
import { AdminRefundResponseSchema } from './admin-refund-response';

export interface AdminRefundFindAllResponse {
  items: Array<AdminRefundResponse>;
  total: string;
}

export const AdminRefundFindAllResponseSchema = z.object({
  items: z.array(AdminRefundResponseSchema),
  total: z.string().regex(/^-?\d+$/),
});
