// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

/**
 * Replaces the user's roles wholesale — a role left out of the list is revoked.
 */

export interface AdminUserRolesRequest {
  /** Realm role names. An unknown name is rejected rather than silently dropped. */
  roles: Array<string>;
}

export const AdminUserRolesRequestSchema = z.object({
  roles: z.array(z.string()),
});
