// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import { AdminRiskLevel, AdminRiskLevelSchema } from '../constant/admin-risk-level';

export interface AdminRiskFlagRequest {
  level: AdminRiskLevel;
  reason: string;
  /** Time-to-live in seconds; defaults to 86400 (24h), capped at 30 days */
  ttl_seconds?: string;
}

export const AdminRiskFlagRequestSchema = z.object({
  level: AdminRiskLevelSchema,
  reason: z.string(),
  ttl_seconds: z.string().regex(/^-?\d+$/).optional(),
});
