// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { AdminAuthorItem } from './admin-author-item';
import { AdminAuthorItemSchema } from './admin-author-item';
import type { AdminSubjectItem } from './admin-subject-item';
import { AdminSubjectItemSchema } from './admin-subject-item';

export interface AdminWorkResponse {
  authors: Array<AdminAuthorItem>;
  created_at: Date;
  description?: string;
  /** Free-form year or date as recorded by the catalog, not a validated date */
  first_publish_date?: string;
  /** Open Library key, when the work was imported from there */
  ol_key?: string;
  subjects: Array<AdminSubjectItem>;
  title: string;
  uid: string;
  updated_at?: Date;
}

export const AdminWorkResponseSchema = z.object({
  authors: z.array(AdminAuthorItemSchema),
  created_at: z.date(),
  description: z.string().optional(),
  first_publish_date: z.string().optional(),
  ol_key: z.string().optional(),
  subjects: z.array(AdminSubjectItemSchema),
  title: z.string(),
  uid: z.string(),
  updated_at: z.date().optional(),
});
