// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

/**
 * A single payment or refund line contributing to a settlement bucket.
 */

export interface AdminSettlementDetailItem {
  /** Signed amount in the smallest currency unit; refunds are negative. */
  amount: string;
  currency: string;
  occurred_at: Date;
  payment_id: string;
  payment_method?: string;
  source_id: string;
  /** PAYMENT or REFUND */
  source_type: string;
  uid: string;
}

export const AdminSettlementDetailItemSchema = z.object({
  amount: z.string().regex(/^-?\d+$/),
  currency: z.string(),
  occurred_at: z.date(),
  payment_id: z.string(),
  payment_method: z.string().optional(),
  source_id: z.string(),
  source_type: z.string(),
  uid: z.string(),
});
