// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

/**
 * Acknowledged manual settlement run; the batch job executes asynchronously.
 */

export interface AdminSettlementRunResponse {
  started_at: Date;
  status: string;
  target_date: Date;
  uid: string;
}

export const AdminSettlementRunResponseSchema = z.object({
  started_at: z.date(),
  status: z.string(),
  target_date: z.date(),
  uid: z.string(),
});
