// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

/**
 * A reconciled daily sales-close bucket, keyed by (date, currency, payment method).
 */

export interface AdminSettlementItem {
  created_at: Date;
  currency: string;
  fee_amount: string;
  gross_amount: string;
  net_amount: string;
  payment_count: number;
  payment_method?: string;
  refund_amount: string;
  refund_count: number;
  settlement_date: Date;
  /** OPEN, CONFIRMED, or DISCREPANCY */
  status: string;
  uid: string;
  updated_at?: Date;
}

export const AdminSettlementItemSchema = z.object({
  created_at: z.date(),
  currency: z.string(),
  fee_amount: z.string().regex(/^-?\d+$/),
  gross_amount: z.string().regex(/^-?\d+$/),
  net_amount: z.string().regex(/^-?\d+$/),
  payment_count: z.number().int(),
  payment_method: z.string().optional(),
  refund_amount: z.string().regex(/^-?\d+$/),
  refund_count: z.number().int(),
  settlement_date: z.date(),
  status: z.string(),
  uid: z.string(),
  updated_at: z.date().optional(),
});
