// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface AdminWorkCreateRequest {
  /** Authors are referenced by uid; they must already exist */
  author_uids: Array<string>;
  description?: string;
  first_publish_date?: string;
  ol_key?: string;
  /** Subjects are created on demand from their names, unlike authors */
  subject_names?: Array<string>;
  title: string;
}

export const AdminWorkCreateRequestSchema = z.object({
  author_uids: z.array(z.string()),
  description: z.string().optional(),
  first_publish_date: z.string().optional(),
  ol_key: z.string().optional(),
  subject_names: z.array(z.string()).optional(),
  title: z.string(),
});
