// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

/**
 * A user account as owned by identity. Roles are realm roles, kept in sync with Keycloak by identity.
 */

export interface AdminUserResponse {
  created_at: Date;
  email: string;
  first_name: string;
  last_login_at?: Date;
  last_name: string;
  phone?: string;
  /** Realm role names: USER, STAFF, MANAGE, SYSTEM */
  roles: Array<string>;
  /** ACTIVE, SUSPENDED, or DEACTIVATED */
  status: string;
  uid: string;
  updated_at?: Date;
}

export const AdminUserResponseSchema = z.object({
  created_at: z.date(),
  email: z.string().email(),
  first_name: z.string(),
  last_login_at: z.date().optional(),
  last_name: z.string(),
  phone: z.string().optional(),
  roles: z.array(z.string()),
  status: z.string(),
  uid: z.string(),
  updated_at: z.date().optional(),
});
