// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface UnauthorizedError {
  code: number;
  message: string;
}

export const UnauthorizedErrorSchema = z.object({
  code: z.number().int(),
  message: z.string(),
});
