// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface Address {
  city?: string;
  country?: string;
  first_name?: string;
  last_name?: string;
  line1?: string;
  line2?: string;
  state?: string;
  zip?: string;
}

export const AddressSchema = z.object({
  city: z.string().optional(),
  country: z.string().optional(),
  first_name: z.string().optional(),
  last_name: z.string().optional(),
  line1: z.string().optional(),
  line2: z.string().optional(),
  state: z.string().optional(),
  zip: z.string().optional(),
});
