// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { Address } from './address';
import { AddressSchema } from './address';

export interface CustomerUpdateRequest {
  default_billing_address?: Address;
  default_shipping_address?: Address;
  description?: string;
  email?: string;
  metadata?: Record<string, unknown>;
  name?: string;
  phone?: string;
  phone_country_code?: string;
}

export const CustomerUpdateRequestSchema = z.object({
  default_billing_address: AddressSchema.optional(),
  default_shipping_address: AddressSchema.optional(),
  description: z.string().optional(),
  email: z.string().email().optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
  name: z.string().optional(),
  phone: z.string().optional(),
  phone_country_code: z.string().optional(),
});
