// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import { FutureUsage, FutureUsageSchema } from '../constant/future-usage';
import { MandateStatus, MandateStatusSchema } from '../constant/mandate-status';
import { MandateType, MandateTypeSchema } from '../constant/mandate-type';

export interface MandateFindResponse {
  created_at: Date;
  customer_acceptance_type?: string;
  customer_accepted_at?: Date;
  customer_id: string;
  end_date?: Date;
  mandate_amount?: string;
  mandate_currency?: string;
  mandate_id: string;
  mandate_status: MandateStatus;
  mandate_type: MandateType;
  metadata?: Record<string, unknown>;
  payment_method_id?: string;
  setup_future_usage?: FutureUsage;
  start_date?: Date;
  uid: string;
  updated_at?: Date;
}

export const MandateFindResponseSchema = z.object({
  created_at: z.date(),
  customer_acceptance_type: z.string().optional(),
  customer_accepted_at: z.date().optional(),
  customer_id: z.string(),
  end_date: z.date().optional(),
  mandate_amount: z.string().regex(/^-?\d+$/).optional(),
  mandate_currency: z.string().optional(),
  mandate_id: z.string(),
  mandate_status: MandateStatusSchema,
  mandate_type: MandateTypeSchema,
  metadata: z.record(z.string(), z.unknown()).optional(),
  payment_method_id: z.string().optional(),
  setup_future_usage: FutureUsageSchema.optional(),
  start_date: z.date().optional(),
  uid: z.string(),
  updated_at: z.date().optional(),
});
