// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface NotFoundError {
  detail?: string;
  status: number;
  title: string;
  type?: string;
}

export const NotFoundErrorSchema = z.object({
  detail: z.string().optional(),
  status: z.number().int(),
  title: z.string(),
  type: z.string().optional(),
});
