// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { PaymentAttemptFindResponse } from './payment-attempt-find-response';
import { PaymentAttemptFindResponseSchema } from './payment-attempt-find-response';

export interface PaymentAttemptFindAllResponse {
  items: Array<PaymentAttemptFindResponse>;
  total: string;
}

export const PaymentAttemptFindAllResponseSchema = z.object({
  items: z.array(PaymentAttemptFindResponseSchema),
  total: z.string().regex(/^-?\d+$/),
});
