// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import { PaymentMethodEnum, PaymentMethodEnumSchema } from '../constant/payment-method-enum';

export interface PaymentMethodUpdateResponse {
  card_exp_month?: number;
  card_exp_year?: number;
  card_holder_name?: string;
  card_last4?: string;
  card_network?: string;
  created_at: Date;
  customer_id: string;
  is_default: boolean;
  metadata?: Record<string, unknown>;
  payment_method: PaymentMethodEnum;
  payment_method_id: string;
  payment_method_issuer?: string;
  payment_method_type?: string;
  uid: string;
  updated_at?: Date;
}

export const PaymentMethodUpdateResponseSchema = z.object({
  card_exp_month: z.number().int().optional(),
  card_exp_year: z.number().int().optional(),
  card_holder_name: z.string().optional(),
  card_last4: z.string().optional(),
  card_network: z.string().optional(),
  created_at: z.date(),
  customer_id: z.string(),
  is_default: z.boolean(),
  metadata: z.record(z.string(), z.unknown()).optional(),
  payment_method: PaymentMethodEnumSchema,
  payment_method_id: z.string(),
  payment_method_issuer: z.string().optional(),
  payment_method_type: z.string().optional(),
  uid: z.string(),
  updated_at: z.date().optional(),
});
