// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { Address } from './address';
import { AddressSchema } from './address';
import type { PaymentAttemptFindResponse } from './payment-attempt-find-response';
import { PaymentAttemptFindResponseSchema } from './payment-attempt-find-response';
import { AuthenticationType, AuthenticationTypeSchema } from '../constant/authentication-type';
import { CaptureMethod, CaptureMethodSchema } from '../constant/capture-method';
import { FutureUsage, FutureUsageSchema } from '../constant/future-usage';
import { PaymentMethodEnum, PaymentMethodEnumSchema } from '../constant/payment-method-enum';
import { PaymentStatus, PaymentStatusSchema } from '../constant/payment-status';

export interface PaymentUpdateResponse {
  amount: string;
  amount_capturable?: string;
  amount_captured?: string;
  attempts?: Array<PaymentAttemptFindResponse>;
  authentication_type?: AuthenticationType;
  billing_address?: Address;
  cancelled_at?: Date;
  capture_method: CaptureMethod;
  captured_at?: Date;
  client_secret?: string;
  confirmed_at?: Date;
  connector?: string;
  connector_transaction_id?: string;
  created_at: Date;
  currency: string;
  customer_id?: string;
  description?: string;
  error_code?: string;
  error_message?: string;
  mandate_id?: string;
  merchant_id?: string;
  metadata?: Record<string, unknown>;
  off_session: boolean;
  payment_id: string;
  payment_method?: PaymentMethodEnum;
  payment_method_id?: string;
  payment_method_type?: string;
  profile_id?: string;
  return_url?: string;
  setup_future_usage?: FutureUsage;
  shipping_address?: Address;
  statement_descriptor?: string;
  status: PaymentStatus;
  surcharge_amount?: string;
  tax_amount?: string;
  uid: string;
  updated_at?: Date;
}

export const PaymentUpdateResponseSchema = z.object({
  amount: z.string().regex(/^-?\d+$/),
  amount_capturable: z.string().regex(/^-?\d+$/).optional(),
  amount_captured: z.string().regex(/^-?\d+$/).optional(),
  attempts: z.array(PaymentAttemptFindResponseSchema).optional(),
  authentication_type: AuthenticationTypeSchema.optional(),
  billing_address: AddressSchema.optional(),
  cancelled_at: z.date().optional(),
  capture_method: CaptureMethodSchema,
  captured_at: z.date().optional(),
  client_secret: z.string().optional(),
  confirmed_at: z.date().optional(),
  connector: z.string().optional(),
  connector_transaction_id: z.string().optional(),
  created_at: z.date(),
  currency: z.string(),
  customer_id: z.string().optional(),
  description: z.string().optional(),
  error_code: z.string().optional(),
  error_message: z.string().optional(),
  mandate_id: z.string().optional(),
  merchant_id: z.string().optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
  off_session: z.boolean(),
  payment_id: z.string(),
  payment_method: PaymentMethodEnumSchema.optional(),
  payment_method_id: z.string().optional(),
  payment_method_type: z.string().optional(),
  profile_id: z.string().optional(),
  return_url: z.string().optional(),
  setup_future_usage: FutureUsageSchema.optional(),
  shipping_address: AddressSchema.optional(),
  statement_descriptor: z.string().optional(),
  status: PaymentStatusSchema,
  surcharge_amount: z.string().regex(/^-?\d+$/).optional(),
  tax_amount: z.string().regex(/^-?\d+$/).optional(),
  uid: z.string(),
  updated_at: z.date().optional(),
});
