env:
  - name: SPRING_PROFILES_ACTIVE
    value: query,local
  - name: SPRING_CONFIG_IMPORT
    value: "configserver:http://cloud-config.example.com"

istio:
  enabled: true
  host: "catalog-query.example.com"
