image:
  pullPolicy: IfNotPresent

envs:
  imagesPullPolicy: IfNotPresent

deployment:
  resources:
    limits:
      cpu: 500m
      memory: 768Mi
    requests:
      cpu: 50m
      memory: 512Mi

replicaCount: 1
