// Generated by oapi-codegen-cli (1.0.0)

/**
 * Thrown by every FreightApiClient method when the HTTP response is not 2xx.
 * Carries the status code and the response body parsed per the response's declared
 * content-type (JSON parsed object, text body for `text/*`, raw `Blob` for binary,
 * or `undefined` when the response had no body).
 */
export class ApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly statusText: string,
    public readonly body: unknown,
  ) {
    super(`HTTP ${status}: ${statusText}`);
    this.name = 'ApiError';
  }
}
import type { FreightCreateRequest } from '../model/freight-create-request';
import type { FreightFindAllResponse } from '../model/freight-find-all-response';
import type { FreightFindResponse } from '../model/freight-find-response';
import type { FreightUpdateResponse } from '../model/freight-update-response';
import type { FreightUpdateStatusRequest } from '../model/freight-update-status-request';
import { FreightStatus } from '../constant/freight-status';

export interface Pageable {
  page?: number;
  size?: number;
  sort?: string;
}

/**
 * Credentials for FreightApi. One field per declared security scheme;
 * supply the value for the scheme(s) the operation you call requires.
 *   - `api-key` schemes carry the raw key (set as the configured header / query / cookie).
 *   - `http-bearer` / `oauth2` / `openid-connect` carry the token (sent as `Authorization: Bearer …`).
 *   - `http-basic` carries the already-base64-encoded `username:password` (sent as `Authorization: Basic …`).
 */
export interface FreightApiCredentials {
  /** Scheme `BearerAuth` (`http-bearer`). */
  bearerAuth?: string;
}

/**
 * Freight API
 */
export interface FreightApi {

  /**
   * List freights
   */
  freightsGetAll(
    shipmentUid: string | undefined,
    carrierUid: string | undefined,
    status: FreightStatus | undefined,
    pageable: Pageable,
  ): Promise<FreightFindAllResponse>;

  /**
   * Create freight
   *
   * Response headers (on success; read via `response.headers` — not part of the return value):
   * - `location`: string — Location of the created resource
   */
  freightsCreate(
    body: FreightCreateRequest,
  ): Promise<void>;

  /**
   * Find freight by shipment
   * Errors:
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  freightsReadByShipment(
    shipmentUid: string,
  ): Promise<FreightFindResponse>;

  /**
   * Find freight
   * Errors:
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  freightsRead(
    uid: string,
  ): Promise<FreightFindResponse>;

  /**
   * Update freight status
   * Errors:
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  freightsUpdateStatus(
    uid: string,
    body: FreightUpdateStatusRequest,
  ): Promise<FreightUpdateResponse>;
}

export class FreightApiClient implements FreightApi {
  private readonly baseUrl: string;
  private readonly credentials: FreightApiCredentials;

  constructor(baseUrl: string, credentials: FreightApiCredentials = {}) {
    this.baseUrl = baseUrl;
    this.credentials = credentials;
  }

  async freightsGetAll(
    shipmentUid: string | undefined,
    carrierUid: string | undefined,
    status: FreightStatus | undefined,
    pageable: Pageable,
  ): Promise<FreightFindAllResponse> {
    const params = new URLSearchParams();
    if (shipmentUid !== undefined) params.append('shipment_uid', Array.isArray(shipmentUid) ? (shipmentUid as readonly unknown[]).join(',') : String(shipmentUid));
    if (carrierUid !== undefined) params.append('carrier_uid', Array.isArray(carrierUid) ? (carrierUid as readonly unknown[]).join(',') : String(carrierUid));
    if (status !== undefined) params.append('status', Array.isArray(status) ? (status as readonly unknown[]).join(',') : String(status));
    if (pageable.page !== undefined) params.append('page', String(pageable.page));
    if (pageable.size !== undefined) params.append('size', String(pageable.size));
    if (pageable.sort !== undefined) params.append('sort', pageable.sort);
    const query = params.toString();
    const url = `${this.baseUrl}/api/v1/freights${query ? `?${query}` : ''}`;
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as FreightFindAllResponse;
  }

  async freightsCreate(
    body: FreightCreateRequest,
  ): Promise<void> {
    const url = `${this.baseUrl}/api/v1/freights`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
      body: JSON.stringify(body),
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
  }

  async freightsReadByShipment(
    shipmentUid: string,
  ): Promise<FreightFindResponse> {
    const url = `${this.baseUrl}/api/v1/freights/shipment/${shipmentUid}`;
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as FreightFindResponse;
  }

  async freightsRead(
    uid: string,
  ): Promise<FreightFindResponse> {
    const url = `${this.baseUrl}/api/v1/freights/${uid}`;
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as FreightFindResponse;
  }

  async freightsUpdateStatus(
    uid: string,
    body: FreightUpdateStatusRequest,
  ): Promise<FreightUpdateResponse> {
    const url = `${this.baseUrl}/api/v1/freights/${uid}/status`;
    const response = await fetch(url, {
      method: 'PATCH',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
      body: JSON.stringify(body),
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as FreightUpdateResponse;
  }
}
