// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export enum AuditStatus {
  AuditStatusInProgress = 'IN_PROGRESS',
  AuditStatusCompleted = 'COMPLETED',
}

export const AuditStatusSchema = z.enum([
  'IN_PROGRESS',
  'COMPLETED',
]);

/**
 * Parses an OpenAPI string value into a {@link AuditStatus}.
 * @throws {Error} when the value is not a known AuditStatus.
 */
export function parseAuditStatus(value: string): AuditStatus {
  if (isAuditStatus(value)) {
    return value;
  }
  throw new Error(`Invalid AuditStatus value: ${value}`);
}

/** Type guard returning whether `value` is a known {@link AuditStatus}. */
export function isAuditStatus(value: string): value is AuditStatus {
  return (Object.values(AuditStatus) as string[]).includes(value);
}
