// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export enum ClosingStatus {
  ClosingStatusOpen = 'OPEN',
  ClosingStatusClosed = 'CLOSED',
}

export const ClosingStatusSchema = z.enum([
  'OPEN',
  'CLOSED',
]);

/**
 * Parses an OpenAPI string value into a {@link ClosingStatus}.
 * @throws {Error} when the value is not a known ClosingStatus.
 */
export function parseClosingStatus(value: string): ClosingStatus {
  if (isClosingStatus(value)) {
    return value;
  }
  throw new Error(`Invalid ClosingStatus value: ${value}`);
}

/** Type guard returning whether `value` is a known {@link ClosingStatus}. */
export function isClosingStatus(value: string): value is ClosingStatus {
  return (Object.values(ClosingStatus) as string[]).includes(value);
}
