// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export enum TransferStatus {
  TransferStatusPending = 'PENDING',
  TransferStatusInTransit = 'IN_TRANSIT',
  TransferStatusCompleted = 'COMPLETED',
  TransferStatusCancelled = 'CANCELLED',
}

export const TransferStatusSchema = z.enum([
  'PENDING',
  'IN_TRANSIT',
  'COMPLETED',
  'CANCELLED',
]);

/**
 * Parses an OpenAPI string value into a {@link TransferStatus}.
 * @throws {Error} when the value is not a known TransferStatus.
 */
export function parseTransferStatus(value: string): TransferStatus {
  if (isTransferStatus(value)) {
    return value;
  }
  throw new Error(`Invalid TransferStatus value: ${value}`);
}

/** Type guard returning whether `value` is a known {@link TransferStatus}. */
export function isTransferStatus(value: string): value is TransferStatus {
  return (Object.values(TransferStatus) as string[]).includes(value);
}
