CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE ROLE debezium WITH LOGIN REPLICATION;
GRANT USAGE ON SCHEMA public TO debezium;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO debezium;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO debezium;
GRANT CREATE ON DATABASE ${database} TO debezium;
GRANT ${app_user} TO debezium;
