variable "namespace" {
  description = "Namespace name"
  type        = string
}

variable "seaweedfs_address" {
  description = "SeaweedFS admin UI hostname (Gateway API HTTPRoute hostname)"
  type        = string
}

variable "seaweedfs_service_name" {
  description = "SeaweedFS admin in-cluster Service name"
  type        = string
}

variable "seaweedfs_api_address" {
  description = "SeaweedFS S3 API hostname (Gateway API HTTPRoute hostname)"
  type        = string
}

variable "seaweedfs_api_service_name" {
  description = "SeaweedFS S3 in-cluster Service name"
  type        = string
}

variable "vault_url" {
  description = "Vault URL (scheme + host[:port])"
  type        = string
}

variable "vault_role_id" {
  description = "Vault AppRole role ID"
  type        = string
}

variable "vault_secret_id" {
  description = "Vault AppRole secret ID"
  type        = string
  sensitive   = true
}

variable "s3_access_key" {
  description = "SeaweedFS S3 admin access key (pre-generated by the vault unit)"
  type        = string
  sensitive   = true
}

variable "s3_secret_key" {
  description = "SeaweedFS S3 admin secret key (pre-generated by the vault unit)"
  type        = string
  sensitive   = true
}

variable "s3_endpoint" {
  description = "SeaweedFS S3 API endpoint for bucket creation; routed via the api_route HTTPRoute through the istio gateway. Must match the terragrunt root S3 backend."
  type        = string
}

variable "bucket_names" {
  description = "Buckets to provision in seaweedfs S3 (includes the terragrunt state bucket)"
  type        = list(string)
}
