ALTER TABLE publisher REPLICA IDENTITY FULL;
ALTER TABLE author REPLICA IDENTITY FULL;
ALTER TABLE work REPLICA IDENTITY FULL;
ALTER TABLE edition REPLICA IDENTITY FULL;
ALTER TABLE subject REPLICA IDENTITY FULL;
ALTER TABLE work_author_mapping REPLICA IDENTITY FULL;
ALTER TABLE work_subject_mapping REPLICA IDENTITY FULL;
