ALTER TABLE publisher REPLICA IDENTITY DEFAULT;
ALTER TABLE author REPLICA IDENTITY DEFAULT;
ALTER TABLE work REPLICA IDENTITY DEFAULT;
ALTER TABLE edition REPLICA IDENTITY DEFAULT;
ALTER TABLE subject REPLICA IDENTITY DEFAULT;
ALTER TABLE work_author_mapping REPLICA IDENTITY DEFAULT;
ALTER TABLE work_subject_mapping REPLICA IDENTITY DEFAULT;
