crds:
  enabled: false

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 100Gi

    enableOTLPReceiver: true
    otlp:
      translationStrategy: UnderscoreEscapingWithSuffixes
      promoteResourceAttributes:
        - service.instance.id
        - service.name
        - service.namespace
        - cloud.availability_zone
        - cloud.region
        - container.name
        - deployment.environment.name
        - k8s.cluster.name
        - k8s.container.name
        - k8s.cronjob.name
        - k8s.daemonset.name
        - k8s.deployment.name
        - k8s.job.name
        - k8s.namespace.name
        - k8s.pod.name
        - k8s.replicaset.name
        - k8s.statefulset.name
    tsdb:
      outOfOrderTimeWindow: 30m

    resources:
      requests:
        cpu: 100m
        memory: 2560Mi
      limits:
        cpu: "1"
        memory: 4Gi

grafana:
  enabled: false

kubeControllerManager:
  endpoints:
    - 192.168.0.20
  service:
    port: 10257
    targetPort: 10257
  serviceMonitor:
    https: true
    insecureSkipVerify: true
    metricRelabelings:
      - sourceLabels: [__name__]
        regex: "workqueue_.*|rest_client_.*|node_collector_.*|process_.*|go_goroutines"
        action: keep

kubeScheduler:
  endpoints:
    - 192.168.0.20
  service:
    port: 10259
    targetPort: 10259
  serviceMonitor:
    https: true
    insecureSkipVerify: true
    metricRelabelings:
      - sourceLabels: [__name__]
        regex: "scheduler_.*|rest_client_.*|process_.*|go_goroutines"
        action: keep

kubeProxy:
  endpoints:
    - 192.168.0.20
  serviceMonitor:
    metricRelabelings:
      - sourceLabels: [__name__]
        regex: "kubeproxy_.*|rest_client_.*|process_.*|go_goroutines"
        action: keep

kubeEtcd:
  endpoints:
    - 192.168.0.20

prometheusOperator:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 256Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 384Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 200m
      memory: 128Mi
