// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export enum OrderStatus {
  OrderStatusPending = 'PENDING',
  OrderStatusPaid = 'PAID',
  OrderStatusShipped = 'SHIPPED',
  OrderStatusDelivered = 'DELIVERED',
  OrderStatusCancelled = 'CANCELLED',
  OrderStatusRefunded = 'REFUNDED',
}

export const OrderStatusSchema = z.enum([
  'PENDING',
  'PAID',
  'SHIPPED',
  'DELIVERED',
  'CANCELLED',
  'REFUNDED',
]);

/**
 * Parses an OpenAPI string value into a {@link OrderStatus}.
 * @throws {Error} when the value is not a known OrderStatus.
 */
export function parseOrderStatus(value: string): OrderStatus {
  if (isOrderStatus(value)) {
    return value;
  }
  throw new Error(`Invalid OrderStatus value: ${value}`);
}

/** Type guard returning whether `value` is a known {@link OrderStatus}. */
export function isOrderStatus(value: string): value is OrderStatus {
  return (Object.values(OrderStatus) as string[]).includes(value);
}
