// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { CarrierItem } from './carrier-item';
import { CarrierItemSchema } from './carrier-item';

export interface CarrierFindAllResponse {
  items: Array<CarrierItem>;
  total: string;
}

export const CarrierFindAllResponseSchema = z.object({
  items: z.array(CarrierItemSchema),
  total: z.string().regex(/^-?\d+$/),
});
