// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface CarrierCreateRequest {
  base_rate: number;
  code: string;
  contact_email?: string;
  contact_name?: string;
  contact_phone?: string;
  name: string;
  rate_per_kg: number;
}

export const CarrierCreateRequestSchema = z.object({
  base_rate: z.number(),
  code: z.string(),
  contact_email: z.string().optional(),
  contact_name: z.string().optional(),
  contact_phone: z.string().optional(),
  name: z.string(),
  rate_per_kg: z.number(),
});
