// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { CarrierPerformance } from './carrier-performance';
import { CarrierPerformanceSchema } from './carrier-performance';
import type { ShipmentStatusCount } from './shipment-status-count';
import { ShipmentStatusCountSchema } from './shipment-status-count';

export interface DashboardResponse {
  avg_delivery_hours?: number;
  carrier_performances: Array<CarrierPerformance>;
  on_time_delivery_rate?: number;
  status_counts: Array<ShipmentStatusCount>;
  total_freight_cost: number;
  total_shipments: string;
}

export const DashboardResponseSchema = z.object({
  avg_delivery_hours: z.number().optional(),
  carrier_performances: z.array(CarrierPerformanceSchema),
  on_time_delivery_rate: z.number().optional(),
  status_counts: z.array(ShipmentStatusCountSchema),
  total_freight_cost: z.number(),
  total_shipments: z.string().regex(/^-?\d+$/),
});
