// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { FreightItem } from './freight-item';
import { FreightItemSchema } from './freight-item';

export interface FreightFindAllResponse {
  items: Array<FreightItem>;
  total: string;
}

export const FreightFindAllResponseSchema = z.object({
  items: z.array(FreightItemSchema),
  total: z.string().regex(/^-?\d+$/),
});
