// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface ShipmentCreateRequest {
  carrier_uid?: string;
  destination_address: string;
  destination_city: string;
  destination_country_code: string;
  destination_postal_code: string;
  destination_state: string;
  order_uid: string;
  origin_address: string;
  planned_delivery_at?: Date;
  planned_pickup_at?: Date;
  weight_kg?: number;
}

export const ShipmentCreateRequestSchema = z.object({
  carrier_uid: z.string().optional(),
  destination_address: z.string(),
  destination_city: z.string(),
  destination_country_code: z.string(),
  destination_postal_code: z.string(),
  destination_state: z.string(),
  order_uid: z.string(),
  origin_address: z.string(),
  planned_delivery_at: z.date().optional(),
  planned_pickup_at: z.date().optional(),
  weight_kg: z.number().optional(),
});
