// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface ShipmentStatusCount {
  count: string;
  status: string;
}

export const ShipmentStatusCountSchema = z.object({
  count: z.string().regex(/^-?\d+$/),
  status: z.string(),
});
