// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import { ShipmentStatus, ShipmentStatusSchema } from '../constant/shipment-status';

export interface TrackingItem {
  created_at: Date;
  description: string;
  location: string;
  occurred_at: Date;
  shipment_uid: string;
  status: ShipmentStatus;
  uid: string;
}

export const TrackingItemSchema = z.object({
  created_at: z.date(),
  description: z.string(),
  location: z.string(),
  occurred_at: z.date(),
  shipment_uid: z.string(),
  status: ShipmentStatusSchema,
  uid: z.string(),
});
