// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import { ShipmentStatus, ShipmentStatusSchema } from '../constant/shipment-status';

export interface TrackingCreateRequest {
  description: string;
  location: string;
  status: ShipmentStatus;
}

export const TrackingCreateRequestSchema = z.object({
  description: z.string(),
  location: z.string(),
  status: ShipmentStatusSchema,
});
