// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { TrackingItem } from './tracking-item';
import { TrackingItemSchema } from './tracking-item';

export interface TrackingFindAllResponse {
  items: Array<TrackingItem>;
}

export const TrackingFindAllResponseSchema = z.object({
  items: z.array(TrackingItemSchema),
});
