// Code generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0); DO NOT EDIT.
//
// Catalog service API
//
// Catalog service API of Bookstore microservices
//
// API version: 0.1.0
// Contact: admin@example.com

package openapi

import (
	"github.com/gin-gonic/gin"
)

type BookAPI interface {

	// ApiV1BooksGet Get /api/v1/books
	// Find all books
	ApiV1BooksGet(c *gin.Context)

	// ApiV1BooksIdDelete Delete /api/v1/books/:id
	// Delete book
	ApiV1BooksIdDelete(c *gin.Context)

	// ApiV1BooksIdGet Get /api/v1/books/:id
	// Find book
	ApiV1BooksIdGet(c *gin.Context)

	// ApiV1BooksIdPut Put /api/v1/books/:id
	// Update book
	ApiV1BooksIdPut(c *gin.Context)

	// ApiV1BooksPost Post /api/v1/books
	// Add new book
	ApiV1BooksPost(c *gin.Context)
}
