// Code generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0); DO NOT EDIT.
//
// Catalog service API
//
// Catalog service API of Bookstore microservices
//
// API version: 0.1.0
// Contact: admin@example.com

package openapi

// Find all books
// Find all books (operationId: ApiV1BooksGet)
type BookFindAllWebParam struct {
	Title     *string `form:"title,omitempty"`
	Publisher *string `form:"publisher,omitempty"`
	AuthorIds []int64 `form:"author_ids,omitempty"`
	// Field to sort by
	Sort string `form:"sort,omitempty"`
	// Sorting order
	Order string `form:"order,omitempty"`
	// Number of items to return
	Limit int32 `form:"limit,omitempty"`
	// The number of items to skip
	Offset int32 `form:"offset,omitempty"`
}

// Delete book
// Delete book (operationId: ApiV1BooksIdDelete)
type BookDeleteWebParam struct {
	Id int64 `uri:"id"`
}

// Find book
// Find book (operationId: ApiV1BooksIdGet)
type BookFindWebParam struct {
	Id int64 `uri:"id"`
}

// Update book
// Update book (operationId: ApiV1BooksIdPut)
type BookUpdateWebParam struct {
	Id int64 `uri:"id"`
}
