// Code generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0); DO NOT EDIT.
//
// Catalog service API
//
// Catalog service API of Bookstore microservices
//
// API version: 0.1.0
// Contact: admin@example.com

package openapi

// Find all publishers
// Find all publishers (operationId: ApiV1PublishersGet)
type PublisherFindAllWebParam struct {
	Name *string `form:"name,omitempty"`
	// Field to sort by
	Sort string `form:"sort,omitempty"`
	// Sorting order
	Order string `form:"order,omitempty"`
	// Number of items to return
	Limit int32 `form:"limit,omitempty"`
	// The number of items to skip
	Offset int32 `form:"offset,omitempty"`
}

// Delete publisher
// Delete publisher (operationId: ApiV1PublishersIdDelete)
type PublisherDeleteWebParam struct {
	Id int64 `uri:"id"`
}

// Find publisher
// Find publisher (operationId: ApiV1PublishersIdGet)
type PublisherFindWebParam struct {
	Id int64 `uri:"id"`
}

// Update publisher
// Update publisher (operationId: ApiV1PublishersIdPut)
type PublisherUpdateWebParam struct {
	Id int64 `uri:"id"`
}
