// Code generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0); DO NOT EDIT.
//
// Catalog service API
//
// Catalog service API of Bookstore microservices
//
// API version: 0.1.0
// Contact: admin@example.com

package openapi

import (
	"github.com/gin-gonic/gin"
)

type CategoryAPI interface {

	// ApiV1CategoriesGet Get /api/v1/categories
	// Find all categories
	ApiV1CategoriesGet(c *gin.Context)
}
