// Code generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0); DO NOT EDIT.
//
// Catalog service API
//
// Catalog service API of Bookstore microservices
//
// API version: 0.1.0
// Contact: admin@example.com

package openapi

type BookFindAllWebResp struct {
	Total int64 `json:"total,omitempty"`

	Items []BookFindWebResp `json:"items,omitempty"`
}
