// Code generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0); DO NOT EDIT.
//
// Catalog service API
//
// Catalog service API of Bookstore microservices
//
// API version: 0.1.0
// Contact: admin@example.com

package openapi

type BookUpdateWebReq struct {
	Title string `json:"title,omitempty"`

	Isbn string `json:"isbn,omitempty"`

	Price float64 `json:"price,omitempty"`

	Description string `json:"description,omitempty"`

	CategoryId int64 `json:"category_id,omitempty"`

	PublisherId int64 `json:"publisher_id,omitempty"`

	AuthorIds []int64 `json:"author_ids,omitempty"`
}
