externalURL: http://harbor.example.com

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      size: 100Gi
    jobservice:
      size: 100Gi
    trivy:
      size: 100Gi
  imageChartStorage:
    disableredirect: true
    type: filesystem
    filesystem:
      rootdirectory: /storage
    s3:
      region: us-west-1
      bucket: harbor-storage
      regionendpoint: http://minio.minio.svc.cluster.local:9000

tracing:
  enabled: false

certificateVolume:
  resources:
    requests:
      cpu: 10m
      memory: 512Mi
      ephemeral-storage: 50Mi
    limits:
      cpu: 750m
      memory: 768Mi
      ephemeral-storage: 2Gi

nginx:
  tls:
    enabled: false
  podAnnotations:
    sidecar.istio.io/proxyCPU: "10m"
  resources:
    requests:
      cpu: 10m
      memory: 512Mi
      ephemeral-storage: 50Mi
    limits:
      cpu: 750m
      memory: 768Mi
      ephemeral-storage: 2Gi
  automountServiceAccountToken: true

portal:
  podAnnotations:
    sidecar.istio.io/proxyCPU: "10m"
  resources:
    requests:
      cpu: 10m
      memory: 512Mi
      ephemeral-storage: 50Mi
    limits:
      cpu: 750m
      memory: 768Mi
      ephemeral-storage: 2Gi
  automountServiceAccountToken: true

core:
  podAnnotations:
    sidecar.istio.io/proxyCPU: "10m"
  resources:
    requests:
      cpu: 10m
      memory: 512Mi
      ephemeral-storage: 50Mi
    limits:
      cpu: 750m
      memory: 768Mi
      ephemeral-storage: 2Gi
  automountServiceAccountToken: true

jobservice:
  podAnnotations:
    sidecar.istio.io/proxyCPU: "10m"
  resources:
    requests:
      cpu: 10m
      memory: 512Mi
      ephemeral-storage: 50Mi
    limits:
      cpu: 750m
      memory: 768Mi
      ephemeral-storage: 2Gi
  automountServiceAccountToken: true

registry:
  automountServiceAccountToken: true
  podAnnotations:
    sidecar.istio.io/proxyCPU: "10m"
  server:
    resources:
      requests:
        cpu: 10m
        memory: 512Mi
        ephemeral-storage: 50Mi
      limits:
        cpu: 750m
        memory: 768Mi
        ephemeral-storage: 2Gi
  controller:
    resources:
      requests:
        cpu: 10m
        memory: 512Mi
        ephemeral-storage: 50Mi
      limits:
        cpu: 750m
        memory: 768Mi
        ephemeral-storage: 2Gi

trivy:
  enabled: true
  podAnnotations:
    sidecar.istio.io/proxyCPU: "10m"
  resources:
    requests:
      cpu: 10m
      memory: 512Mi
      ephemeral-storage: 50Mi
    limits:
      cpu: 750m
      memory: 768Mi
      ephemeral-storage: 2Gi
  automountServiceAccountToken: true

exporter:
  podAnnotations:
    sidecar.istio.io/proxyCPU: "10m"
  resources:
    requests:
      cpu: 10m
      memory: 512Mi
      ephemeral-storage: 50Mi
    limits:
      cpu: 750m
      memory: 768Mi
      ephemeral-storage: 2Gi
  automountServiceAccountToken: true

postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    postgresPassword: postgres
  architecture: standalone
  primary:
    podAnnotations:
      sidecar.istio.io/proxyCPU: "10m"
    resources:
      requests:
        cpu: 10m
        memory: 512Mi
        ephemeral-storage: 50Mi
      limits:
        cpu: 750m
        memory: 768Mi
        ephemeral-storage: 2Gi

redis:
  enabled: true
  auth:
    enabled: false
  architecture: standalone
  sentinel:
    enabled: false
  master:
    podAnnotations:
      sidecar.istio.io/proxyCPU: "10m"
    resources:
      requests:
        cpu: 10m
        memory: 512Mi
        ephemeral-storage: 50Mi
      limits:
        cpu: 750m
        memory: 768Mi
        ephemeral-storage: 2Gi

logLevel: debug
