// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: modules/author/v1/author.proto

package authorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorFindAllProtoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	BookId        *int64                 `protobuf:"varint,2,opt,name=book_id,json=bookId,proto3,oneof" json:"book_id,omitempty"`
	Filter        *QueryFilter           `protobuf:"bytes,3,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorFindAllProtoReq) Reset() {
	*x = AuthorFindAllProtoReq{}
	mi := &file_modules_author_v1_author_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorFindAllProtoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorFindAllProtoReq) ProtoMessage() {}

func (x *AuthorFindAllProtoReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_author_v1_author_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorFindAllProtoReq.ProtoReflect.Descriptor instead.
func (*AuthorFindAllProtoReq) Descriptor() ([]byte, []int) {
	return file_modules_author_v1_author_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorFindAllProtoReq) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *AuthorFindAllProtoReq) GetBookId() int64 {
	if x != nil && x.BookId != nil {
		return *x.BookId
	}
	return 0
}

func (x *AuthorFindAllProtoReq) GetFilter() *QueryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type QueryFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sort          string                 `protobuf:"bytes,1,opt,name=sort,proto3" json:"sort,omitempty"`
	Order         string                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFilter) Reset() {
	*x = QueryFilter{}
	mi := &file_modules_author_v1_author_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFilter) ProtoMessage() {}

func (x *QueryFilter) ProtoReflect() protoreflect.Message {
	mi := &file_modules_author_v1_author_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFilter.ProtoReflect.Descriptor instead.
func (*QueryFilter) Descriptor() ([]byte, []int) {
	return file_modules_author_v1_author_proto_rawDescGZIP(), []int{1}
}

func (x *QueryFilter) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *QueryFilter) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *QueryFilter) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryFilter) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type AuthorFindAllProtoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Items         []*AuthorFindProtoResp `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorFindAllProtoResp) Reset() {
	*x = AuthorFindAllProtoResp{}
	mi := &file_modules_author_v1_author_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorFindAllProtoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorFindAllProtoResp) ProtoMessage() {}

func (x *AuthorFindAllProtoResp) ProtoReflect() protoreflect.Message {
	mi := &file_modules_author_v1_author_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorFindAllProtoResp.ProtoReflect.Descriptor instead.
func (*AuthorFindAllProtoResp) Descriptor() ([]byte, []int) {
	return file_modules_author_v1_author_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorFindAllProtoResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AuthorFindAllProtoResp) GetItems() []*AuthorFindProtoResp {
	if x != nil {
		return x.Items
	}
	return nil
}

type AuthorFindProtoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorFindProtoReq) Reset() {
	*x = AuthorFindProtoReq{}
	mi := &file_modules_author_v1_author_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorFindProtoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorFindProtoReq) ProtoMessage() {}

func (x *AuthorFindProtoReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_author_v1_author_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorFindProtoReq.ProtoReflect.Descriptor instead.
func (*AuthorFindProtoReq) Descriptor() ([]byte, []int) {
	return file_modules_author_v1_author_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorFindProtoReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AuthorFindProtoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorFindProtoResp) Reset() {
	*x = AuthorFindProtoResp{}
	mi := &file_modules_author_v1_author_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorFindProtoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorFindProtoResp) ProtoMessage() {}

func (x *AuthorFindProtoResp) ProtoReflect() protoreflect.Message {
	mi := &file_modules_author_v1_author_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorFindProtoResp.ProtoReflect.Descriptor instead.
func (*AuthorFindProtoResp) Descriptor() ([]byte, []int) {
	return file_modules_author_v1_author_proto_rawDescGZIP(), []int{4}
}

func (x *AuthorFindProtoResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuthorFindProtoResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_modules_author_v1_author_proto protoreflect.FileDescriptor

const file_modules_author_v1_author_proto_rawDesc = "" +
	"\n" +
	"\x1emodules/author/v1/author.proto\x12\tauthor.v1\"\xa3\x01\n" +
	"\x15AuthorFindAllProtoReq\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1c\n" +
	"\abook_id\x18\x02 \x01(\x03H\x01R\x06bookId\x88\x01\x01\x123\n" +
	"\x06filter\x18\x03 \x01(\v2\x16.author.v1.QueryFilterH\x02R\x06filter\x88\x01\x01B\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_book_idB\t\n" +
	"\a_filter\"e\n" +
	"\vQueryFilter\x12\x12\n" +
	"\x04sort\x18\x01 \x01(\tR\x04sort\x12\x14\n" +
	"\x05order\x18\x02 \x01(\tR\x05order\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"d\n" +
	"\x16AuthorFindAllProtoResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x124\n" +
	"\x05items\x18\x02 \x03(\v2\x1e.author.v1.AuthorFindProtoRespR\x05items\"$\n" +
	"\x12AuthorFindProtoReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"9\n" +
	"\x13AuthorFindProtoResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xb7\x01\n" +
	"\rAuthorService\x12W\n" +
	"\x0eFindAllAuthors\x12 .author.v1.AuthorFindAllProtoReq\x1a!.author.v1.AuthorFindAllProtoResp\"\x00\x12M\n" +
	"\n" +
	"FindAuthor\x12\x1d.author.v1.AuthorFindProtoReq\x1a\x1e.author.v1.AuthorFindProtoResp\"\x00B\x9c\x01\n" +
	";com.codejsha.bookstore.service.application.port.pb.authorpbB\vAuthorProtoP\x01Z\vpb/authorpb\xa2\x02\x03AXX\xaa\x02\tAuthor.V1\xca\x02\tAuthor\\V1\xe2\x02\x15Author\\V1\\GPBMetadata\xea\x02\n" +
	"Author::V1b\x06proto3"

var (
	file_modules_author_v1_author_proto_rawDescOnce sync.Once
	file_modules_author_v1_author_proto_rawDescData []byte
)

func file_modules_author_v1_author_proto_rawDescGZIP() []byte {
	file_modules_author_v1_author_proto_rawDescOnce.Do(func() {
		file_modules_author_v1_author_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_author_v1_author_proto_rawDesc), len(file_modules_author_v1_author_proto_rawDesc)))
	})
	return file_modules_author_v1_author_proto_rawDescData
}

var file_modules_author_v1_author_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_modules_author_v1_author_proto_goTypes = []any{
	(*AuthorFindAllProtoReq)(nil),  // 0: author.v1.AuthorFindAllProtoReq
	(*QueryFilter)(nil),            // 1: author.v1.QueryFilter
	(*AuthorFindAllProtoResp)(nil), // 2: author.v1.AuthorFindAllProtoResp
	(*AuthorFindProtoReq)(nil),     // 3: author.v1.AuthorFindProtoReq
	(*AuthorFindProtoResp)(nil),    // 4: author.v1.AuthorFindProtoResp
}
var file_modules_author_v1_author_proto_depIdxs = []int32{
	1, // 0: author.v1.AuthorFindAllProtoReq.filter:type_name -> author.v1.QueryFilter
	4, // 1: author.v1.AuthorFindAllProtoResp.items:type_name -> author.v1.AuthorFindProtoResp
	0, // 2: author.v1.AuthorService.FindAllAuthors:input_type -> author.v1.AuthorFindAllProtoReq
	3, // 3: author.v1.AuthorService.FindAuthor:input_type -> author.v1.AuthorFindProtoReq
	2, // 4: author.v1.AuthorService.FindAllAuthors:output_type -> author.v1.AuthorFindAllProtoResp
	4, // 5: author.v1.AuthorService.FindAuthor:output_type -> author.v1.AuthorFindProtoResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_modules_author_v1_author_proto_init() }
func file_modules_author_v1_author_proto_init() {
	if File_modules_author_v1_author_proto != nil {
		return
	}
	file_modules_author_v1_author_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_author_v1_author_proto_rawDesc), len(file_modules_author_v1_author_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_author_v1_author_proto_goTypes,
		DependencyIndexes: file_modules_author_v1_author_proto_depIdxs,
		MessageInfos:      file_modules_author_v1_author_proto_msgTypes,
	}.Build()
	File_modules_author_v1_author_proto = out.File
	file_modules_author_v1_author_proto_goTypes = nil
	file_modules_author_v1_author_proto_depIdxs = nil
}
