// Generated by oapi-codegen-cli (1.0.0)

/**
 * Thrown by every OrderShippingApiClient method when the HTTP response is not 2xx.
 * Carries the status code and the response body parsed per the response's declared
 * content-type (JSON parsed object, text body for `text/*`, raw `Blob` for binary,
 * or `undefined` when the response had no body).
 */
export class ApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly statusText: string,
    public readonly body: unknown,
  ) {
    super(`HTTP ${status}: ${statusText}`);
    this.name = 'ApiError';
  }
}
import type { OrderShippingCreateRequest } from '../model/order-shipping-create-request';
import type { OrderShippingFindResponse } from '../model/order-shipping-find-response';
import type { OrderShippingUpdateRequest } from '../model/order-shipping-update-request';

/**
 * Credentials for OrderShippingApi. One field per declared security scheme;
 * supply the value for the scheme(s) the operation you call requires.
 *   - `api-key` schemes carry the raw key (set as the configured header / query / cookie).
 *   - `http-bearer` / `oauth2` / `openid-connect` carry the token (sent as `Authorization: Bearer …`).
 *   - `http-basic` carries the already-base64-encoded `username:password` (sent as `Authorization: Basic …`).
 */
export interface OrderShippingApiCredentials {
  /** Scheme `BearerAuth` (`http-bearer`). */
  bearerAuth?: string;
}

/**
 * OrderShipping API
 */
export interface OrderShippingApi {

  /**
   * Set or replace shipping for an order (upsert)
   * Errors:
   * 400 (BadRequestError) — The server could not understand the request due to invalid syntax.
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  orderShippingSet(
    orderUid: string,
    body: OrderShippingCreateRequest,
  ): Promise<OrderShippingFindResponse>;

  /**
   * Update shipping details of an order
   * Errors:
   * 400 (BadRequestError) — The server could not understand the request due to invalid syntax.
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  orderShippingUpdate(
    orderUid: string,
    body: OrderShippingUpdateRequest,
  ): Promise<OrderShippingFindResponse>;
}

export class OrderShippingApiClient implements OrderShippingApi {
  private readonly baseUrl: string;
  private readonly credentials: OrderShippingApiCredentials;

  constructor(baseUrl: string, credentials: OrderShippingApiCredentials = {}) {
    this.baseUrl = baseUrl;
    this.credentials = credentials;
  }

  async orderShippingSet(
    orderUid: string,
    body: OrderShippingCreateRequest,
  ): Promise<OrderShippingFindResponse> {
    const url = `${this.baseUrl}/api/v1/orders/${orderUid}/shipping`;
    const response = await fetch(url, {
      method: 'PUT',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
      body: JSON.stringify(body),
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as OrderShippingFindResponse;
  }

  async orderShippingUpdate(
    orderUid: string,
    body: OrderShippingUpdateRequest,
  ): Promise<OrderShippingFindResponse> {
    const url = `${this.baseUrl}/api/v1/orders/${orderUid}/shipping`;
    const response = await fetch(url, {
      method: 'PATCH',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
      body: JSON.stringify(body),
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as OrderShippingFindResponse;
  }
}
