// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export enum CaptureMethod {
  CaptureMethodAutomatic = 'automatic',
  CaptureMethodManual = 'manual',
  CaptureMethodManualMultiple = 'manual_multiple',
  CaptureMethodScheduled = 'scheduled',
}

export const CaptureMethodSchema = z.enum([
  'automatic',
  'manual',
  'manual_multiple',
  'scheduled',
]);

/**
 * Parses an OpenAPI string value into a {@link CaptureMethod}.
 * @throws {Error} when the value is not a known CaptureMethod.
 */
export function parseCaptureMethod(value: string): CaptureMethod {
  if (isCaptureMethod(value)) {
    return value;
  }
  throw new Error(`Invalid CaptureMethod value: ${value}`);
}

/** Type guard returning whether `value` is a known {@link CaptureMethod}. */
export function isCaptureMethod(value: string): value is CaptureMethod {
  return (Object.values(CaptureMethod) as string[]).includes(value);
}
