// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export enum FutureUsage {
  FutureUsageOnSession = 'on_session',
  FutureUsageOffSession = 'off_session',
}

export const FutureUsageSchema = z.enum([
  'on_session',
  'off_session',
]);

/**
 * Parses an OpenAPI string value into a {@link FutureUsage}.
 * @throws {Error} when the value is not a known FutureUsage.
 */
export function parseFutureUsage(value: string): FutureUsage {
  if (isFutureUsage(value)) {
    return value;
  }
  throw new Error(`Invalid FutureUsage value: ${value}`);
}

/** Type guard returning whether `value` is a known {@link FutureUsage}. */
export function isFutureUsage(value: string): value is FutureUsage {
  return (Object.values(FutureUsage) as string[]).includes(value);
}
