// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export enum MandateStatus {
  MandateStatusActive = 'active',
  MandateStatusRevoked = 'revoked',
  MandateStatusInactive = 'inactive',
  MandateStatusPending = 'pending',
}

export const MandateStatusSchema = z.enum([
  'active',
  'revoked',
  'inactive',
  'pending',
]);

/**
 * Parses an OpenAPI string value into a {@link MandateStatus}.
 * @throws {Error} when the value is not a known MandateStatus.
 */
export function parseMandateStatus(value: string): MandateStatus {
  if (isMandateStatus(value)) {
    return value;
  }
  throw new Error(`Invalid MandateStatus value: ${value}`);
}

/** Type guard returning whether `value` is a known {@link MandateStatus}. */
export function isMandateStatus(value: string): value is MandateStatus {
  return (Object.values(MandateStatus) as string[]).includes(value);
}
