// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export enum PaymentStatus {
  PaymentStatusRequiresPaymentMethod = 'requires_payment_method',
  PaymentStatusRequiresConfirmation = 'requires_confirmation',
  PaymentStatusRequiresCustomerAction = 'requires_customer_action',
  PaymentStatusRequiresCapture = 'requires_capture',
  PaymentStatusProcessing = 'processing',
  PaymentStatusSucceeded = 'succeeded',
  PaymentStatusFailed = 'failed',
  PaymentStatusCancelled = 'cancelled',
  PaymentStatusPartiallyCaptured = 'partially_captured',
  PaymentStatusExpired = 'expired',
}

export const PaymentStatusSchema = z.enum([
  'requires_payment_method',
  'requires_confirmation',
  'requires_customer_action',
  'requires_capture',
  'processing',
  'succeeded',
  'failed',
  'cancelled',
  'partially_captured',
  'expired',
]);

/**
 * Parses an OpenAPI string value into a {@link PaymentStatus}.
 * @throws {Error} when the value is not a known PaymentStatus.
 */
export function parsePaymentStatus(value: string): PaymentStatus {
  if (isPaymentStatus(value)) {
    return value;
  }
  throw new Error(`Invalid PaymentStatus value: ${value}`);
}

/** Type guard returning whether `value` is a known {@link PaymentStatus}. */
export function isPaymentStatus(value: string): value is PaymentStatus {
  return (Object.values(PaymentStatus) as string[]).includes(value);
}
