// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export enum RefundType {
  RefundTypeInstant = 'instant',
  RefundTypeScheduled = 'scheduled',
}

export const RefundTypeSchema = z.enum([
  'instant',
  'scheduled',
]);

/**
 * Parses an OpenAPI string value into a {@link RefundType}.
 * @throws {Error} when the value is not a known RefundType.
 */
export function parseRefundType(value: string): RefundType {
  if (isRefundType(value)) {
    return value;
  }
  throw new Error(`Invalid RefundType value: ${value}`);
}

/** Type guard returning whether `value` is a known {@link RefundType}. */
export function isRefundType(value: string): value is RefundType {
  return (Object.values(RefundType) as string[]).includes(value);
}
