// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface EditionCreateRequest {
  cover_uids?: Array<string>;
  description?: string;
  isbn10?: string;
  isbn13?: string;
  languages?: Array<string>;
  number_of_pages?: number;
  ol_key?: string;
  physical_format?: string;
  publish_date?: string;
  publisher_uid?: string;
  title: string;
  work_uid: string;
}

export const EditionCreateRequestSchema = z.object({
  cover_uids: z.array(z.string()).optional(),
  description: z.string().optional(),
  isbn10: z.string().optional(),
  isbn13: z.string().optional(),
  languages: z.array(z.string()).optional(),
  number_of_pages: z.number().int().optional(),
  ol_key: z.string().optional(),
  physical_format: z.string().optional(),
  publish_date: z.string().optional(),
  publisher_uid: z.string().optional(),
  title: z.string(),
  work_uid: z.string(),
});
