// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface PublisherCreateRequest {
  address?: string;
  name: string;
  ol_key?: string;
}

export const PublisherCreateRequestSchema = z.object({
  address: z.string().optional(),
  name: z.string(),
  ol_key: z.string().optional(),
});
