// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface SubjectUpdateRequest {
  name?: string;
}

export const SubjectUpdateRequestSchema = z.object({
  name: z.string().optional(),
});
