// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export interface SubjectUpdateResponse {
  name: string;
  uid: string;
}

export const SubjectUpdateResponseSchema = z.object({
  name: z.string(),
  uid: z.string(),
});
