// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';
import type { AuthorItem } from './author-item';
import { AuthorItemSchema } from './author-item';
import type { SubjectItem } from './subject-item';
import { SubjectItemSchema } from './subject-item';

export interface WorkUpdateResponse {
  authors: Array<AuthorItem>;
  cover_uids?: Array<string>;
  created_at: Date;
  description?: string;
  first_publish_date?: string;
  ol_key?: string;
  subjects: Array<SubjectItem>;
  title: string;
  uid: string;
  updated_at?: Date;
}

export const WorkUpdateResponseSchema = z.object({
  authors: z.array(AuthorItemSchema),
  cover_uids: z.array(z.string()).optional(),
  created_at: z.date(),
  description: z.string().optional(),
  first_publish_date: z.string().optional(),
  ol_key: z.string().optional(),
  subjects: z.array(SubjectItemSchema),
  title: z.string(),
  uid: z.string(),
  updated_at: z.date().optional(),
});
