prometheusOperator:
  admissionWebhooks:
    patch:
      podAnnotations:
        sidecar.istio.io/inject: "false"

prometheus:
  prometheusSpec:
    additionalConfig:
      enableOTLPReceiver: true
      otlp:
        translationStrategy: NoUTF8EscapingWithSuffixes
        promoteResourceAttributes:
          - service.instance.id
          - service.name
          - service.namespace
          - cloud.availability_zone
          - cloud.region
          - container.name
          - deployment.environment.name
          - k8s.cluster.name
          - k8s.container.name
          - k8s.cronjob.name
          - k8s.daemonset.name
          - k8s.deployment.name
          - k8s.job.name
          - k8s.namespace.name
          - k8s.pod.name
          - k8s.replicaset.name
          - k8s.statefulset.name
      tsdb:
        outOfOrderTimeWindow: 30m

grafana:
  additionalDataSources:
    - name: OpenSearch
      type: elasticsearch
      uid: opensearch
      url: http://opensearch-cluster-master.opensearch.svc.cluster.local:9200
      access: proxy
      jsonData:
        timeField: "@timestamp"
    # - name: Loki
    #   type: loki
    #   uid: loki
    #   url: <loki-gateway-url>
    #   access: proxy
    #   jsonData:
    #     httpHeaderName1: "X-Scope-OrgID"
    #   secureJsonData:
    #     httpHeaderValue1: "otel"
    - name: Jaeger
      type: jaeger
      uid: jaeger
      url: http://jaeger-query.jaeger.svc.cluster.local:16686
      access: proxy
