clusterName: clusterlocal

opentelemetry-operator:
  manager:
    collectorImage:
      repository: otel/opentelemetry-collector-contrib
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 128Mi
  admissionWebhooks:
    certManager:
      enabled: true
      issuerRef:
        name: selfsigned-cluster-issuer
        kind: ClusterIssuer

collectors:
  daemon:
    presets:
      hostMetrics:
        enabled: false
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 250Mi

  cluster:
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 250Mi
    config:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318

      processors:
        batch:
          send_batch_size: 1000
          timeout: 1s
          send_batch_max_size: 1500
        resourcedetection/env:
          detectors: [env]
          timeout: 2s
          override: false

      exporters:
        debug: {}
        otlp:
          endpoint: "jaeger-collector.jaeger.svc.cluster.local:4317"
          tls:
            insecure: true
        otlphttp:
          endpoint: "http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090/api/v1/otlp"
          tls:
            insecure: true
        opensearch:
          http:
            endpoint: "http://opensearch-cluster-master.opensearch.svc.cluster.local:9200"
            tls:
              insecure: true
            auth:
              authenticator: "basicauth/opensearch"
          logs_index: otel
        # loki:
        #   endpoint: "<loki-gateway-url>/api/v1/push"
        #   tls:
        #     insecure: true
        #   headers:
        #     X-Scope-OrgID: otel

      service:
        extensions: ["basicauth/opensearch"]
        pipelines:
          traces:
            receivers: ["otlp"]
            processors: ["resourcedetection/env", "batch"]
            exporters: ["otlp", "debug"]
          metrics:
            receivers: ["otlp"]
            processors: ["resourcedetection/env", "batch"]
            exporters: ["otlphttp", "debug"]
          logs:
            receivers: ["otlp"]
            processors: ["resourcedetection/env", "batch"]
            exporters: ["opensearch", "debug"]
