clusterName: clusterlocal

opentelemetry-operator:
  manager:
    collectorImage:
      repository: otel/opentelemetry-collector-contrib
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 128Mi
  admissionWebhooks:
    certManager:
      enabled: true
      issuerRef:
        group: cert-manager.io
        name: opentelemetry-issuer
        kind: Issuer
    autoGenerateCert:
      enabled: false

collectors:
  daemon:
    mode: daemonset
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 250Mi
    presets:
      hostMetrics:
        enabled: false

    config:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      processors:
        batch:
          send_batch_size: 1000
          send_batch_max_size: 1500
          timeout: 1s
        resourcedetection/env:
          detectors: [env]
          override: false
          timeout: 2s
      exporters:
        debug: {}
        otlp:
          endpoint: "jaeger-collector.jaeger.svc.cluster.local:4317"
          tls:
            insecure: true
        otlphttp:
          endpoint: "http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090/api/v1/otlp"
          tls:
            insecure: true
        opensearch:
          http:
            endpoint: "http://opensearch-cluster-master.opensearch.svc.cluster.local:9200"
            tls:
              insecure: true
            auth:
              authenticator: "basicauth/opensearch"
          logs_index: otel
        # loki:
        #   endpoint: "<loki-gateway-url>/api/v1/push"
        #   tls:
        #     insecure: true
        #   headers:
        #     X-Scope-OrgID: otel
      service:
        extensions: ["basicauth/opensearch"]
        pipelines:
          traces:
            receivers: ["otlp"]
            processors: ["resourcedetection/env", "batch"]
            exporters: ["otlp", "debug"]
          metrics:
            receivers: ["otlp"]
            processors: ["resourcedetection/env", "batch"]
            exporters: ["otlphttp", "debug"]
          logs:
            receivers: ["otlp"]
            processors: ["resourcedetection/env", "batch"]
            exporters: ["opensearch", "debug"]

  cluster:
    replicas: 1
    mode: deployment
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 250Mi

    config:
      receivers: {}
      processors:
        batch:
          send_batch_size: 1000
          send_batch_max_size: 1500
          timeout: 1s
        resourcedetection/env:
          detectors: [env]
          override: false
          timeout: 2s
      exporters:
        debug: {}
      service:
        pipelines:
          metrics:
            receivers: ["k8s_cluster"]
            processors: ["resourcedetection/env", "batch"]
            exporters: ["debug"]
          logs:
            receivers: ["k8sobjects"]
            processors: ["resourcedetection/env", "batch"]
            exporters: ["debug"]
