replicaCount: 1

image:
  repository: harbor.example.com/bookstore/config-server
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations:
  sidecar.istio.io/rewriteAppHTTPProbers: "false"
podLabels:
  app.kubernetes.io/group: config-server

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8888
  https:
    enabled: false
    port: 8443

ingress:
  enabled: false
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /actuator/health
    port: http

readinessProbe:
  httpGet:
    path: /actuator/health
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

istio:
  enabled: false
  host: "example.com"
  tls:
    enabled: false
    httpsRedirect: false
    mode: "SIMPLE"
    credentialName: ""
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  gateway:
    annotations: {}
  virtualService:
    annotations: {}
  destinationRule:
    annotations: {}
