// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export enum CarrierStatus {
  CarrierStatusActive = 'ACTIVE',
  CarrierStatusInactive = 'INACTIVE',
}

export const CarrierStatusSchema = z.enum([
  'ACTIVE',
  'INACTIVE',
]);

/**
 * Parses an OpenAPI string value into a {@link CarrierStatus}.
 * @throws {Error} when the value is not a known CarrierStatus.
 */
export function parseCarrierStatus(value: string): CarrierStatus {
  if (isCarrierStatus(value)) {
    return value;
  }
  throw new Error(`Invalid CarrierStatus value: ${value}`);
}

/** Type guard returning whether `value` is a known {@link CarrierStatus}. */
export function isCarrierStatus(value: string): value is CarrierStatus {
  return (Object.values(CarrierStatus) as string[]).includes(value);
}
