variable "harbor_url" {
  description = "Harbor URL"
  type        = string
}

variable "vault_url" {
  description = "Vault URL"
  type        = string
}

variable "vault_auth_role" {
  type = string
}

variable "vault_k8s_jwt" {
  description = "Short-lived Kubernetes ServiceAccount token for Vault kubernetes-auth login"
  type        = string
  sensitive   = true
}

variable "harbor_usernames" {
  description = "Harbor usernames to create. Passwords are generated by this module and written to vault at kv/harbor/users/<username>/credentials."
  type        = list(string)
}

variable "harbor_projects" {
  description = "Harbor project configuration with members"
  type = map(object({
    project_name = string
    is_public    = bool
    members = list(object({
      username = string
      role     = string
    }))
  }))
}

variable "robot_name" {
  description = "Harbor robot account used by Tekton to push images"
  type        = string
  default     = "tekton-ci"
}
