apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
  namespace: "${namespace}"
  labels:
    app.kubernetes.io/name: argocd-env-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  ARGOCD_AUTH_TOKEN: "${argocd_token}"
