apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-env-configmap
  namespace: "${namespace}"
  labels:
    app.kubernetes.io/name: argocd-env-configmap
    app.kubernetes.io/part-of: argocd
data:
  ARGOCD_SERVER: "${argocd_address}"
