apiVersion: v1
kind: Secret
metadata:
  name: "${name}"
  namespace: "${namespace}"
  annotations:
    tekton.dev/git-0: "${gitea_fqdn}"
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: "${ssh_private_key}"
