app:
  logging_level: info

server:
  mode: prod

telemetry:
  service_name: delivery-app
  enabled: true
  endpoint: alloy-gateway.grafana.svc.cluster.local:4317
  profiling_endpoint: http://alloy-agent.grafana.svc.cluster.local:9095
  sampling_ratio: 0.1

database:
  host: delivery-mysql.bookstore.svc.cluster.local
  port: 3306
  db_name: delivery_db

temporal:
  enabled: true
  host: temporal-frontend.temporal.svc.cluster.local:7233
  namespace: bookstore
