// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
//
// Keycloak Admin REST API
//
// This is a REST API reference for the Keycloak Admin REST API.
//
// API version: 1.0

package idp

// Get a keystore file for the client, containing private key and public certificate
// (operationId: AdminRealmsRealmClientsClientUuidCertificatesAttrDownloadPost)
type AdminRealmsRealmClientsClientUuidCertificatesAttrDownloadPostParam struct {
	// realm name (not id!)
	Realm string `uri:"realm"`
	// id of client (not client-id!)
	ClientUuid string `uri:"client-uuid"`
	Attr       string `uri:"attr"`
}

// Generate a new keypair and certificate, and get the private key file  Generates a keypair and certificate and serves the private key in a specified keystore format. Only generated public certificate is saved in Keycloak DB - the private key is not.
// (operationId: AdminRealmsRealmClientsClientUuidCertificatesAttrGenerateAndDownloadPost)
type AdminRealmsRealmClientsClientUuidCertificatesAttrGenerateAndDownloadPostParam struct {
	// realm name (not id!)
	Realm string `uri:"realm"`
	// id of client (not client-id!)
	ClientUuid string `uri:"client-uuid"`
	Attr       string `uri:"attr"`
}

// Generate a new certificate with new key pair
// (operationId: AdminRealmsRealmClientsClientUuidCertificatesAttrGeneratePost)
type AdminRealmsRealmClientsClientUuidCertificatesAttrGeneratePostParam struct {
	// realm name (not id!)
	Realm string `uri:"realm"`
	// id of client (not client-id!)
	ClientUuid string `uri:"client-uuid"`
	Attr       string `uri:"attr"`
}

// Get key info
// (operationId: AdminRealmsRealmClientsClientUuidCertificatesAttrGet)
type AdminRealmsRealmClientsClientUuidCertificatesAttrGetParam struct {
	// realm name (not id!)
	Realm string `uri:"realm"`
	// id of client (not client-id!)
	ClientUuid string `uri:"client-uuid"`
	Attr       string `uri:"attr"`
}

// Upload only certificate, not private key
// (operationId: AdminRealmsRealmClientsClientUuidCertificatesAttrUploadCertificatePost)
type AdminRealmsRealmClientsClientUuidCertificatesAttrUploadCertificatePostParam struct {
	// realm name (not id!)
	Realm string `uri:"realm"`
	// id of client (not client-id!)
	ClientUuid string `uri:"client-uuid"`
	Attr       string `uri:"attr"`
}

// Upload certificate and eventually private key
// (operationId: AdminRealmsRealmClientsClientUuidCertificatesAttrUploadPost)
type AdminRealmsRealmClientsClientUuidCertificatesAttrUploadPostParam struct {
	// realm name (not id!)
	Realm string `uri:"realm"`
	// id of client (not client-id!)
	ClientUuid string `uri:"client-uuid"`
	Attr       string `uri:"attr"`
}
