// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
//
// Keycloak Admin REST API
//
// This is a REST API reference for the Keycloak Admin REST API.
//
// API version: 1.0

package idp

// Import a realm. Imports a realm from a full representation of that realm.
// Realm name must be unique.
type AdminRealmsPostReq struct {
}

// Base path for importing clients under this realm.
type AdminRealmsRealmClientDescriptionConverterPostReq struct {
}

// (model: ClientPoliciesRepresentation)

// (model: ClientProfilesRepresentation)

// Update a client type
// This endpoint allows you to update a realm level client type
// (model: ClientTypesRepresentation)

// Update the events provider Change the events provider and/or its configuration
// (model: RealmEventsConfigRepresentation)

type AdminRealmsRealmLocalizationLocaleKeyPutReq struct {
}

// Import localization from uploaded JSON file
type AdminRealmsRealmLocalizationLocalePostReq struct {
	Inner string `json:"inner,omitempty"`
}

// Partial import from a JSON file to an existing realm.
type AdminRealmsRealmPartialImportPostReq struct {
}

// Update the top-level information of the realm Any user, roles or client information in the representation will be ignored.
// This will only update top-level attributes of the realm.
// (model: RealmRepresentation)

// Test SMTP connection with current logged in user
type AdminRealmsRealmTestSMTPConnectionPostReq struct {
	Inner string `json:"inner,omitempty"`
}

// (model: ManagementPermissionReference)
