// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
//
// Keycloak Admin REST API
//
// This is a REST API reference for the Keycloak Admin REST API.
//
// API version: 1.0

package idp

// Delete client-level roles from user or group role mapping
type AdminRealmsRealmGroupsGroupIdRoleMappingsClientsClientIdDeleteReq struct {
	Property RoleRepresentation `json:"Property,omitempty"`
}

// Add client-level roles to the user or group role mapping
type AdminRealmsRealmGroupsGroupIdRoleMappingsClientsClientIdPostReq struct {
	Property RoleRepresentation `json:"Property,omitempty"`
}

// Delete client-level roles from user or group role mapping
type AdminRealmsRealmUsersUserIdRoleMappingsClientsClientIdDeleteReq struct {
	Property RoleRepresentation `json:"Property,omitempty"`
}

// Add client-level roles to the user or group role mapping
type AdminRealmsRealmUsersUserIdRoleMappingsClientsClientIdPostReq struct {
	Property RoleRepresentation `json:"Property,omitempty"`
}
