// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
//
// Keycloak Admin REST API
//
// This is a REST API reference for the Keycloak Admin REST API.
//
// API version: 1.0

package idp

import (
	"context"
)

type DefaultAPI interface {

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerGet)
	// GET /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server
	AdminRealmsRealmClientsClientUuidAuthzResourceServerGet(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerGetParam) (ResourceServerRepresentation, error)

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerImportPost)
	// POST /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/import
	AdminRealmsRealmClientsClientUuidAuthzResourceServerImportPost(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerImportPostParam, req ResourceServerRepresentation) error

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerPermissionEvaluatePost)
	// POST /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/permission/evaluate
	AdminRealmsRealmClientsClientUuidAuthzResourceServerPermissionEvaluatePost(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerPermissionEvaluatePostParam, req PolicyEvaluationRequest) (PolicyEvaluationResponse, error)

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerPermissionGet)
	// GET /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/permission
	AdminRealmsRealmClientsClientUuidAuthzResourceServerPermissionGet(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerPermissionGetParam) ([]AbstractPolicyRepresentation, error)

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerPermissionPost)
	// POST /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/permission
	AdminRealmsRealmClientsClientUuidAuthzResourceServerPermissionPost(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerPermissionPostParam, req AdminRealmsRealmClientsClientUuidAuthzResourceServerPermissionPostReq) error

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerPermissionProvidersGet)
	// GET /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/permission/providers
	AdminRealmsRealmClientsClientUuidAuthzResourceServerPermissionProvidersGet(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerPermissionProvidersGetParam) ([]PolicyProviderRepresentation, error)

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerPermissionSearchGet)
	// GET /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/permission/search
	AdminRealmsRealmClientsClientUuidAuthzResourceServerPermissionSearchGet(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerPermissionSearchGetParam) (AbstractPolicyRepresentation, error)

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerPolicyEvaluatePost)
	// POST /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/policy/evaluate
	AdminRealmsRealmClientsClientUuidAuthzResourceServerPolicyEvaluatePost(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerPolicyEvaluatePostParam, req PolicyEvaluationRequest) (PolicyEvaluationResponse, error)

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerPolicyGet)
	// GET /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/policy
	AdminRealmsRealmClientsClientUuidAuthzResourceServerPolicyGet(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerPolicyGetParam) ([]AbstractPolicyRepresentation, error)

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerPolicyPost)
	// POST /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/policy
	AdminRealmsRealmClientsClientUuidAuthzResourceServerPolicyPost(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerPolicyPostParam, req AdminRealmsRealmClientsClientUuidAuthzResourceServerPolicyPostReq) error

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerPolicyProvidersGet)
	// GET /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/policy/providers
	AdminRealmsRealmClientsClientUuidAuthzResourceServerPolicyProvidersGet(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerPolicyProvidersGetParam) ([]PolicyProviderRepresentation, error)

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerPolicySearchGet)
	// GET /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/policy/search
	AdminRealmsRealmClientsClientUuidAuthzResourceServerPolicySearchGet(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerPolicySearchGetParam) (AbstractPolicyRepresentation, error)

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerPut)
	// PUT /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server
	AdminRealmsRealmClientsClientUuidAuthzResourceServerPut(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerPutParam, req ResourceServerRepresentation) error

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceGet)
	// GET /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/resource
	AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceGet(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceGetParam) ([]ResourceRepresentation, error)

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerResourcePost)
	// POST /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/resource
	AdminRealmsRealmClientsClientUuidAuthzResourceServerResourcePost(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerResourcePostParam, req ResourceRepresentation) (ResourceRepresentation, error)

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceResourceIdAttributesGet)
	// GET /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/resource/{resource-id}/attributes
	AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceResourceIdAttributesGet(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceResourceIdAttributesGetParam) error

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceResourceIdDelete)
	// DELETE /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/resource/{resource-id}
	AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceResourceIdDelete(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceResourceIdDeleteParam) error

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceResourceIdGet)
	// GET /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/resource/{resource-id}
	AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceResourceIdGet(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceResourceIdGetParam) (ResourceRepresentation, error)

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceResourceIdPermissionsGet)
	// GET /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/resource/{resource-id}/permissions
	AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceResourceIdPermissionsGet(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceResourceIdPermissionsGetParam) ([]PolicyRepresentation, error)

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceResourceIdPut)
	// PUT /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/resource/{resource-id}
	AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceResourceIdPut(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceResourceIdPutParam, req ResourceRepresentation) error

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceResourceIdScopesGet)
	// GET /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/resource/{resource-id}/scopes
	AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceResourceIdScopesGet(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceResourceIdScopesGetParam) ([]ScopeRepresentation, error)

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceSearchGet)
	// GET /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/resource/search
	AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceSearchGet(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerResourceSearchGetParam) (ResourceRepresentation, error)

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerScopeGet)
	// GET /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/scope
	AdminRealmsRealmClientsClientUuidAuthzResourceServerScopeGet(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerScopeGetParam) ([]ScopeRepresentation, error)

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerScopePost)
	// POST /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/scope
	AdminRealmsRealmClientsClientUuidAuthzResourceServerScopePost(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerScopePostParam, req ScopeRepresentation) error

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerScopeScopeIdDelete)
	// DELETE /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/scope/{scope-id}
	AdminRealmsRealmClientsClientUuidAuthzResourceServerScopeScopeIdDelete(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerScopeScopeIdDeleteParam) error

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerScopeScopeIdGet)
	// GET /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/scope/{scope-id}
	AdminRealmsRealmClientsClientUuidAuthzResourceServerScopeScopeIdGet(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerScopeScopeIdGetParam) (ScopeRepresentation, error)

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerScopeScopeIdPermissionsGet)
	// GET /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/scope/{scope-id}/permissions
	AdminRealmsRealmClientsClientUuidAuthzResourceServerScopeScopeIdPermissionsGet(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerScopeScopeIdPermissionsGetParam) ([]PolicyRepresentation, error)

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerScopeScopeIdPut)
	// PUT /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/scope/{scope-id}
	AdminRealmsRealmClientsClientUuidAuthzResourceServerScopeScopeIdPut(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerScopeScopeIdPutParam, req ScopeRepresentation) error

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerScopeScopeIdResourcesGet)
	// GET /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/scope/{scope-id}/resources
	AdminRealmsRealmClientsClientUuidAuthzResourceServerScopeScopeIdResourcesGet(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerScopeScopeIdResourcesGetParam) ([]ResourceRepresentation, error)

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerScopeSearchGet)
	// GET /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/scope/search
	AdminRealmsRealmClientsClientUuidAuthzResourceServerScopeSearchGet(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerScopeSearchGetParam) ([]ScopeRepresentation, error)

	// (operationId: AdminRealmsRealmClientsClientUuidAuthzResourceServerSettingsGet)
	// GET /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/settings
	AdminRealmsRealmClientsClientUuidAuthzResourceServerSettingsGet(ctx context.Context, param AdminRealmsRealmClientsClientUuidAuthzResourceServerSettingsGetParam) (ResourceServerRepresentation, error)
}
