// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
//
// Keycloak Admin REST API
//
// This is a REST API reference for the Keycloak Admin REST API.
//
// API version: 1.0

package idp

import (
	"context"
)

type AttackDetectionAPI interface {

	// Clear any user login failures for all users This can release temporary disabled users
	// (operationId: AdminRealmsRealmAttackDetectionBruteForceUsersDelete)
	// DELETE /admin/realms/{realm}/attack-detection/brute-force/users
	AdminRealmsRealmAttackDetectionBruteForceUsersDelete(ctx context.Context, param AdminRealmsRealmAttackDetectionBruteForceUsersDeleteParam) error

	// Clear any user login failures for the user This can release temporary disabled user
	// (operationId: AdminRealmsRealmAttackDetectionBruteForceUsersUserIdDelete)
	// DELETE /admin/realms/{realm}/attack-detection/brute-force/users/{userId}
	AdminRealmsRealmAttackDetectionBruteForceUsersUserIdDelete(ctx context.Context, param AdminRealmsRealmAttackDetectionBruteForceUsersUserIdDeleteParam) error

	// Get status of a username in brute force detection
	// (operationId: AdminRealmsRealmAttackDetectionBruteForceUsersUserIdGet)
	// GET /admin/realms/{realm}/attack-detection/brute-force/users/{userId}
	AdminRealmsRealmAttackDetectionBruteForceUsersUserIdGet(ctx context.Context, param AdminRealmsRealmAttackDetectionBruteForceUsersUserIdGetParam) (map[string]interface{}, error)
}
