// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
//
// Keycloak Admin REST API
//
// This is a REST API reference for the Keycloak Admin REST API.
//
// API version: 1.0

package idp

// (operationId: AdminRealmsRealmClientsInitialAccessGet)
type AdminRealmsRealmClientsInitialAccessGetParam struct {
	// realm name (not id!)
	Realm string `uri:"realm"`
}

// (operationId: AdminRealmsRealmClientsInitialAccessIdDelete)
type AdminRealmsRealmClientsInitialAccessIdDeleteParam struct {
	// realm name (not id!)
	Realm string `uri:"realm"`
	Id    string `uri:"id"`
}

// Create a new initial access token.
// (operationId: AdminRealmsRealmClientsInitialAccessPost)
type AdminRealmsRealmClientsInitialAccessPostParam struct {
	// realm name (not id!)
	Realm string `uri:"realm"`
}
