// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
//
// Keycloak Admin REST API
//
// This is a REST API reference for the Keycloak Admin REST API.
//
// API version: 1.0

package idp

// Update the client scope
// (model: ClientScopeRepresentation)

// Create a new client scope Client Scope’s name must be unique!
// (model: ClientScopeRepresentation)

// Update the client scope
// (model: ClientScopeRepresentation)

// Create a new client scope Client Scope’s name must be unique!
// (model: ClientScopeRepresentation)
