// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
//
// Keycloak Admin REST API
//
// This is a REST API reference for the Keycloak Admin REST API.
//
// API version: 1.0

package idp

// Import identity provider from JSON body
// Import identity provider from uploaded JSON file
type AdminRealmsRealmIdentityProviderImportConfigPostReq struct {
	Inner *interface{} `json:"inner,omitempty"`
}

// Return object stating whether client Authorization permissions have been initialized or not and a reference
// (model: ManagementPermissionReference)

// Update a mapper for the identity provider
// (model: IdentityProviderMapperRepresentation)

// Add a mapper to identity provider
// (model: IdentityProviderMapperRepresentation)

// Update the identity provider
// (model: IdentityProviderRepresentation)

// Create a new identity provider
// (model: IdentityProviderRepresentation)
