// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
//
// Keycloak Admin REST API
//
// This is a REST API reference for the Keycloak Admin REST API.
//
// API version: 1.0

package idp

// Adds the identity provider with the specified id to the organization
// Adds, or associates, an existing identity provider with the organization. If no identity provider is found, or if it is already associated with the organization, an error response is returned
type AdminRealmsRealmOrganizationsOrgIdIdentityProvidersPostReq struct {
}

// Adds the user with the specified id as a member of the organization
// Adds, or associates, an existing user with the organization. If no user is found, or if it is already associated with the organization, an error response is returned
type AdminRealmsRealmOrganizationsOrgIdMembersPostReq struct {
}

// Updates the organization
// (model: OrganizationRepresentation)

// Creates a new organization
// (model: OrganizationRepresentation)
