// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
//
// Keycloak Admin REST API
//
// This is a REST API reference for the Keycloak Admin REST API.
//
// API version: 1.0

package idp

// Create a new role for the realm or client
// (model: RoleRepresentation)

// Remove roles from the role's composite
type AdminRealmsRealmClientsClientUuidRolesRoleNameCompositesDeleteReq struct {
	Property RoleRepresentation `json:"Property,omitempty"`
}

// Add a composite to the role
type AdminRealmsRealmClientsClientUuidRolesRoleNameCompositesPostReq struct {
	Property RoleRepresentation `json:"Property,omitempty"`
}

// Return object stating whether role Authorization permissions have been initialized or not and a reference
// (model: ManagementPermissionReference)

// Update a role by name
// (model: RoleRepresentation)

// Create a new role for the realm or client
// (model: RoleRepresentation)

// Remove roles from the role's composite
type AdminRealmsRealmRolesRoleNameCompositesDeleteReq struct {
	Property RoleRepresentation `json:"Property,omitempty"`
}

// Add a composite to the role
type AdminRealmsRealmRolesRoleNameCompositesPostReq struct {
	Property RoleRepresentation `json:"Property,omitempty"`
}

// Return object stating whether role Authorization permissions have been initialized or not and a reference
// (model: ManagementPermissionReference)

// Update a role by name
// (model: RoleRepresentation)
