// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
//
// Keycloak Admin REST API
//
// This is a REST API reference for the Keycloak Admin REST API.
//
// API version: 1.0

package idp

import (
	"context"
)

type KeyAPI interface {

	// (operationId: AdminRealmsRealmKeysGet)
	// GET /admin/realms/{realm}/keys
	AdminRealmsRealmKeysGet(ctx context.Context, param AdminRealmsRealmKeysGetParam) (KeysMetadataRepresentation, error)
}
