// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
//
// Keycloak Admin REST API
//
// This is a REST API reference for the Keycloak Admin REST API.
//
// API version: 1.0

package idp

import (
	"context"
)

type ComponentAPI interface {

	// (operationId: AdminRealmsRealmComponentsGet)
	// GET /admin/realms/{realm}/components
	AdminRealmsRealmComponentsGet(ctx context.Context, param AdminRealmsRealmComponentsGetParam) ([]ComponentRepresentation, error)

	// (operationId: AdminRealmsRealmComponentsIdDelete)
	// DELETE /admin/realms/{realm}/components/{id}
	AdminRealmsRealmComponentsIdDelete(ctx context.Context, param AdminRealmsRealmComponentsIdDeleteParam) error

	// (operationId: AdminRealmsRealmComponentsIdGet)
	// GET /admin/realms/{realm}/components/{id}
	AdminRealmsRealmComponentsIdGet(ctx context.Context, param AdminRealmsRealmComponentsIdGetParam) (ComponentRepresentation, error)

	// (operationId: AdminRealmsRealmComponentsIdPut)
	// PUT /admin/realms/{realm}/components/{id}
	AdminRealmsRealmComponentsIdPut(ctx context.Context, param AdminRealmsRealmComponentsIdPutParam, req ComponentRepresentation) error

	// List of subcomponent types that are available to configure for a particular parent component.
	// (operationId: AdminRealmsRealmComponentsIdSubComponentTypesGet)
	// GET /admin/realms/{realm}/components/{id}/sub-component-types
	AdminRealmsRealmComponentsIdSubComponentTypesGet(ctx context.Context, param AdminRealmsRealmComponentsIdSubComponentTypesGetParam) ([]ComponentTypeRepresentation, error)

	// (operationId: AdminRealmsRealmComponentsPost)
	// POST /admin/realms/{realm}/components
	AdminRealmsRealmComponentsPost(ctx context.Context, param AdminRealmsRealmComponentsPostParam, req ComponentRepresentation) error
}
