image:
  pullPolicy: Always

env:
  - name: SPRING_PROFILES_ACTIVE
    value: command,dev
  - name: SPRING_CONFIG_IMPORT
    value: "configserver:http://config-server.cloud-config.svc.cluster.local:8888"

istio:
  enabled: true
  host: "customer-command.example.com"
