import StyleDictionary from "style-dictionary";
import type { Config, TransformedToken } from "style-dictionary/types";

function tokenValue(token: TransformedToken): string {
  return token.$value ?? token.value ?? String(token.original.$value);
}

StyleDictionary.registerFormat({
  name: "css/semantic-light",
  format: ({ dictionary }) => {
    const vars = dictionary.allTokens
      .map((token) => `  --${token.path.join("-")}: ${tokenValue(token)};`)
      .join("\n");
    return `:root {\n${vars}\n}\n`;
  },
});

StyleDictionary.registerFormat({
  name: "css/semantic-dark",
  format: ({ dictionary }) => {
    const vars = dictionary.allTokens
      .map((token) => `  --${token.path.join("-")}: ${tokenValue(token)};`)
      .join("\n");
    return `.dark {\n${vars}\n}\n`;
  },
});

StyleDictionary.registerFormat({
  name: "json/ai-flat",
  format: ({ dictionary }) => {
    const result: Record<
      string,
      { value: string; path: string[]; type?: string }
    > = {};
    dictionary.allTokens.forEach((token) => {
      const key = token.path.join(".");
      result[key] = {
        value: tokenValue(token),
        path: token.path,
        type: token.$type,
      };
    });
    return JSON.stringify(result, null, 2) + "\n";
  },
});

StyleDictionary.registerFormat({
  name: "ts/flat",
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens
      .map((token) => {
        const key = token.path.join("-");
        const value = tokenValue(token);
        return `  "${key}": "${value}",`;
      })
      .join("\n");
    return `// Auto-generated by Style Dictionary — do not edit manually
export const tokens = {
${entries}
} as const;

export type TokenName = keyof typeof tokens;
`;
  },
});

const transforms: string[] = [];

const config: Config = {
  log: { warnings: "disabled" },
  source: [
    "tokens/primitive/**/*.json",
    "tokens/semantic/color.json",
    "tokens/semantic/elevation.json",
  ],
  platforms: {
    "css-light": {
      transforms,
      buildPath: "build/css/",
      files: [
        {
          destination: "semantic-light.css",
          format: "css/semantic-light",
          filter: (token: TransformedToken) =>
            token.filePath.includes("semantic/color.json") ||
            token.filePath.includes("semantic/elevation.json"),
        },
        {
          destination: "primitives.css",
          format: "css/semantic-light",
          filter: (token: TransformedToken) =>
            token.filePath.includes("primitive/"),
        },
      ],
    },
    "json-resolved": {
      transforms,
      buildPath: "build/json/",
      files: [
        {
          destination: "resolved.json",
          format: "json/ai-flat",
        },
      ],
    },
    "ts-light": {
      transforms,
      buildPath: "build/ts/",
      files: [
        {
          destination: "light.ts",
          format: "ts/flat",
          filter: (token: TransformedToken) =>
            token.filePath.includes("semantic/color.json") ||
            token.filePath.includes("semantic/elevation.json") ||
            token.filePath.includes("primitive/radius.json"),
        },
      ],
    },
  },
};

export const darkConfig: Config = {
  log: { warnings: "disabled" },
  source: [
    "tokens/primitive/**/*.json",
    "tokens/semantic/color.dark.json",
    "tokens/semantic/elevation.json",
  ],
  platforms: {
    "css-dark": {
      transforms,
      buildPath: "build/css/",
      files: [
        {
          destination: "semantic-dark.css",
          format: "css/semantic-dark",
          filter: (token: TransformedToken) =>
            token.filePath.includes("semantic/color.dark.json"),
        },
      ],
    },
    "ts-dark": {
      transforms,
      buildPath: "build/ts/",
      files: [
        {
          destination: "dark.ts",
          format: "ts/flat",
          filter: (token: TransformedToken) =>
            token.filePath.includes("semantic/color.dark.json"),
        },
      ],
    },
  },
};

export default config;
