deploymentMode: SingleBinary

loki:
  image:
    registry: docker.io
    repository: grafana/loki
    tag: 3.5.1
  commonConfig:
    replication_factor: 1
  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    type: s3
    s3:
      endpoint: http://minio.default.svc.cluster.local:9000
      region: us-east-1
      insecure: true
  schemaConfig:
    configs:
      - from: "2025-01-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
  ruler:
    enable_api: true

lokiCanary:
  enabled: true
  resources:
    requests:
      cpu: 10m

gateway:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 10m

singleBinary:
  replicas: 1

minio:
  enabled: false

resultsCache:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 10m
chunksCache:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 10m

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
