// Generated by oapi-codegen-cli (1.0.0)

/**
 * Thrown by every WishlistApiClient method when the HTTP response is not 2xx.
 * Carries the status code and the response body parsed per the response's declared
 * content-type (JSON parsed object, text body for `text/*`, raw `Blob` for binary,
 * or `undefined` when the response had no body).
 */
export class ApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly statusText: string,
    public readonly body: unknown,
  ) {
    super(`HTTP ${status}: ${statusText}`);
    this.name = 'ApiError';
  }
}
import type { WishlistAddRequest } from '../model/wishlist-add-request';
import type { WishlistRemoveRequest } from '../model/wishlist-remove-request';
import type { WishlistResponse } from '../model/wishlist-response';

/**
 * Credentials for WishlistApi. One field per declared security scheme;
 * supply the value for the scheme(s) the operation you call requires.
 *   - `api-key` schemes carry the raw key (set as the configured header / query / cookie).
 *   - `http-bearer` / `oauth2` / `openid-connect` carry the token (sent as `Authorization: Bearer …`).
 *   - `http-basic` carries the already-base64-encoded `username:password` (sent as `Authorization: Basic …`).
 */
export interface WishlistApiCredentials {
  /** Scheme `BearerAuth` (`http-bearer`). */
  bearerAuth?: string;
}

/**
 * Wishlist API
 */
export interface WishlistApi {

  /**
   * Get customer's wishlist
   * Errors:
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  wishlistsGet(
    uid: string,
  ): Promise<WishlistResponse>;

  /**
   * Add books to customer's wishlist
   * Errors:
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  wishlistsAddBooks(
    uid: string,
    body: WishlistAddRequest,
  ): Promise<WishlistResponse>;

  /**
   * Remove books from customer's wishlist
   * Errors:
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  wishlistsRemoveBooks(
    uid: string,
    body: WishlistRemoveRequest,
  ): Promise<WishlistResponse>;
}

export class WishlistApiClient implements WishlistApi {
  private readonly baseUrl: string;
  private readonly credentials: WishlistApiCredentials;

  constructor(baseUrl: string, credentials: WishlistApiCredentials = {}) {
    this.baseUrl = baseUrl;
    this.credentials = credentials;
  }

  async wishlistsGet(
    uid: string,
  ): Promise<WishlistResponse> {
    const url = `${this.baseUrl}/api/v1/customers/${uid}/wishlist`;
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as WishlistResponse;
  }

  async wishlistsAddBooks(
    uid: string,
    body: WishlistAddRequest,
  ): Promise<WishlistResponse> {
    const url = `${this.baseUrl}/api/v1/customers/${uid}/wishlist/add`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
      body: JSON.stringify(body),
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as WishlistResponse;
  }

  async wishlistsRemoveBooks(
    uid: string,
    body: WishlistRemoveRequest,
  ): Promise<WishlistResponse> {
    const url = `${this.baseUrl}/api/v1/customers/${uid}/wishlist/remove`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
      body: JSON.stringify(body),
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as WishlistResponse;
  }
}
