apiVersion: v1
kind: Service
metadata:
  name: otel-forward-grpc
  namespace: opentelemetry
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/instance: opentelemetry.opentelemetry-cluster-stats
    app.kubernetes.io/managed-by: opentelemetry-operator
    app.kubernetes.io/part-of: opentelemetry
  ports:
    - appProtocol: grpc
      name: otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: otel-forward-http
  namespace: opentelemetry
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/instance: opentelemetry.opentelemetry-cluster-stats
    app.kubernetes.io/managed-by: opentelemetry-operator
    app.kubernetes.io/part-of: opentelemetry
  ports:
    - appProtocol: http
      name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: 4318
      nodePort: 30002
