{{- if .Values.rollout.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "identity.fullname" . }}-canary
  labels:
    {{- include "identity.labels" . | nindent 4 }}
    {{- if .Values.mesh }}
    {{- if .Values.mesh.waypoint }}
    istio.io/use-waypoint: {{ .Values.mesh.waypoint }}
    istio.io/ingress-use-waypoint: "true"
    {{- end }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      appProtocol: {{ .Values.service.appProtocol | default "http" }}
    {{- if .Values.service.grpc.enabled }}
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
      appProtocol: grpc
    {{- end }}
  selector:
    {{- include "identity.selectorLabels" . | nindent 4 }}
{{- end }}
