server:
  port: 8888
spring:
  application:
    name: config-server
    version: 1.0.0
  config:
    import: optional:file:/vault/secrets/git.properties
  cloud:
    config:
      server:
        git:
          uri: http://gitea-http.gitea.svc.cluster.local:3000/example-corp/cloud-config.git
          username: ${gitea.username}
          password: ${gitea.password}
          default-label: main
          clone-on-start: true
          search-paths: '{application}'
management:
  endpoints:
    web:
      exposure:
        include: health
