spring:
  application:
    name: payment
    version: 1.0.0
---
spring:
  config:
    activate:
      on-profile: local
    import: configserver:http://localhost:8888
  application:
    name: payment
    version: 1.0.0
