// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export enum PointChangeType {
  PointChangeTypeEarn = 'EARN',
  PointChangeTypeSpend = 'SPEND',
  PointChangeTypeAdjust = 'ADJUST',
  PointChangeTypeExpire = 'EXPIRE',
}

export const PointChangeTypeSchema = z.enum([
  'EARN',
  'SPEND',
  'ADJUST',
  'EXPIRE',
]);

/**
 * Parses an OpenAPI string value into a {@link PointChangeType}.
 * @throws {Error} when the value is not a known PointChangeType.
 */
export function parsePointChangeType(value: string): PointChangeType {
  if (isPointChangeType(value)) {
    return value;
  }
  throw new Error(`Invalid PointChangeType value: ${value}`);
}

/** Type guard returning whether `value` is a known {@link PointChangeType}. */
export function isPointChangeType(value: string): value is PointChangeType {
  return (Object.values(PointChangeType) as string[]).includes(value);
}
