// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export enum ShipmentStatus {
  ShipmentStatusUnknown = 'UNKNOWN',
  ShipmentStatusPlanned = 'PLANNED',
  ShipmentStatusDispatched = 'DISPATCHED',
  ShipmentStatusPickedUp = 'PICKED_UP',
  ShipmentStatusInTransit = 'IN_TRANSIT',
  ShipmentStatusOutForDelivery = 'OUT_FOR_DELIVERY',
  ShipmentStatusDelivered = 'DELIVERED',
  ShipmentStatusFailed = 'FAILED',
  ShipmentStatusCancelled = 'CANCELLED',
}

export const ShipmentStatusSchema = z.enum([
  'UNKNOWN',
  'PLANNED',
  'DISPATCHED',
  'PICKED_UP',
  'IN_TRANSIT',
  'OUT_FOR_DELIVERY',
  'DELIVERED',
  'FAILED',
  'CANCELLED',
]);

/**
 * Parses an OpenAPI string value into a {@link ShipmentStatus}.
 * @throws {Error} when the value is not a known ShipmentStatus.
 */
export function parseShipmentStatus(value: string): ShipmentStatus {
  if (isShipmentStatus(value)) {
    return value;
  }
  throw new Error(`Invalid ShipmentStatus value: ${value}`);
}

/** Type guard returning whether `value` is a known {@link ShipmentStatus}. */
export function isShipmentStatus(value: string): value is ShipmentStatus {
  return (Object.values(ShipmentStatus) as string[]).includes(value);
}
