// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: modules/user/v1/user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthRole int32

const (
	AuthRole_UNKNOWN AuthRole = 0
	AuthRole_SYSTEM  AuthRole = 1
	AuthRole_MANAGE  AuthRole = 2
	AuthRole_PROFILE AuthRole = 3
	AuthRole_ORDER   AuthRole = 4
	AuthRole_VIEW    AuthRole = 5
)

// Enum value maps for AuthRole.
var (
	AuthRole_name = map[int32]string{
		0: "UNKNOWN",
		1: "SYSTEM",
		2: "MANAGE",
		3: "PROFILE",
		4: "ORDER",
		5: "VIEW",
	}
	AuthRole_value = map[string]int32{
		"UNKNOWN": 0,
		"SYSTEM":  1,
		"MANAGE":  2,
		"PROFILE": 3,
		"ORDER":   4,
		"VIEW":    5,
	}
)

func (x AuthRole) Enum() *AuthRole {
	p := new(AuthRole)
	*p = x
	return p
}

func (x AuthRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthRole) Descriptor() protoreflect.EnumDescriptor {
	return file_modules_user_v1_user_proto_enumTypes[0].Descriptor()
}

func (AuthRole) Type() protoreflect.EnumType {
	return &file_modules_user_v1_user_proto_enumTypes[0]
}

func (x AuthRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthRole.Descriptor instead.
func (AuthRole) EnumDescriptor() ([]byte, []int) {
	return file_modules_user_v1_user_proto_rawDescGZIP(), []int{0}
}

type UserFindAllProtoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *string                `protobuf:"bytes,1,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Phone         *string                `protobuf:"bytes,3,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Filter        *QueryFilter           `protobuf:"bytes,4,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFindAllProtoReq) Reset() {
	*x = UserFindAllProtoReq{}
	mi := &file_modules_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFindAllProtoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFindAllProtoReq) ProtoMessage() {}

func (x *UserFindAllProtoReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFindAllProtoReq.ProtoReflect.Descriptor instead.
func (*UserFindAllProtoReq) Descriptor() ([]byte, []int) {
	return file_modules_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserFindAllProtoReq) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UserFindAllProtoReq) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UserFindAllProtoReq) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UserFindAllProtoReq) GetFilter() *QueryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type QueryFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sort          string                 `protobuf:"bytes,1,opt,name=sort,proto3" json:"sort,omitempty"`
	Order         string                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFilter) Reset() {
	*x = QueryFilter{}
	mi := &file_modules_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFilter) ProtoMessage() {}

func (x *QueryFilter) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFilter.ProtoReflect.Descriptor instead.
func (*QueryFilter) Descriptor() ([]byte, []int) {
	return file_modules_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *QueryFilter) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *QueryFilter) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *QueryFilter) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryFilter) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type UserFindAllProtoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Items         []*UserFindProtoResp   `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFindAllProtoResp) Reset() {
	*x = UserFindAllProtoResp{}
	mi := &file_modules_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFindAllProtoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFindAllProtoResp) ProtoMessage() {}

func (x *UserFindAllProtoResp) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFindAllProtoResp.ProtoReflect.Descriptor instead.
func (*UserFindAllProtoResp) Descriptor() ([]byte, []int) {
	return file_modules_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserFindAllProtoResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *UserFindAllProtoResp) GetItems() []*UserFindProtoResp {
	if x != nil {
		return x.Items
	}
	return nil
}

type UserFindProtoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFindProtoReq) Reset() {
	*x = UserFindProtoReq{}
	mi := &file_modules_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFindProtoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFindProtoReq) ProtoMessage() {}

func (x *UserFindProtoReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFindProtoReq.ProtoReflect.Descriptor instead.
func (*UserFindProtoReq) Descriptor() ([]byte, []int) {
	return file_modules_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserFindProtoReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserFindProtoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone         *string                `protobuf:"bytes,5,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Roles         []AuthRole             `protobuf:"varint,6,rep,packed,name=roles,proto3,enum=user.v1.AuthRole" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFindProtoResp) Reset() {
	*x = UserFindProtoResp{}
	mi := &file_modules_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFindProtoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFindProtoResp) ProtoMessage() {}

func (x *UserFindProtoResp) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFindProtoResp.ProtoReflect.Descriptor instead.
func (*UserFindProtoResp) Descriptor() ([]byte, []int) {
	return file_modules_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserFindProtoResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserFindProtoResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserFindProtoResp) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserFindProtoResp) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserFindProtoResp) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UserFindProtoResp) GetRoles() []AuthRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

type UserUpdateProtoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone         *string                `protobuf:"bytes,5,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Roles         []AuthRole             `protobuf:"varint,6,rep,packed,name=roles,proto3,enum=user.v1.AuthRole" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateProtoReq) Reset() {
	*x = UserUpdateProtoReq{}
	mi := &file_modules_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateProtoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateProtoReq) ProtoMessage() {}

func (x *UserUpdateProtoReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateProtoReq.ProtoReflect.Descriptor instead.
func (*UserUpdateProtoReq) Descriptor() ([]byte, []int) {
	return file_modules_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserUpdateProtoReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserUpdateProtoReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserUpdateProtoReq) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserUpdateProtoReq) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserUpdateProtoReq) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UserUpdateProtoReq) GetRoles() []AuthRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

type UserUpdateProtoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone         *string                `protobuf:"bytes,5,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Roles         []AuthRole             `protobuf:"varint,6,rep,packed,name=roles,proto3,enum=user.v1.AuthRole" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateProtoResp) Reset() {
	*x = UserUpdateProtoResp{}
	mi := &file_modules_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateProtoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateProtoResp) ProtoMessage() {}

func (x *UserUpdateProtoResp) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateProtoResp.ProtoReflect.Descriptor instead.
func (*UserUpdateProtoResp) Descriptor() ([]byte, []int) {
	return file_modules_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserUpdateProtoResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserUpdateProtoResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserUpdateProtoResp) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserUpdateProtoResp) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserUpdateProtoResp) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UserUpdateProtoResp) GetRoles() []AuthRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

type UserDeleteProtoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleteProtoReq) Reset() {
	*x = UserDeleteProtoReq{}
	mi := &file_modules_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleteProtoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleteProtoReq) ProtoMessage() {}

func (x *UserDeleteProtoReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleteProtoReq.ProtoReflect.Descriptor instead.
func (*UserDeleteProtoReq) Descriptor() ([]byte, []int) {
	return file_modules_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserDeleteProtoReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserDeleteProtoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleteProtoResp) Reset() {
	*x = UserDeleteProtoResp{}
	mi := &file_modules_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleteProtoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleteProtoResp) ProtoMessage() {}

func (x *UserDeleteProtoResp) ProtoReflect() protoreflect.Message {
	mi := &file_modules_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleteProtoResp.ProtoReflect.Descriptor instead.
func (*UserDeleteProtoResp) Descriptor() ([]byte, []int) {
	return file_modules_user_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserDeleteProtoResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_modules_user_v1_user_proto protoreflect.FileDescriptor

const file_modules_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x1amodules/user/v1/user.proto\x12\auser.v1\"\xbf\x01\n" +
	"\x13UserFindAllProtoReq\x12\x19\n" +
	"\x05email\x18\x01 \x01(\tH\x00R\x05email\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x03 \x01(\tH\x02R\x05phone\x88\x01\x01\x121\n" +
	"\x06filter\x18\x04 \x01(\v2\x14.user.v1.QueryFilterH\x03R\x06filter\x88\x01\x01B\b\n" +
	"\x06_emailB\a\n" +
	"\x05_nameB\b\n" +
	"\x06_phoneB\t\n" +
	"\a_filter\"e\n" +
	"\vQueryFilter\x12\x12\n" +
	"\x04sort\x18\x01 \x01(\tR\x04sort\x12\x14\n" +
	"\x05order\x18\x02 \x01(\tR\x05order\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"^\n" +
	"\x14UserFindAllProtoResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x120\n" +
	"\x05items\x18\x02 \x03(\v2\x1a.user.v1.UserFindProtoRespR\x05items\"\"\n" +
	"\x10UserFindProtoReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc3\x01\n" +
	"\x11UserFindProtoResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x19\n" +
	"\x05phone\x18\x05 \x01(\tH\x00R\x05phone\x88\x01\x01\x12'\n" +
	"\x05roles\x18\x06 \x03(\x0e2\x11.user.v1.AuthRoleR\x05rolesB\b\n" +
	"\x06_phone\"\xc4\x01\n" +
	"\x12UserUpdateProtoReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x19\n" +
	"\x05phone\x18\x05 \x01(\tH\x00R\x05phone\x88\x01\x01\x12'\n" +
	"\x05roles\x18\x06 \x03(\x0e2\x11.user.v1.AuthRoleR\x05rolesB\b\n" +
	"\x06_phone\"\xc5\x01\n" +
	"\x13UserUpdateProtoResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x19\n" +
	"\x05phone\x18\x05 \x01(\tH\x00R\x05phone\x88\x01\x01\x12'\n" +
	"\x05roles\x18\x06 \x03(\x0e2\x11.user.v1.AuthRoleR\x05rolesB\b\n" +
	"\x06_phone\"$\n" +
	"\x12UserDeleteProtoReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13UserDeleteProtoResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id*Q\n" +
	"\bAuthRole\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x01\x12\n" +
	"\n" +
	"\x06MANAGE\x10\x02\x12\v\n" +
	"\aPROFILE\x10\x03\x12\t\n" +
	"\x05ORDER\x10\x04\x12\b\n" +
	"\x04VIEW\x10\x052\xb7\x02\n" +
	"\vUserService\x12M\n" +
	"\fFindAllUsers\x12\x1c.user.v1.UserFindAllProtoReq\x1a\x1d.user.v1.UserFindAllProtoResp\"\x00\x12C\n" +
	"\bFindUser\x12\x19.user.v1.UserFindProtoReq\x1a\x1a.user.v1.UserFindProtoResp\"\x00\x12I\n" +
	"\n" +
	"UpdateUser\x12\x1b.user.v1.UserUpdateProtoReq\x1a\x1c.user.v1.UserUpdateProtoResp\"\x00\x12I\n" +
	"\n" +
	"DeleteUser\x12\x1b.user.v1.UserDeleteProtoReq\x1a\x1c.user.v1.UserDeleteProtoResp\"\x00B\x8e\x01\n" +
	"9com.codejsha.bookstore.service.application.port.pb.userpbB\tUserProtoP\x01Z\tpb/userpb\xa2\x02\x03UXX\xaa\x02\aUser.V1\xca\x02\aUser\\V1\xe2\x02\x13User\\V1\\GPBMetadata\xea\x02\bUser::V1b\x06proto3"

var (
	file_modules_user_v1_user_proto_rawDescOnce sync.Once
	file_modules_user_v1_user_proto_rawDescData []byte
)

func file_modules_user_v1_user_proto_rawDescGZIP() []byte {
	file_modules_user_v1_user_proto_rawDescOnce.Do(func() {
		file_modules_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_user_v1_user_proto_rawDesc), len(file_modules_user_v1_user_proto_rawDesc)))
	})
	return file_modules_user_v1_user_proto_rawDescData
}

var file_modules_user_v1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_modules_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_modules_user_v1_user_proto_goTypes = []any{
	(AuthRole)(0),                // 0: user.v1.AuthRole
	(*UserFindAllProtoReq)(nil),  // 1: user.v1.UserFindAllProtoReq
	(*QueryFilter)(nil),          // 2: user.v1.QueryFilter
	(*UserFindAllProtoResp)(nil), // 3: user.v1.UserFindAllProtoResp
	(*UserFindProtoReq)(nil),     // 4: user.v1.UserFindProtoReq
	(*UserFindProtoResp)(nil),    // 5: user.v1.UserFindProtoResp
	(*UserUpdateProtoReq)(nil),   // 6: user.v1.UserUpdateProtoReq
	(*UserUpdateProtoResp)(nil),  // 7: user.v1.UserUpdateProtoResp
	(*UserDeleteProtoReq)(nil),   // 8: user.v1.UserDeleteProtoReq
	(*UserDeleteProtoResp)(nil),  // 9: user.v1.UserDeleteProtoResp
}
var file_modules_user_v1_user_proto_depIdxs = []int32{
	2, // 0: user.v1.UserFindAllProtoReq.filter:type_name -> user.v1.QueryFilter
	5, // 1: user.v1.UserFindAllProtoResp.items:type_name -> user.v1.UserFindProtoResp
	0, // 2: user.v1.UserFindProtoResp.roles:type_name -> user.v1.AuthRole
	0, // 3: user.v1.UserUpdateProtoReq.roles:type_name -> user.v1.AuthRole
	0, // 4: user.v1.UserUpdateProtoResp.roles:type_name -> user.v1.AuthRole
	1, // 5: user.v1.UserService.FindAllUsers:input_type -> user.v1.UserFindAllProtoReq
	4, // 6: user.v1.UserService.FindUser:input_type -> user.v1.UserFindProtoReq
	6, // 7: user.v1.UserService.UpdateUser:input_type -> user.v1.UserUpdateProtoReq
	8, // 8: user.v1.UserService.DeleteUser:input_type -> user.v1.UserDeleteProtoReq
	3, // 9: user.v1.UserService.FindAllUsers:output_type -> user.v1.UserFindAllProtoResp
	5, // 10: user.v1.UserService.FindUser:output_type -> user.v1.UserFindProtoResp
	7, // 11: user.v1.UserService.UpdateUser:output_type -> user.v1.UserUpdateProtoResp
	9, // 12: user.v1.UserService.DeleteUser:output_type -> user.v1.UserDeleteProtoResp
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_modules_user_v1_user_proto_init() }
func file_modules_user_v1_user_proto_init() {
	if File_modules_user_v1_user_proto != nil {
		return
	}
	file_modules_user_v1_user_proto_msgTypes[0].OneofWrappers = []any{}
	file_modules_user_v1_user_proto_msgTypes[4].OneofWrappers = []any{}
	file_modules_user_v1_user_proto_msgTypes[5].OneofWrappers = []any{}
	file_modules_user_v1_user_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_user_v1_user_proto_rawDesc), len(file_modules_user_v1_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_user_v1_user_proto_goTypes,
		DependencyIndexes: file_modules_user_v1_user_proto_depIdxs,
		EnumInfos:         file_modules_user_v1_user_proto_enumTypes,
		MessageInfos:      file_modules_user_v1_user_proto_msgTypes,
	}.Build()
	File_modules_user_v1_user_proto = out.File
	file_modules_user_v1_user_proto_goTypes = nil
	file_modules_user_v1_user_proto_depIdxs = nil
}
