// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: modules/category/v1/category.proto

package categorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CategoryFindAllProtoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *QueryFilter           `protobuf:"bytes,1,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryFindAllProtoReq) Reset() {
	*x = CategoryFindAllProtoReq{}
	mi := &file_modules_category_v1_category_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryFindAllProtoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryFindAllProtoReq) ProtoMessage() {}

func (x *CategoryFindAllProtoReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_category_v1_category_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryFindAllProtoReq.ProtoReflect.Descriptor instead.
func (*CategoryFindAllProtoReq) Descriptor() ([]byte, []int) {
	return file_modules_category_v1_category_proto_rawDescGZIP(), []int{0}
}

func (x *CategoryFindAllProtoReq) GetFilter() *QueryFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type QueryFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sort          string                 `protobuf:"bytes,1,opt,name=sort,proto3" json:"sort,omitempty"`
	Order         string                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFilter) Reset() {
	*x = QueryFilter{}
	mi := &file_modules_category_v1_category_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFilter) ProtoMessage() {}

func (x *QueryFilter) ProtoReflect() protoreflect.Message {
	mi := &file_modules_category_v1_category_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFilter.ProtoReflect.Descriptor instead.
func (*QueryFilter) Descriptor() ([]byte, []int) {
	return file_modules_category_v1_category_proto_rawDescGZIP(), []int{1}
}

func (x *QueryFilter) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *QueryFilter) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type CategoryFindAllProtoResp struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Total         int64                    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Items         []*CategoryFindProtoResp `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryFindAllProtoResp) Reset() {
	*x = CategoryFindAllProtoResp{}
	mi := &file_modules_category_v1_category_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryFindAllProtoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryFindAllProtoResp) ProtoMessage() {}

func (x *CategoryFindAllProtoResp) ProtoReflect() protoreflect.Message {
	mi := &file_modules_category_v1_category_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryFindAllProtoResp.ProtoReflect.Descriptor instead.
func (*CategoryFindAllProtoResp) Descriptor() ([]byte, []int) {
	return file_modules_category_v1_category_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryFindAllProtoResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CategoryFindAllProtoResp) GetItems() []*CategoryFindProtoResp {
	if x != nil {
		return x.Items
	}
	return nil
}

type CategoryFindProtoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryFindProtoResp) Reset() {
	*x = CategoryFindProtoResp{}
	mi := &file_modules_category_v1_category_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryFindProtoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryFindProtoResp) ProtoMessage() {}

func (x *CategoryFindProtoResp) ProtoReflect() protoreflect.Message {
	mi := &file_modules_category_v1_category_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryFindProtoResp.ProtoReflect.Descriptor instead.
func (*CategoryFindProtoResp) Descriptor() ([]byte, []int) {
	return file_modules_category_v1_category_proto_rawDescGZIP(), []int{3}
}

func (x *CategoryFindProtoResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryFindProtoResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_modules_category_v1_category_proto protoreflect.FileDescriptor

const file_modules_category_v1_category_proto_rawDesc = "" +
	"\n" +
	"\"modules/category/v1/category.proto\x12\vcategory.v1\"[\n" +
	"\x17CategoryFindAllProtoReq\x125\n" +
	"\x06filter\x18\x01 \x01(\v2\x18.category.v1.QueryFilterH\x00R\x06filter\x88\x01\x01B\t\n" +
	"\a_filter\"7\n" +
	"\vQueryFilter\x12\x12\n" +
	"\x04sort\x18\x01 \x01(\tR\x04sort\x12\x14\n" +
	"\x05order\x18\x02 \x01(\tR\x05order\"j\n" +
	"\x18CategoryFindAllProtoResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x128\n" +
	"\x05items\x18\x02 \x03(\v2\".category.v1.CategoryFindProtoRespR\x05items\";\n" +
	"\x15CategoryFindProtoResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2u\n" +
	"\x0fCategoryService\x12b\n" +
	"\x11FindAllCategories\x12$.category.v1.CategoryFindAllProtoReq\x1a%.category.v1.CategoryFindAllProtoResp\"\x00B\xaa\x01\n" +
	"=com.codejsha.bookstore.service.application.port.pb.categorypbB\rCategoryProtoP\x01Z\rpb/categorypb\xa2\x02\x03CXX\xaa\x02\vCategory.V1\xca\x02\vCategory\\V1\xe2\x02\x17Category\\V1\\GPBMetadata\xea\x02\fCategory::V1b\x06proto3"

var (
	file_modules_category_v1_category_proto_rawDescOnce sync.Once
	file_modules_category_v1_category_proto_rawDescData []byte
)

func file_modules_category_v1_category_proto_rawDescGZIP() []byte {
	file_modules_category_v1_category_proto_rawDescOnce.Do(func() {
		file_modules_category_v1_category_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_modules_category_v1_category_proto_rawDesc), len(file_modules_category_v1_category_proto_rawDesc)))
	})
	return file_modules_category_v1_category_proto_rawDescData
}

var file_modules_category_v1_category_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_modules_category_v1_category_proto_goTypes = []any{
	(*CategoryFindAllProtoReq)(nil),  // 0: category.v1.CategoryFindAllProtoReq
	(*QueryFilter)(nil),              // 1: category.v1.QueryFilter
	(*CategoryFindAllProtoResp)(nil), // 2: category.v1.CategoryFindAllProtoResp
	(*CategoryFindProtoResp)(nil),    // 3: category.v1.CategoryFindProtoResp
}
var file_modules_category_v1_category_proto_depIdxs = []int32{
	1, // 0: category.v1.CategoryFindAllProtoReq.filter:type_name -> category.v1.QueryFilter
	3, // 1: category.v1.CategoryFindAllProtoResp.items:type_name -> category.v1.CategoryFindProtoResp
	0, // 2: category.v1.CategoryService.FindAllCategories:input_type -> category.v1.CategoryFindAllProtoReq
	2, // 3: category.v1.CategoryService.FindAllCategories:output_type -> category.v1.CategoryFindAllProtoResp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_modules_category_v1_category_proto_init() }
func file_modules_category_v1_category_proto_init() {
	if File_modules_category_v1_category_proto != nil {
		return
	}
	file_modules_category_v1_category_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_modules_category_v1_category_proto_rawDesc), len(file_modules_category_v1_category_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_category_v1_category_proto_goTypes,
		DependencyIndexes: file_modules_category_v1_category_proto_depIdxs,
		MessageInfos:      file_modules_category_v1_category_proto_msgTypes,
	}.Build()
	File_modules_category_v1_category_proto = out.File
	file_modules_category_v1_category_proto_goTypes = nil
	file_modules_category_v1_category_proto_depIdxs = nil
}
