// Generated by oapi-codegen-cli (1.0.0)

/**
 * Thrown by every BalanceApiClient method when the HTTP response is not 2xx.
 * Carries the status code and the response body parsed per the response's declared
 * content-type (JSON parsed object, text body for `text/*`, raw `Blob` for binary,
 * or `undefined` when the response had no body).
 */
export class ApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly statusText: string,
    public readonly body: unknown,
  ) {
    super(`HTTP ${status}: ${statusText}`);
    this.name = 'ApiError';
  }
}
import type { BalanceFindAllResponse } from '../model/balance-find-all-response';

export interface Pageable {
  page?: number;
  size?: number;
  sort?: string;
}

/**
 * Credentials for BalanceApi. One field per declared security scheme;
 * supply the value for the scheme(s) the operation you call requires.
 *   - `api-key` schemes carry the raw key (set as the configured header / query / cookie).
 *   - `http-bearer` / `oauth2` / `openid-connect` carry the token (sent as `Authorization: Bearer …`).
 *   - `http-basic` carries the already-base64-encoded `username:password` (sent as `Authorization: Basic …`).
 */
export interface BalanceApiCredentials {
  /** Scheme `BearerAuth` (`http-bearer`). */
  bearerAuth?: string;
}

/**
 * Balance API
 */
export interface BalanceApi {

  /**
   * Find stock balance report (수불 현황)
   */
  balanceGetAll(
    editionUid: string | undefined,
    warehouseUid: string | undefined,
    yearMonth: string | undefined,
    pageable: Pageable,
  ): Promise<BalanceFindAllResponse>;
}

export class BalanceApiClient implements BalanceApi {
  private readonly baseUrl: string;
  private readonly credentials: BalanceApiCredentials;

  constructor(baseUrl: string, credentials: BalanceApiCredentials = {}) {
    this.baseUrl = baseUrl;
    this.credentials = credentials;
  }

  async balanceGetAll(
    editionUid: string | undefined,
    warehouseUid: string | undefined,
    yearMonth: string | undefined,
    pageable: Pageable,
  ): Promise<BalanceFindAllResponse> {
    const params = new URLSearchParams();
    if (editionUid !== undefined) params.append('edition_uid', Array.isArray(editionUid) ? (editionUid as readonly unknown[]).join(',') : String(editionUid));
    if (warehouseUid !== undefined) params.append('warehouse_uid', Array.isArray(warehouseUid) ? (warehouseUid as readonly unknown[]).join(',') : String(warehouseUid));
    if (yearMonth !== undefined) params.append('year_month', Array.isArray(yearMonth) ? (yearMonth as readonly unknown[]).join(',') : String(yearMonth));
    if (pageable.page !== undefined) params.append('page', String(pageable.page));
    if (pageable.size !== undefined) params.append('size', String(pageable.size));
    if (pageable.sort !== undefined) params.append('sort', pageable.sort);
    const query = params.toString();
    const url = `${this.baseUrl}/api/v1/balance${query ? `?${query}` : ''}`;
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as BalanceFindAllResponse;
  }
}
