// Generated by oapi-codegen-cli (1.0.0)

/**
 * Thrown by every TransferApiClient method when the HTTP response is not 2xx.
 * Carries the status code and the response body parsed per the response's declared
 * content-type (JSON parsed object, text body for `text/*`, raw `Blob` for binary,
 * or `undefined` when the response had no body).
 */
export class ApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly statusText: string,
    public readonly body: unknown,
  ) {
    super(`HTTP ${status}: ${statusText}`);
    this.name = 'ApiError';
  }
}
import type { TransferCreateRequest } from '../model/transfer-create-request';
import type { TransferFindAllResponse } from '../model/transfer-find-all-response';
import type { TransferFindResponse } from '../model/transfer-find-response';
import { TransferStatus } from '../constant/transfer-status';

export interface Pageable {
  page?: number;
  size?: number;
  sort?: string;
}

/**
 * Credentials for TransferApi. One field per declared security scheme;
 * supply the value for the scheme(s) the operation you call requires.
 *   - `api-key` schemes carry the raw key (set as the configured header / query / cookie).
 *   - `http-bearer` / `oauth2` / `openid-connect` carry the token (sent as `Authorization: Bearer …`).
 *   - `http-basic` carries the already-base64-encoded `username:password` (sent as `Authorization: Basic …`).
 */
export interface TransferApiCredentials {
  /** Scheme `BearerAuth` (`http-bearer`). */
  bearerAuth?: string;
}

/**
 * Transfer API
 */
export interface TransferApi {

  /**
   * Find all stock transfers
   */
  transfersGetAll(
    editionUid: string | undefined,
    sourceWarehouseUid: string | undefined,
    targetWarehouseUid: string | undefined,
    status: TransferStatus | undefined,
    pageable: Pageable,
  ): Promise<TransferFindAllResponse>;

  /**
   * Create stock transfer between warehouses
   */
  transfersCreate(
    body: TransferCreateRequest,
  ): Promise<TransferFindResponse>;

  /**
   * Find stock transfer
   * Errors:
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  transfersRead(
    uid: string,
  ): Promise<TransferFindResponse>;

  /**
   * Cancel stock transfer
   * Errors:
   * 400 (BadRequestError) — The server could not understand the request due to invalid syntax.
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  transfersCancel(
    uid: string,
  ): Promise<TransferFindResponse>;

  /**
   * Complete stock transfer
   * Errors:
   * 400 (BadRequestError) — The server could not understand the request due to invalid syntax.
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  transfersComplete(
    uid: string,
  ): Promise<TransferFindResponse>;
}

export class TransferApiClient implements TransferApi {
  private readonly baseUrl: string;
  private readonly credentials: TransferApiCredentials;

  constructor(baseUrl: string, credentials: TransferApiCredentials = {}) {
    this.baseUrl = baseUrl;
    this.credentials = credentials;
  }

  async transfersGetAll(
    editionUid: string | undefined,
    sourceWarehouseUid: string | undefined,
    targetWarehouseUid: string | undefined,
    status: TransferStatus | undefined,
    pageable: Pageable,
  ): Promise<TransferFindAllResponse> {
    const params = new URLSearchParams();
    if (editionUid !== undefined) params.append('edition_uid', Array.isArray(editionUid) ? (editionUid as readonly unknown[]).join(',') : String(editionUid));
    if (sourceWarehouseUid !== undefined) params.append('source_warehouse_uid', Array.isArray(sourceWarehouseUid) ? (sourceWarehouseUid as readonly unknown[]).join(',') : String(sourceWarehouseUid));
    if (targetWarehouseUid !== undefined) params.append('target_warehouse_uid', Array.isArray(targetWarehouseUid) ? (targetWarehouseUid as readonly unknown[]).join(',') : String(targetWarehouseUid));
    if (status !== undefined) params.append('status', Array.isArray(status) ? (status as readonly unknown[]).join(',') : String(status));
    if (pageable.page !== undefined) params.append('page', String(pageable.page));
    if (pageable.size !== undefined) params.append('size', String(pageable.size));
    if (pageable.sort !== undefined) params.append('sort', pageable.sort);
    const query = params.toString();
    const url = `${this.baseUrl}/api/v1/transfers${query ? `?${query}` : ''}`;
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as TransferFindAllResponse;
  }

  async transfersCreate(
    body: TransferCreateRequest,
  ): Promise<TransferFindResponse> {
    const url = `${this.baseUrl}/api/v1/transfers`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
      body: JSON.stringify(body),
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as TransferFindResponse;
  }

  async transfersRead(
    uid: string,
  ): Promise<TransferFindResponse> {
    const url = `${this.baseUrl}/api/v1/transfers/${uid}`;
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as TransferFindResponse;
  }

  async transfersCancel(
    uid: string,
  ): Promise<TransferFindResponse> {
    const url = `${this.baseUrl}/api/v1/transfers/${uid}/cancel`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as TransferFindResponse;
  }

  async transfersComplete(
    uid: string,
  ): Promise<TransferFindResponse> {
    const url = `${this.baseUrl}/api/v1/transfers/${uid}/complete`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as TransferFindResponse;
  }
}
