image:
  pullPolicy: Always

env:
  - name: APP_CONFIG_PROFILE
    value: dev
  - name: APP_CONFIG_SERVER
    value: "configserver:http://config-server.cloud-config.svc.cluster.local:8888"
  - name: PYROSCOPE_APPLICATION_NAME
    value: catalog
  - name: PYROSCOPE_SERVER_ADDRESS
    value: "http://alloy-agent.grafana.svc.cluster.local:9095"
  - name: PYROSCOPE_PROFILING_ENABLED
    value: "true"
  - name: PYROSCOPE_LABELS
    value: "namespace=bookstore"

mesh:
  waypoint: "bookstore-waypoint"

gatewayApi:
  enabled: true
  host: "catalog-api.example.com"
  storefront:
    enabled: true
    host: "bookstore.example.com"
