env:
  - name: SPRING_PROFILES_ACTIVE
    value: command,local
  - name: SPRING_CONFIG_IMPORT
    value: "configserver:http://cloud-config.example.com"

istio:
  enabled: true
  host: "order-command.example.com"
