// Code generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0); DO NOT EDIT.
//
// Customer service API
//
// Customer service API of Bookstore microservices
//
// API version: 0.1.0
// Contact: admin@example.com

package openapi

// Find customer's point
// Find customer's point (operationId: ApiV1CustomersIdPointGet)
type PointFindAllWebParam struct {
	// User ID
	Id string `uri:"id"`
}

// Update customer's point
// Update customer's point (operationId: ApiV1CustomersIdPointPut)
type PointUpdateWebParam struct {
	// User ID
	Id string `uri:"id"`
}
