// Code generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0); DO NOT EDIT.
//
// Customer service API
//
// Customer service API of Bookstore microservices
//
// API version: 0.1.0
// Contact: admin@example.com

package openapi

// Find all customers
// Find all customers (operationId: ApiV1CustomersGet)
type CustomerFindAllWebParam struct {
	Email *string `form:"email,omitempty"`
	Name  *string `form:"name,omitempty"`
	Phone *string `form:"phone,omitempty"`
	// Field to sort by
	Sort string `form:"sort,omitempty"`
	// Sorting order
	Order string `form:"order,omitempty"`
	// Number of items to return
	Limit int32 `form:"limit,omitempty"`
	// The number of items to skip
	Offset int32 `form:"offset,omitempty"`
}

// Delete user
// Delete user (operationId: ApiV1CustomersIdDelete)
type CustomerDeleteWebParam struct {
	// User ID
	Id string `uri:"id"`
}

// Find customer
// Find customer (operationId: ApiV1CustomersIdGet)
type CustomerFindWebParam struct {
	// User ID
	Id string `uri:"id"`
}

// Update customer
// Update customer (operationId: ApiV1CustomersIdPut)
type CustomerUpdateWebParam struct {
	// User ID
	Id string `uri:"id"`
}
