// Code generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0); DO NOT EDIT.
//
// Customer service API
//
// Customer service API of Bookstore microservices
//
// API version: 0.1.0
// Contact: admin@example.com

package openapi

import (
	"github.com/gin-gonic/gin"
)

type PointAPI interface {

	// ApiV1CustomersIdPointGet Get /api/v1/customers/:id/point
	// Find customer's point
	ApiV1CustomersIdPointGet(c *gin.Context)

	// ApiV1CustomersIdPointPut Put /api/v1/customers/:id/point
	// Update customer's point
	ApiV1CustomersIdPointPut(c *gin.Context)
}
