// Code generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0); DO NOT EDIT.
//
// Customer service API
//
// Customer service API of Bookstore microservices
//
// API version: 0.1.0
// Contact: admin@example.com

package openapi

// Find customer's payments
// Find customer's payments (operationId: ApiV1CustomersIdPaymentsGet)
type PaymentFindAllWebParam struct {
	// User ID
	Id string `uri:"id"`
	// Order ID
	OrderId *int64 `form:"order_id,omitempty"`
	// Field to sort by
	Sort string `form:"sort,omitempty"`
	// Sorting order
	Order string `form:"order,omitempty"`
	// Number of items to return
	Limit int32 `form:"limit,omitempty"`
	// The number of items to skip
	Offset int32 `form:"offset,omitempty"`
}

// Find customer's payments
// Find customer's payments (operationId: ApiV1CustomersIdPaymentsPaymentIdGet)
type PaymentFindWebParam struct {
	// User ID
	Id        string `uri:"id"`
	PaymentId int64  `uri:"paymentId"`
}
