// Code generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0); DO NOT EDIT.
//
// Customer service API
//
// Customer service API of Bookstore microservices
//
// API version: 0.1.0
// Contact: admin@example.com

package openapi

import (
	"github.com/gin-gonic/gin"
)

type WishlistAPI interface {

	// ApiV1CustomersIdWishlistDelete Delete /api/v1/customers/:id/wishlist
	// Delete user's wishlist
	ApiV1CustomersIdWishlistDelete(c *gin.Context)

	// ApiV1CustomersIdWishlistGet Get /api/v1/customers/:id/wishlist
	// Find user's wishlist
	ApiV1CustomersIdWishlistGet(c *gin.Context)

	// ApiV1CustomersIdWishlistPost Post /api/v1/customers/:id/wishlist
	// Create user's wishlist
	ApiV1CustomersIdWishlistPost(c *gin.Context)

	// ApiV1CustomersIdWishlistPut Put /api/v1/customers/:id/wishlist
	// Update user's wishlist
	ApiV1CustomersIdWishlistPut(c *gin.Context)
}
