// Code generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0); DO NOT EDIT.
//
// Customer service API
//
// Customer service API of Bookstore microservices
//
// API version: 0.1.0
// Contact: admin@example.com

package openapi

type WishlistFindWebResp struct {
	BookIds []int64 `json:"book_ids,omitempty"`
}
