deployment:
  custom_secrets:
    - name: grafana-admin-credentials
      mount: /kiali-override-secrets/grafana-admin-credentials
      optional: true

server:
  web_fqdn: kiali.example.com
  web_schema: https
  web_port: "443"
  web_root: /kiali

auth:
  strategy: openid
  openid:
    client_id: kiali
    issuer_uri: "https://keycloak.example.com/realms/bookstore"
    username_claim: preferred_username
    scopes:
      - openid
      - profile
      - email
    disable_rbac: true

external_services:
  prometheus:
    url: "http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090"

  grafana:
    enabled: true
    internal_url: "http://grafana.grafana.svc.cluster.local"
    external_url: "https://grafana.example.com"
    datasource_uid: "prometheus"
    dashboards:
      - name: "Istio Mesh Dashboard"
      - name: "Istio Service Dashboard"
      - name: "Istio Workload Dashboard"
      - name: "Istio Performance Dashboard"
      - name: "Istio Control Plane Dashboard"
      - name: "Istio Wasm Extension Dashboard"
    auth:
      type: "basic"
