global:
  enabled: true
  tlsDisable: true

injector:
  enabled: true
  replicas: 1

  agentImage:
    repository: "hashicorp/vault"

  agentDefaults:
    cpuLimit: 500m
    cpuRequest: 10m
    memLimit: 128Mi
    memRequest: 64Mi

  authPath: "auth/kubernetes"

  logLevel: debug
  logFormat: json

  resources:
    requests:
      memory: 256Mi
      cpu: 10m
    limits:
      memory: 256Mi
      cpu: 250m

  annotations:
    sidecar.istio.io/proxyCPU: "10m"

server:
  enabled: true
  image:
    repository: "hashicorp/vault"

  logLevel: debug
  logFormat: json

  resources:
    requests:
      memory: 256Mi
      cpu: 10m
    limits:
      memory: 256Mi
      cpu: 250m

  authDelegator:
    enabled: true

  # extraEnvironmentVars:
  #   VAULT_CACERT: /vault/userconfig/vault-ha-tls/ca.crt
  #   VAULT_TLSCERT: /vault/userconfig/vault-ha-tls/tls.crt
  #   VAULT_TLSKEY: /vault/userconfig/vault-ha-tls/tls.key
  # volumes:
  #   - name: userconfig-vault-ha-tls
  #     secret:
  #       defaultMode: 420
  #       secretName: vault-ha-tls
  # volumeMounts:
  #   - mountPath: /vault/userconfig/vault-ha-tls
  #     name: userconfig-vault-ha-tls
  #     readOnly: true

  affinity: {}
  # affinity: |
  #   podAntiAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       - labelSelector:
  #           matchLabels:
  #             app.kubernetes.io/name: {{ template "vault.name" . }}
  #             app.kubernetes.io/instance: "{{ .Release.Name }}"
  #             component: server
  #         topologyKey: kubernetes.io/hostname

  annotations:
    sidecar.istio.io/proxyCPU: "10m"

  dataStorage:
    enabled: true
    size: 10Gi
  auditStorage:
    enabled: true
    size: 10Gi

  service:
    enabled: true
    active:
      enabled: true
    standby:
      enabled: true
    publishNotReadyAddresses: true

  dev:
    enabled: false

  standalone:
    enabled: false

  ha:
    enabled: true
    replicas: 3

    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          # tls_cert_file = "/vault/userconfig/vault-ha-tls/tls.crt"
          # tls_key_file  = "/vault/userconfig/vault-ha-tls/tls.key"
          # tls_client_ca_file = "/vault/userconfig/vault-ha-tls/ca.crt"
        }
        cluster_name = "vault-integrated-storage"
        storage "raft" {
          path    = "/vault/data/"
        }
        service_registration "kubernetes" {}
        disable_mlock = true

ui:
  enabled: true
  publishNotReadyAddresses: true

csi:
  enabled: false

serverTelemetry:
  serviceMonitor:
    enabled: false
  prometheusRules:
    enabled: false
