variable "namespace" {
  description = "Namespace name"
  type        = string
}

variable "postgres_services" {
  description = "Postgres services"
  type        = list(string)
}

variable "postgres_credentials" {
  description = "Per-service credentials list: [{service, username, password}]. Generated by random_password in parent module."
  type = list(object({
    service  = string
    username = string
    password = string
  }))
  sensitive = true
}

variable "debezium_username" {
  description = "Debezium Postgres replication role name"
  type        = string
}

variable "debezium_password" {
  description = "Debezium Postgres role password (generated by random_password in parent module)"
  type        = string
  sensitive   = true
}

variable "postgres_service_accounts" {
  description = "Postgres service accounts bound to the Vault kubernetes-auth role"
  type        = list(string)
}
