// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export enum AuthRole {
  AuthRoleUnknown = 'UNKNOWN',
  AuthRoleAdmin = 'ADMIN',
  AuthRoleSystem = 'SYSTEM',
  AuthRoleManage = 'MANAGE',
  AuthRoleProfile = 'PROFILE',
  AuthRoleOrder = 'ORDER',
  AuthRoleView = 'VIEW',
}

export const AuthRoleSchema = z.enum([
  'UNKNOWN',
  'ADMIN',
  'SYSTEM',
  'MANAGE',
  'PROFILE',
  'ORDER',
  'VIEW',
]);

/**
 * Parses an OpenAPI string value into a {@link AuthRole}.
 * @throws {Error} when the value is not a known AuthRole.
 */
export function parseAuthRole(value: string): AuthRole {
  if (isAuthRole(value)) {
    return value;
  }
  throw new Error(`Invalid AuthRole value: ${value}`);
}

/** Type guard returning whether `value` is a known {@link AuthRole}. */
export function isAuthRole(value: string): value is AuthRole {
  return (Object.values(AuthRole) as string[]).includes(value);
}
