// Generated by oapi-codegen-cli (1.0.0)

import { z } from 'zod';

export enum UserStatus {
  UserStatusActive = 'ACTIVE',
  UserStatusSuspended = 'SUSPENDED',
  UserStatusDeactivated = 'DEACTIVATED',
}

export const UserStatusSchema = z.enum([
  'ACTIVE',
  'SUSPENDED',
  'DEACTIVATED',
]);

/**
 * Parses an OpenAPI string value into a {@link UserStatus}.
 * @throws {Error} when the value is not a known UserStatus.
 */
export function parseUserStatus(value: string): UserStatus {
  if (isUserStatus(value)) {
    return value;
  }
  throw new Error(`Invalid UserStatus value: ${value}`);
}

/** Type guard returning whether `value` is a known {@link UserStatus}. */
export function isUserStatus(value: string): value is UserStatus {
  return (Object.values(UserStatus) as string[]).includes(value);
}
