{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "customer.fullname" . }}-vs
  labels:
    {{- include "customer.labels" . | nindent 4 }}
  {{- with .Values.istio.virtualService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hosts:
    - {{ .Values.istio.host }}
  gateways:
    - {{ include "customer.fullname" . }}-gw
  http:
    - match:
        - port: 80
      route:
        - destination:
            host: {{ include "customer.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port }}
  {{- if and .Values.istio.tls.enabled .Values.service.https.enabled }}
  tls:
    - match:
        - port: 443
          sniHosts:
            - {{ .Values.istio.host }}
      route:
        - destination:
            host: {{ include "customer.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.https.port }}
  {{- end}}
{{- end }}
