{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{ include "inventory.fullname" . }}-dr
  labels:
    {{- include "inventory.labels" . | nindent 4 }}
  {{- with .Values.istio.destinationRule.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ include "inventory.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  {{- with .Values.istio.trafficPolicy }}
  trafficPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
