from enum import StrEnum


class NotificationType(StrEnum):
    ORDER_PLACED = "ORDER_PLACED"
    ORDER_CONFIRMED = "ORDER_CONFIRMED"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    SHIPMENT_DISPATCHED = "SHIPMENT_DISPATCHED"
    SHIPMENT_DELIVERED = "SHIPMENT_DELIVERED"
    ACCOUNT_CREATED = "ACCOUNT_CREATED"
    PASSWORD_RESET = "PASSWORD_RESET"
