// Generated by oapi-codegen-cli (1.0.0)

/**
 * Thrown by every CustomerApiClient method when the HTTP response is not 2xx.
 * Carries the status code and the response body parsed per the response's declared
 * content-type (JSON parsed object, text body for `text/*`, raw `Blob` for binary,
 * or `undefined` when the response had no body).
 */
export class ApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly statusText: string,
    public readonly body: unknown,
  ) {
    super(`HTTP ${status}: ${statusText}`);
    this.name = 'ApiError';
  }
}
import type { CustomerCreateRequest } from '../model/customer-create-request';
import type { CustomerFindAllResponse } from '../model/customer-find-all-response';
import type { CustomerFindResponse } from '../model/customer-find-response';
import type { CustomerUpdateRequest } from '../model/customer-update-request';
import type { CustomerUpdateResponse } from '../model/customer-update-response';

export interface Pageable {
  page?: number;
  size?: number;
  sort?: string;
}

/**
 * Credentials for CustomerApi. One field per declared security scheme;
 * supply the value for the scheme(s) the operation you call requires.
 *   - `api-key` schemes carry the raw key (set as the configured header / query / cookie).
 *   - `http-bearer` / `oauth2` / `openid-connect` carry the token (sent as `Authorization: Bearer …`).
 *   - `http-basic` carries the already-base64-encoded `username:password` (sent as `Authorization: Basic …`).
 */
export interface CustomerApiCredentials {
  /** Scheme `BearerAuth` (`http-bearer`). */
  bearerAuth?: string;
}

/**
 * Customer API
 */
export interface CustomerApi {

  /**
   * Find all customers
   */
  customersGetAll(
    customerId: string | undefined,
    email: string | undefined,
    pageable: Pageable,
  ): Promise<CustomerFindAllResponse>;

  /**
   * Create customer
   * Errors:
   * 400 (BadRequestError) — The server could not understand the request due to invalid syntax.
   * 409 (ConflictError) — The request conflicts with the current state of the server.
   *
   * Response headers (on success; read via `response.headers` — not part of the return value):
   * - `location`: string — Location of the created resource
   */
  customersCreate(
    body: CustomerCreateRequest,
  ): Promise<void>;

  /**
   * Find customer
   * Errors:
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  customersRead(
    uid: string,
  ): Promise<CustomerFindResponse>;

  /**
   * Update customer
   * Errors:
   * 400 (BadRequestError) — The server could not understand the request due to invalid syntax.
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  customersUpdate(
    uid: string,
    body: CustomerUpdateRequest,
  ): Promise<CustomerUpdateResponse>;

  /**
   * Delete customer
   * Errors:
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  customersDelete(
    uid: string,
  ): Promise<void>;
}

export class CustomerApiClient implements CustomerApi {
  private readonly baseUrl: string;
  private readonly credentials: CustomerApiCredentials;

  constructor(baseUrl: string, credentials: CustomerApiCredentials = {}) {
    this.baseUrl = baseUrl;
    this.credentials = credentials;
  }

  async customersGetAll(
    customerId: string | undefined,
    email: string | undefined,
    pageable: Pageable,
  ): Promise<CustomerFindAllResponse> {
    const params = new URLSearchParams();
    if (customerId !== undefined) params.append('customer_id', Array.isArray(customerId) ? (customerId as readonly unknown[]).join(',') : String(customerId));
    if (email !== undefined) params.append('email', Array.isArray(email) ? (email as readonly unknown[]).join(',') : String(email));
    if (pageable.page !== undefined) params.append('page', String(pageable.page));
    if (pageable.size !== undefined) params.append('size', String(pageable.size));
    if (pageable.sort !== undefined) params.append('sort', pageable.sort);
    const query = params.toString();
    const url = `${this.baseUrl}/api/v1/customers${query ? `?${query}` : ''}`;
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as CustomerFindAllResponse;
  }

  async customersCreate(
    body: CustomerCreateRequest,
  ): Promise<void> {
    const url = `${this.baseUrl}/api/v1/customers`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
      body: JSON.stringify(body),
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
  }

  async customersRead(
    uid: string,
  ): Promise<CustomerFindResponse> {
    const url = `${this.baseUrl}/api/v1/customers/${uid}`;
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as CustomerFindResponse;
  }

  async customersUpdate(
    uid: string,
    body: CustomerUpdateRequest,
  ): Promise<CustomerUpdateResponse> {
    const url = `${this.baseUrl}/api/v1/customers/${uid}`;
    const response = await fetch(url, {
      method: 'PUT',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
      body: JSON.stringify(body),
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as CustomerUpdateResponse;
  }

  async customersDelete(
    uid: string,
  ): Promise<void> {
    const url = `${this.baseUrl}/api/v1/customers/${uid}`;
    const response = await fetch(url, {
      method: 'DELETE',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
  }
}
