// Generated by oapi-codegen-cli (1.0.0)

/**
 * Thrown by every PaymentAttemptApiClient method when the HTTP response is not 2xx.
 * Carries the status code and the response body parsed per the response's declared
 * content-type (JSON parsed object, text body for `text/*`, raw `Blob` for binary,
 * or `undefined` when the response had no body).
 */
export class ApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly statusText: string,
    public readonly body: unknown,
  ) {
    super(`HTTP ${status}: ${statusText}`);
    this.name = 'ApiError';
  }
}
import type { PaymentAttemptFindAllResponse } from '../model/payment-attempt-find-all-response';
import type { PaymentAttemptFindResponse } from '../model/payment-attempt-find-response';
import { PaymentStatus } from '../constant/payment-status';

export interface Pageable {
  page?: number;
  size?: number;
  sort?: string;
}

/**
 * Credentials for PaymentAttemptApi. One field per declared security scheme;
 * supply the value for the scheme(s) the operation you call requires.
 *   - `api-key` schemes carry the raw key (set as the configured header / query / cookie).
 *   - `http-bearer` / `oauth2` / `openid-connect` carry the token (sent as `Authorization: Bearer …`).
 *   - `http-basic` carries the already-base64-encoded `username:password` (sent as `Authorization: Basic …`).
 */
export interface PaymentAttemptApiCredentials {
  /** Scheme `BearerAuth` (`http-bearer`). */
  bearerAuth?: string;
}

/**
 * PaymentAttempt API
 */
export interface PaymentAttemptApi {

  /**
   * Find all attempts of a payment
   * Errors:
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  paymentAttemptsGetAll(
    paymentUid: string,
    status: PaymentStatus | undefined,
    pageable: Pageable,
  ): Promise<PaymentAttemptFindAllResponse>;

  /**
   * Find attempt of a payment
   * Errors:
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  paymentAttemptsRead(
    paymentUid: string,
    uid: string,
  ): Promise<PaymentAttemptFindResponse>;
}

export class PaymentAttemptApiClient implements PaymentAttemptApi {
  private readonly baseUrl: string;
  private readonly credentials: PaymentAttemptApiCredentials;

  constructor(baseUrl: string, credentials: PaymentAttemptApiCredentials = {}) {
    this.baseUrl = baseUrl;
    this.credentials = credentials;
  }

  async paymentAttemptsGetAll(
    paymentUid: string,
    status: PaymentStatus | undefined,
    pageable: Pageable,
  ): Promise<PaymentAttemptFindAllResponse> {
    const params = new URLSearchParams();
    if (status !== undefined) params.append('status', Array.isArray(status) ? (status as readonly unknown[]).join(',') : String(status));
    if (pageable.page !== undefined) params.append('page', String(pageable.page));
    if (pageable.size !== undefined) params.append('size', String(pageable.size));
    if (pageable.sort !== undefined) params.append('sort', pageable.sort);
    const query = params.toString();
    const url = `${this.baseUrl}/api/v1/payments/${paymentUid}/attempts${query ? `?${query}` : ''}`;
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as PaymentAttemptFindAllResponse;
  }

  async paymentAttemptsRead(
    paymentUid: string,
    uid: string,
  ): Promise<PaymentAttemptFindResponse> {
    const url = `${this.baseUrl}/api/v1/payments/${paymentUid}/attempts/${uid}`;
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as PaymentAttemptFindResponse;
  }
}
