// Generated by oapi-codegen-cli (1.0.0)

/**
 * Thrown by every RefundApiClient method when the HTTP response is not 2xx.
 * Carries the status code and the response body parsed per the response's declared
 * content-type (JSON parsed object, text body for `text/*`, raw `Blob` for binary,
 * or `undefined` when the response had no body).
 */
export class ApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly statusText: string,
    public readonly body: unknown,
  ) {
    super(`HTTP ${status}: ${statusText}`);
    this.name = 'ApiError';
  }
}
import type { RefundCreateRequest } from '../model/refund-create-request';
import type { RefundFindAllResponse } from '../model/refund-find-all-response';
import type { RefundFindResponse } from '../model/refund-find-response';
import { RefundStatus } from '../constant/refund-status';

export interface Pageable {
  page?: number;
  size?: number;
  sort?: string;
}

/**
 * Credentials for RefundApi. One field per declared security scheme;
 * supply the value for the scheme(s) the operation you call requires.
 *   - `api-key` schemes carry the raw key (set as the configured header / query / cookie).
 *   - `http-bearer` / `oauth2` / `openid-connect` carry the token (sent as `Authorization: Bearer …`).
 *   - `http-basic` carries the already-base64-encoded `username:password` (sent as `Authorization: Basic …`).
 */
export interface RefundApiCredentials {
  /** Scheme `BearerAuth` (`http-bearer`). */
  bearerAuth?: string;
}

/**
 * Refund API
 */
export interface RefundApi {

  /**
   * Find all refunds
   */
  refundsGetAll(
    paymentId: string | undefined,
    status: RefundStatus | undefined,
    pageable: Pageable,
  ): Promise<RefundFindAllResponse>;

  /**
   * Create refund
   *
   * Response headers (on success; read via `response.headers` — not part of the return value):
   * - `location`: string — Location of the created resource
   */
  refundsCreate(
    body: RefundCreateRequest,
  ): Promise<void>;

  /**
   * Find refund
   * Errors:
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  refundsRead(
    uid: string,
  ): Promise<RefundFindResponse>;
}

export class RefundApiClient implements RefundApi {
  private readonly baseUrl: string;
  private readonly credentials: RefundApiCredentials;

  constructor(baseUrl: string, credentials: RefundApiCredentials = {}) {
    this.baseUrl = baseUrl;
    this.credentials = credentials;
  }

  async refundsGetAll(
    paymentId: string | undefined,
    status: RefundStatus | undefined,
    pageable: Pageable,
  ): Promise<RefundFindAllResponse> {
    const params = new URLSearchParams();
    if (paymentId !== undefined) params.append('payment_id', Array.isArray(paymentId) ? (paymentId as readonly unknown[]).join(',') : String(paymentId));
    if (status !== undefined) params.append('status', Array.isArray(status) ? (status as readonly unknown[]).join(',') : String(status));
    if (pageable.page !== undefined) params.append('page', String(pageable.page));
    if (pageable.size !== undefined) params.append('size', String(pageable.size));
    if (pageable.sort !== undefined) params.append('sort', pageable.sort);
    const query = params.toString();
    const url = `${this.baseUrl}/api/v1/refunds${query ? `?${query}` : ''}`;
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as RefundFindAllResponse;
  }

  async refundsCreate(
    body: RefundCreateRequest,
  ): Promise<void> {
    const url = `${this.baseUrl}/api/v1/refunds`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
      body: JSON.stringify(body),
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
  }

  async refundsRead(
    uid: string,
  ): Promise<RefundFindResponse> {
    const url = `${this.baseUrl}/api/v1/refunds/${uid}`;
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as RefundFindResponse;
  }
}
