variable "nexus_url" {
  description = "Nexus external base URL (Gateway API HTTPRoute host)"
  type        = string
}

variable "vault_url" {
  description = "Vault URL"
  type        = string
}

variable "vault_auth_role" {
  type = string
}

variable "vault_k8s_jwt" {
  description = "Short-lived Kubernetes ServiceAccount token for Vault kubernetes-auth login"
  type        = string
  sensitive   = true
}

variable "proxy_name" {
  description = "npm proxy repository name"
  type        = string
  default     = "npm-proxy"
}

variable "hosted_name" {
  description = "npm hosted repository name (private @bookstore/* packages)"
  type        = string
  default     = "npm-hosted"
}

variable "group_name" {
  description = "npm group repository name (hosted + proxy)"
  type        = string
  default     = "npm-group"
}

variable "blob_store_name" {
  description = "Blob store backing the npm repositories. The chart provisions only the built-in `default` blob store."
  type        = string
  default     = "default"
}

variable "npm_registry_remote_url" {
  description = "Upstream npm registry the proxy caches"
  type        = string
  default     = "https://registry.npmjs.org"
}

variable "hosted_write_policy" {
  description = "Hosted repo deployment policy. ALLOW permits version overwrites during iteration; prod should consider ALLOW_ONCE to make published versions immutable."
  type        = string
  default     = "ALLOW"

  validation {
    condition     = contains(["ALLOW", "ALLOW_ONCE", "DENY"], var.hosted_write_policy)
    error_message = "hosted_write_policy must be one of: ALLOW, ALLOW_ONCE, DENY."
  }
}

variable "publisher_username" {
  description = "CI/dev publish user. Password is generated by this unit and written to vault at kv/nexus/publisher."
  type        = string
  default     = "bookstore-publisher"
}

variable "publisher_role_id" {
  description = "Security role id granting view/add/edit on the hosted npm repository"
  type        = string
  default     = "npm-publisher"
}

variable "maven_proxy_name" {
  description = "maven proxy repository name (caches Maven Central)"
  type        = string
  default     = "maven-proxy"
}

variable "maven_hosted_name" {
  description = "maven hosted repository name (private com.codejsha.platform artifacts)"
  type        = string
  default     = "maven-hosted"
}

variable "maven_group_name" {
  description = "maven group repository name — the single URL the Gradle builds resolve against"
  type        = string
  default     = "maven-group"
}

variable "maven_registry_remote_url" {
  description = "Upstream maven registry the proxy caches"
  type        = string
  default     = "https://repo1.maven.org/maven2/"
}

variable "maven_plugins_proxy_name" {
  description = "maven proxy repository name for the Gradle Plugin Portal"
  type        = string
  default     = "gradle-plugins-proxy"
}

variable "maven_plugins_remote_url" {
  description = "Gradle Plugin Portal m2 URL the proxy caches"
  type        = string
  default     = "https://plugins.gradle.org/m2/"
}

variable "pypi_proxy_name" {
  description = "pypi proxy repository name (caches pypi.org)"
  type        = string
  default     = "pypi-proxy"
}

variable "pypi_group_name" {
  description = "pypi group repository name — the single URL uv/pip resolve against"
  type        = string
  default     = "pypi-group"
}

variable "pypi_registry_remote_url" {
  description = "Upstream PyPI registry the proxy caches"
  type        = string
  default     = "https://pypi.org"
}

variable "raw_hosted_name" {
  description = "raw hosted repository name — vendored third-party API specs (codegen inputs, not source)"
  type        = string
  default     = "raw-hosted"
}

variable "go_proxy_name" {
  description = "go proxy repository name (caches proxy.golang.org)"
  type        = string
  default     = "go-proxy"
}

variable "go_group_name" {
  description = "go group repository name — the single URL the Go builds' GOPROXY points at"
  type        = string
  default     = "go-group"
}

variable "go_registry_remote_url" {
  description = "Upstream Go module proxy the proxy caches"
  type        = string
  default     = "https://proxy.golang.org"
}

variable "namespace" {
  description = "Namespace Nexus runs in — only used to spell the in-cluster docker connector Service name"
  type        = string
  default     = "nexus"
}

variable "docker_proxy_name" {
  description = "docker proxy repository name — pull-through cache for the OCI artifacts CI fetches from ghcr.io (trivy vuln + java DBs)"
  type        = string
  default     = "docker-proxy"
}

variable "docker_registry_remote_url" {
  description = "Upstream OCI registry the docker proxy caches"
  type        = string
  default     = "https://ghcr.io"
}

variable "docker_http_port" {
  description = <<-EOT
    Dedicated HTTP connector port for the docker proxy. Must match the port in
    the chart's nexus.docker.registries list (infra/service/nexus), and the port
    its nexus-docker Service publishes.
  EOT
  type        = number
  default     = 5000
}

variable "docker_service_name" {
  description = <<-EOT
    In-cluster Service fronting the docker connector. The chart's own Service is
    named <fullname>-docker-<port>, which callers cannot spell without knowing
    the port, so infra/service/nexus adds this stable alias alongside it.
  EOT
  type        = string
  default     = "nexus-docker"
}
