// Code generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0); DO NOT EDIT.
//
// Identity service API
//
// Identity service API of Bookstore microservices
//
// API version: 0.1.0
// Contact: admin@example.com

package openapi

// Sign-out user (Logout)
// Sign-out user (operationId: ApiV1UsersSignoutPost)
type SignOutWebParam struct {
	// Refresh token
	XRefreshToken string `header:"X-Refresh-Token"`
}

// Exchange user token
// Exchange user token (operationId: ApiV1UsersTokensExchangePost)
type TokenExchangeWebParam struct {
	// Refresh token
	XRefreshToken string `header:"X-Refresh-Token"`
}
