// Code generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0); DO NOT EDIT.
//
// Identity service API
//
// Identity service API of Bookstore microservices
//
// API version: 0.1.0
// Contact: admin@example.com

package openapi

type User struct {
	Id string `json:"id,omitempty"`

	Email string `json:"email,omitempty"`

	FirstName string `json:"first_name,omitempty"`

	LastName string `json:"last_name,omitempty"`

	Phone *string `json:"phone,omitempty"`
}
