// Code generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0); DO NOT EDIT.
//
// Identity service API
//
// Identity service API of Bookstore microservices
//
// API version: 0.1.0
// Contact: admin@example.com

package openapi

type TokenExchangeWebResp struct {
	AccessToken string `json:"access_token"`
}
