// Generated by oapi-codegen-cli (1.0.0)

/**
 * Thrown by every RiskApiClient method when the HTTP response is not 2xx.
 * Carries the status code and the response body parsed per the response's declared
 * content-type (JSON parsed object, text body for `text/*`, raw `Blob` for binary,
 * or `undefined` when the response had no body).
 */
export class ApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly statusText: string,
    public readonly body: unknown,
  ) {
    super(`HTTP ${status}: ${statusText}`);
    this.name = 'ApiError';
  }
}
import type { RiskEntryListResponse } from '../model/risk-entry-list-response';
import type { RiskEntryResponse } from '../model/risk-entry-response';
import type { RiskFlagRequest } from '../model/risk-flag-request';

/**
 * Credentials for RiskApi. One field per declared security scheme;
 * supply the value for the scheme(s) the operation you call requires.
 *   - `api-key` schemes carry the raw key (set as the configured header / query / cookie).
 *   - `http-bearer` / `oauth2` / `openid-connect` carry the token (sent as `Authorization: Bearer …`).
 *   - `http-basic` carries the already-base64-encoded `username:password` (sent as `Authorization: Basic …`).
 */
export interface RiskApiCredentials {
  /** Scheme `BearerAuth` (`http-bearer`). */
  bearerAuth?: string;
}

/**
 * Risk API
 */
export interface RiskApi {

  /**
   * List all currently flagged principals
   */
  riskGetAll(
  ): Promise<RiskEntryListResponse>;

  /**
   * Flag a principal (restrict = deny writes, block = deny all)
   * Errors:
   * 400 (BadRequestError) — The server could not understand the request due to invalid syntax.
   */
  riskFlagPrincipal(
    uid: string,
    body: RiskFlagRequest,
  ): Promise<RiskEntryResponse>;

  /**
   * Remove a principal's risk flag
   */
  riskUnflagPrincipal(
    uid: string,
  ): Promise<void>;
}

export class RiskApiClient implements RiskApi {
  private readonly baseUrl: string;
  private readonly credentials: RiskApiCredentials;

  constructor(baseUrl: string, credentials: RiskApiCredentials = {}) {
    this.baseUrl = baseUrl;
    this.credentials = credentials;
  }

  async riskGetAll(
  ): Promise<RiskEntryListResponse> {
    const url = `${this.baseUrl}/api/v1/risk`;
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as RiskEntryListResponse;
  }

  async riskFlagPrincipal(
    uid: string,
    body: RiskFlagRequest,
  ): Promise<RiskEntryResponse> {
    const url = `${this.baseUrl}/api/v1/risk/${uid}`;
    const response = await fetch(url, {
      method: 'PUT',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
      body: JSON.stringify(body),
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as RiskEntryResponse;
  }

  async riskUnflagPrincipal(
    uid: string,
  ): Promise<void> {
    const url = `${this.baseUrl}/api/v1/risk/${uid}`;
    const response = await fetch(url, {
      method: 'DELETE',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
  }
}
