// Generated by oapi-codegen-cli (1.0.0)

/**
 * Thrown by every UserApiClient method when the HTTP response is not 2xx.
 * Carries the status code and the response body parsed per the response's declared
 * content-type (JSON parsed object, text body for `text/*`, raw `Blob` for binary,
 * or `undefined` when the response had no body).
 */
export class ApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly statusText: string,
    public readonly body: unknown,
  ) {
    super(`HTTP ${status}: ${statusText}`);
    this.name = 'ApiError';
  }
}
import type { UserFindAllResponse } from '../model/user-find-all-response';
import type { UserFindResponse } from '../model/user-find-response';
import type { UserRegisterRequest } from '../model/user-register-request';
import type { UserRolesRequest } from '../model/user-roles-request';
import type { UserUpdateRequest } from '../model/user-update-request';
import { UserStatus } from '../constant/user-status';

export interface Pageable {
  page?: number;
  size?: number;
  sort?: string;
}

/**
 * Credentials for UserApi. One field per declared security scheme;
 * supply the value for the scheme(s) the operation you call requires.
 *   - `api-key` schemes carry the raw key (set as the configured header / query / cookie).
 *   - `http-bearer` / `oauth2` / `openid-connect` carry the token (sent as `Authorization: Bearer …`).
 *   - `http-basic` carries the already-base64-encoded `username:password` (sent as `Authorization: Basic …`).
 */
export interface UserApiCredentials {
  /** Scheme `BearerAuth` (`http-bearer`). */
  bearerAuth?: string;
}

/**
 * User API
 */
export interface UserApi {

  /**
   * Find all users
   */
  usersGetAll(
    email: string | undefined,
    name: string | undefined,
    phone: string | undefined,
    status: UserStatus | undefined,
    pageable: Pageable,
  ): Promise<UserFindAllResponse>;

  /**
   * Register a new user (creates in Keycloak + local DB)
   * Errors:
   * 400 (BadRequestError) — The server could not understand the request due to invalid syntax.
   */
  usersRegister(
    body: UserRegisterRequest,
  ): Promise<UserFindResponse>;

  /**
   * Find user by email
   * Errors:
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  usersReadByEmail(
    email: string,
  ): Promise<UserFindResponse>;

  /**
   * Sync user data from Keycloak to local DB
   * Errors:
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  usersSyncFromIdp(
    idpUid: string,
  ): Promise<UserFindResponse>;

  /**
   * Find user by uid
   * Errors:
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  usersRead(
    uid: string,
  ): Promise<UserFindResponse>;

  /**
   * Update user profile
   * Errors:
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  usersUpdate(
    uid: string,
    body: UserUpdateRequest,
  ): Promise<UserFindResponse>;

  /**
   * Deactivate user account (delete in Keycloak, soft-delete locally)
   * Errors:
   * 400 (BadRequestError) — The server could not understand the request due to invalid syntax.
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  usersDeactivate(
    uid: string,
  ): Promise<UserFindResponse>;

  /**
   * Reactivate suspended user account (enable in Keycloak)
   * Errors:
   * 400 (BadRequestError) — The server could not understand the request due to invalid syntax.
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  usersReactivate(
    uid: string,
  ): Promise<UserFindResponse>;

  /**
   * Update user roles
   * Errors:
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  usersUpdateRoles(
    uid: string,
    body: UserRolesRequest,
  ): Promise<UserFindResponse>;

  /**
   * Suspend user account (disable in Keycloak)
   * Errors:
   * 400 (BadRequestError) — The server could not understand the request due to invalid syntax.
   * 404 (NotFoundError) — The server cannot find the requested resource.
   */
  usersSuspend(
    uid: string,
  ): Promise<UserFindResponse>;
}

export class UserApiClient implements UserApi {
  private readonly baseUrl: string;
  private readonly credentials: UserApiCredentials;

  constructor(baseUrl: string, credentials: UserApiCredentials = {}) {
    this.baseUrl = baseUrl;
    this.credentials = credentials;
  }

  async usersGetAll(
    email: string | undefined,
    name: string | undefined,
    phone: string | undefined,
    status: UserStatus | undefined,
    pageable: Pageable,
  ): Promise<UserFindAllResponse> {
    const params = new URLSearchParams();
    if (email !== undefined) params.append('email', Array.isArray(email) ? (email as readonly unknown[]).join(',') : String(email));
    if (name !== undefined) params.append('name', Array.isArray(name) ? (name as readonly unknown[]).join(',') : String(name));
    if (phone !== undefined) params.append('phone', Array.isArray(phone) ? (phone as readonly unknown[]).join(',') : String(phone));
    if (status !== undefined) params.append('status', Array.isArray(status) ? (status as readonly unknown[]).join(',') : String(status));
    if (pageable.page !== undefined) params.append('page', String(pageable.page));
    if (pageable.size !== undefined) params.append('size', String(pageable.size));
    if (pageable.sort !== undefined) params.append('sort', pageable.sort);
    const query = params.toString();
    const url = `${this.baseUrl}/api/v1/users${query ? `?${query}` : ''}`;
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as UserFindAllResponse;
  }

  async usersRegister(
    body: UserRegisterRequest,
  ): Promise<UserFindResponse> {
    const url = `${this.baseUrl}/api/v1/users`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
      body: JSON.stringify(body),
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as UserFindResponse;
  }

  async usersReadByEmail(
    email: string,
  ): Promise<UserFindResponse> {
    const url = `${this.baseUrl}/api/v1/users/by-email/${email}`;
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as UserFindResponse;
  }

  async usersSyncFromIdp(
    idpUid: string,
  ): Promise<UserFindResponse> {
    const url = `${this.baseUrl}/api/v1/users/sync/${idpUid}`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as UserFindResponse;
  }

  async usersRead(
    uid: string,
  ): Promise<UserFindResponse> {
    const url = `${this.baseUrl}/api/v1/users/${uid}`;
    const response = await fetch(url, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as UserFindResponse;
  }

  async usersUpdate(
    uid: string,
    body: UserUpdateRequest,
  ): Promise<UserFindResponse> {
    const url = `${this.baseUrl}/api/v1/users/${uid}`;
    const response = await fetch(url, {
      method: 'PUT',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
      body: JSON.stringify(body),
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as UserFindResponse;
  }

  async usersDeactivate(
    uid: string,
  ): Promise<UserFindResponse> {
    const url = `${this.baseUrl}/api/v1/users/${uid}/deactivate`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as UserFindResponse;
  }

  async usersReactivate(
    uid: string,
  ): Promise<UserFindResponse> {
    const url = `${this.baseUrl}/api/v1/users/${uid}/reactivate`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as UserFindResponse;
  }

  async usersUpdateRoles(
    uid: string,
    body: UserRolesRequest,
  ): Promise<UserFindResponse> {
    const url = `${this.baseUrl}/api/v1/users/${uid}/roles`;
    const response = await fetch(url, {
      method: 'PUT',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
      body: JSON.stringify(body),
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as UserFindResponse;
  }

  async usersSuspend(
    uid: string,
  ): Promise<UserFindResponse> {
    const url = `${this.baseUrl}/api/v1/users/${uid}/suspend`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        ...(this.credentials.bearerAuth ? { 'Authorization': `Bearer ${this.credentials.bearerAuth}` } : {}),
      },
    });
    if (!response.ok) {
      const contentType = response.headers.get('content-type') ?? '';
      let body: unknown;
      try {
        if (contentType.includes('json')) {
          body = await response.json();
        } else if (contentType.startsWith('text/')) {
          body = await response.text();
        } else if (response.headers.get('content-length') !== '0') {
          body = await response.blob();
        }
      } catch {
        // Response body was unreadable / malformed — leave `body` undefined so the
        // caller still gets the status and can inspect headers if needed.
      }
      throw new ApiError(response.status, response.statusText, body);
    }
    return await response.json() as UserFindResponse;
  }
}
